version: '3.8'
services:
  wonderwall:
    image: ghcr.io/nais/wonderwall:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    command: >
      --auto-login=true
      --openid.provider=azure
      --ingress=http://localhost:8080
      --bind-address=0.0.0.0:8080
      --upstream-host=frontend:8081
      --log-level=debug
      --log-format=text
    restart: on-failure
    environment:
      WONDERWALL_OPENID_CLIENT_JWK: "${AZURE_APP_JWK}"
      WONDERWALL_OPENID_CLIENT_ID: "${AZURE_APP_CLIENT_ID}"
      WONDERWALL_OPENID_WELL_KNOWN_URL: "${AZURE_APP_WELL_KNOWN_URL}"
  frontend:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
      secrets:
        - npmrc
    ports:
      - "8081:8081"
    environment:
      NODE_ENV: "development"
      EXPRESS_PORT: "8081"
      EXPRESS_HOST: "::"
      AZURE_APP_CLIENT_ID: "${AZURE_APP_CLIENT_ID}"
      AZURE_OPENID_CONFIG_ISSUER: "${AZURE_OPENID_CONFIG_ISSUER}"
      AZURE_OPENID_CONFIG_TOKEN_ENDPOINT: "${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}"
      AZURE_APP_JWK: "${AZURE_APP_JWK}"
      AZURE_OPENID_CONFIG_JWKS_URI: "${AZURE_OPENID_CONFIG_JWKS_URI}"
      SKRIBENTEN_API_URL: "https://pensjon-skribenten.intern.dev.nav.no"
      SKRIBENTEN_API_SCOPE: "api://dev-gcp.pensjonsbrev.skribenten-backend/.default"

secrets:
  npmrc:
    file: ~/.npmrc