// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdetid

import no.nav.pensjon.brevbaker.api.model.BrevbakerType.Kroner

data class Trygdetid(
    val fatta10netto: Kroner?,
    val fatteos: Int?,
    val fattnorge: Int?,
    val framtidigtteos: Int?,
    val framtidigttnorsk: Int?,
    val ttnevnereos: Int?,
    val ttnevnernordisk: Int?,
    val ttnordisk: Int?,
    val tttellereos: Int?,
    val tttellernordisk: Int?
)
