// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdetid

import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdetid.fatt.Fatt

data class Trygdetid(
    val fatt: Fatt?,
    val fatteos: Int?,
    val fattnorge: Int?,
    val framtidigtteos: Int?,
    val framtidigttnorsk: Int?,
    val ttnevnereos: Int?,
    val ttnevnernordisk: Int?,
    val ttnordisk: Int?,
    val tttellereos: Int?,
    val tttellernordisk: Int?
)
