apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app-name}}
  namespace: "pensjonsbrev"
  labels:
    "team": "pensjonsbrev"
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: /internal/health/liveness
    initialDelay: 5
  readiness:
    path: /internal/health/readiness
    initialDelay: 5
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true
      singlePageApplication: true
      allowAllUsers: false
      claims:
        groups:
          {{#each groups as |group|}}
             - id: {{group}}
          {{/each}}
        extra:
          - azp_name
          - NAVident
      replyURLs:
        - "http://localhost:8080/oauth2/callback"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - "/bff/*"

  accessPolicy:
    outbound:
      rules:
        {{#each outboundApps as |rule|}}
          - application: {{rule.application}}
            namespace: {{rule.namespace}}
            cluster: {{rule.cluster}}
        {{/each}}

  ingresses:
    {{#each ingresses as |url|}}
       - {{url}}
    {{/each}}

  env:
    {{#each env as |e|}}
       - name: {{e.name}}
         value: "{{{e.value}}}"
    {{/each}}