// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningperiode.beregningytelsekomp.sertillegg

import no.nav.pensjon.brevbaker.api.model.BrevbakerType.Kroner

data class Sertillegg(
    val stbrutto: Kroner?,
    val stinnvilget: Boolean?,
    val stnetto: Kroner?
)
