// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdetidsgrunnlaglistenor.trygdetidsgrunnlag

import java.time.LocalDate

data class Trygdetidsgrunnlag(
    val trygdetidfom: LocalDate?,
    val trygdetidtom: LocalDate?
)
