#######
# Denne er brukt til å gjøre det mulig å bruke tokens lokalt
#
# secret kan hentes fra cluster med "kubectl -n pensjonsbrev get secret azure-pensjonsbrev-tjenestebuss-lokal -o json | jq '.data | map_values(@base64d)'"
#
# Kjøres en gang eller ved endringer med
# kubectl apply -f .nais/azure-ad-app-lokal.yml
###
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: pensjonsbrev-tjenestebuss-lokal
  namespace: pensjonsbrev
  labels:
    team: pensjonsbrev
spec:
  secretName: azure-pensjonsbrev-tjenestebuss-lokal
  replyUrls:
    - url: "http://localhost:8082/oauth2/callback"
  claims:
    extra:
      - "azp_name"
    groups:
      - id: "8bb9b8d1-f46a-4ade-8ee8-5895eccdf8cf" #0000-GA-PENSJON_SAKSBEHANDLER i preprod

  preAuthorizedApplications:
    - application: azure-token-generator
      cluster: dev-gcp
      namespace: aura
    - application: skribenten-backend-lokal
      cluster: dev-gcp
      namespace: pensjonsbrev
