app-name: "pensjonsbrev-tjenestebuss"
ingresses:
  - "https://pensjonsbrev-tjenestebuss.intern.dev.nav.no"
env:
  - name: TJENESTEBUSS_URL
    value: "https://tjenestebuss-q2.adeo.no/"
  - name: STS_URL
    value: "https://security-token-service.dev.adeo.no"

inboundRules:
  - application: skribenten-backend
    namespace: pensjonsbrev
    cluster: dev-gcp
  - application: skribenten-backend-lokal
    namespace: pensjonsbrev
    cluster: dev-gcp

externalHosts:
  - host: https://tjenestebuss-q2.adeo.no
  - host: https://security-token-service.dev.adeo.no