apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app-name}}
  namespace: "pensjonsbrev"
  labels:
    "team": "pensjonsbrev"
spec:
  webproxy: true
  image: {{image}}
  port: 8080
  service:
    port: 80
    protocol: http
  liveness:
    path: "/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 10
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
    port: "8080"
  logging:
    destinations:
      - id: elastic
      - id: loki
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          {{#each groups as |group|}}
             - id: {{group}}
          {{/each}}
  vault:
    enabled: true
    paths:
      {{#each vaultPaths as |path|}}
        - kvPath: {{path.kvPath}}
          mountPath: {{path.mountPath}}
      {{/each}}

  accessPolicy:
    outbound:
      external:
        {{#each externalHosts as |host|}}
          - host: {{host}}
        {{/each}}

    inbound:
      rules:
        {{#each inboundRules as |rule|}}
          - application: {{rule.application}}
            namespace: {{rule.namespace}}
            cluster: {{rule.cluster}}
        {{/each}}
  ingresses:
    {{#each ingresses as |url|}}
       - {{url}}
    {{/each}}
  env:
    {{#each env as |e|}}
       - name: {{e.name}}
         value: {{{e.value}}}
    {{/each}}