apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "pensjonsbrev-tjenestebuss"
  namespace: "pensjonsbrev"
  labels:
    "team": "pensjonsbrev"
spec:
  image: {{image}}
  port: 8080
  service:
    port: 80
    protocol: http
  liveness:
    path: "/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 10
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
    port: "8080"
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "300m"
    memory: "512Mi"

  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "8bb9b8d1-f46a-4ade-8ee8-5895eccdf8cf" #0000-GA-PENSJON_SAKSBEHANDLER i preprod

  accessPolicy:
    outbound:
      rules:
        {{#each outboundRules as |rule|}}
           - application: {{rule.application}}
             namespace: {{rule.namespace}}
             cluster: {{rule.cluster}}
        {{/each}}
      external:
        {{#each externalHosts as |host|}}
          - host: {{host}}
        {{/each}}

    inbound:
      rules:
        {{#each inboundRules as |rule|}}
          - application: {{rule.application}}
            namespace: {{rule.namespace}}
            cluster: {{rule.cluster}}
        {{/each}}
  ingresses:
    {{#each ingresses as |url|}}
       - {{url}}
    {{/each}}
  env:
    {{#each env as |e|}}
       - name: {{e.name}}
         value: {{{e.value}}}
    {{/each}}