app-name: "pensjonsbrev-tjenestebuss"
ingresses:
  - "https://pensjonsbrev-tjenestebuss.intern.nav.no"
  - "https://pensjonsbrev-tjenestebuss.prod-fss-pub.nais.io"
env:
  - name: STS_URL
    value: "https://security-token-service.nais.adeo.no"
  - name: SAMHANDLERSERVICE_URL
    value: "https://wasapp.adeo.no/"

groups:
  - "0af3955f-df85-4eb0-b5b2-45bf2c8aeb9e" #0000-GA-PENSJON_SAKSBEHANDLER
  - "7845a796-1516-4d14-b500-fd65c001f35c" #0000-GA-PENSJON_BRUKERHJELPA
  - "11053fd7-e674-4552-9a88-f9fcedfa70b3" #0000-GA-PENSJON_ATTESTERING
  - "959ead5b-99b5-466b-a0ff-5fdbc687517b" #0000-GA-Pensjon_VEILEDER
  - "70ef8e7f-7456-4298-95e0-b13c0ef2422b" #0000-GA-Pensjon_Okonomi
  - "8d5e0211-6c41-4ed3-be74-dd19a210ebab" #0000-GA-PENSJON_KLAGEBEH

vaultPaths:
  - kvPath: "/kv/prod/fss/pensjonsbrev-tjenestebuss/pensjonsbrev"
    mountPath: "/secrets/pensjonsbrev"
inboundRules:
  - application: skribenten-backend
    namespace: pensjonsbrev
    cluster: prod-gcp

externalHosts:
  - login.microsoftonline.com
  - wasapp.adeo.no
