#!/bin/sh
set -e

DIRS="brevoppskrift-web/bff brevoppskrift-web/frontend skribenten-web/bff skribenten-web/frontend"

for dir in $DIRS; do
  if [ -d "$dir/node_modules/lint-staged" ]; then
    echo 📂 $dir
    npx --prefix $dir lint-staged -v --cwd $dir
  else
    echo "💡 run 'npm --prefix $dir ci' to prepare pre-commit checks"
  fi
done

