// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.vilkarsvedtaklist

import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.vilkarsvedtaklist.vilkarsvedtak.Vilkarsvedtak

data class Vilkarsvedtaklist(
    val vilkarsvedtak: List<Vilkarsvedtak>?
)
