// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningnokkelinfo.beregningnokkelinfo2.ypt.poengrekke

data class Poengrekke(
    val poengaryrke: Int?,
    val poengaryrkee91: Int?,
    val poengaryrkef92: Int?
)
