package no.nav.pensjon.brev.ufore.api.model

import no.nav.pensjon.brev.api.model.maler.Brevkode.Automatisk
import no.nav.pensjon.brev.api.model.maler.Brevkode.Redigerbart
import no.nav.pensjon.brevbaker.api.model.AlltidValgbartVedleggKode

object Ufoerebrevkoder {
    enum class AutoBrev : Automatisk {
        UT_INFO_ENDRET_PGA_INNTEKT
        ;
        override fun kode(): String = this.name
    }

    enum class Redigerbar : Redigerbart {
        UT_AVSLAG_HENSIKTSMESSIG_BEHANDLING,
        UT_AVSLAG_HENSIKTSMESSIG_ARB_TILTAK_I1,
        UT_AVSLAG_HENSIKTSMESSIG_ARB_TILTAK_I2,
        UT_AVSLAG_SYKDOM,
        UT_AVSLAG_ALDER,
        UT_AVSLAG_MANGLENDE_DOK,
        UT_AVSLAG_INNTEKTSEVNE_50,
        UT_AVSLAG_INNTEKTSEVNE_40,
        UT_AVSLAG_INNTEKTSEVNE_30,
        UT_AVSLAG_UNG_UFOR_36,
        UT_AVSLAG_UNG_UFOR_26,
        UT_AVSLAG_UNG_UFOR_VARIG,
        UT_AVSLAG_YRKESSKADE_GODKJENT,
        UT_AVSLAG_YRKESSKADE_IKKE_GODKJENT,
        UT_AVSLAG_IFU_IKKE_VARIG,
        UT_AVSLAG_IFU_OKT_STILLING,
        UT_AVSLAG_OKT_GRAD_INNTEKTSEVNE,
        UT_AVSLAG_OKT_GRAD_HENSIKTSMESSIG_BEHANDLING,
        UT_AVSLAG_OKT_GRAD_HENSIKTSMESSIG_ARB_TILTAK_I1,
        UT_AVSLAG_OKT_GRAD_HENSIKTSMESSIG_ARB_TILTAK_I2,
        UT_AVSLAG_OKT_GRAD_SYKDOM,
        UT_AVSLAG_OKT_GRAD_MANGLENDE_DOK,
        UT_AVSLAG_MEDLEMSKAP,
        UT_VEDTAK_FEILUTBETALING,
        UT_VEDTAK_FEILUTBETALING_INGEN_TILBAKEKREVING,
        UT_VEDTAK_FEILUTBETALING_ETTERGITT_FORELDET,
        UT_VARSEL_FEILUTBETALING,
        UT_AVSLAG_MEDLEMSKAP_UTLAND,
        UT_FEILUTBETALING_VARSEL_SIVILSTAND,
        UT_FEILUTBETALING_VARSEL_SIVILSTAND_UU,
        UT_FEILUTBETALING_VARSEL_BARN_FLYTTER,
        UT_FEILUTBETALING_VARSEL_BARN_UTLAND,
        UT_FEILUTBETALING_VARSEL_INSTITUSJON,
        UT_FEILUTBETALING_VARSEL_SONING,
        UT_FEILUTBETALING_VARSEL_DODSBO,
        UT_INNH_OPPL_SOKNAD_BARNETILLEGG,
        UT_INNH_OPPL_SOKNAD_BARNETILLEGG_UTLAND,
        UT_INNH_OPPL_SOKNAD_BARNETILLEGG_FOSTERFORELDER,
        UT_INNH_OPPL_BRUKER_LEGEERKLAERING,
        UT_INNH_OPPL_LEGE_LEGEERKLAERING,
        UT_INNH_OPPL_NAERINGSINNTEKTER,
        UT_INNH_OPPL_FLERE_OPPL_GENERELL,
        UT_INNH_OPPL_FLERE_OPPL_FIRMAINNTEKT,
        UT_INNH_OPPL_UTSATT_KLAGEFRIST,
        UT_INNH_OPPL_TRUKKET_KLAGE,
        UT_INNH_OPPL_NY_SIVILSTAND,
        UT_INNH_OPPL_ANTATT_DOD,
        UT_INNH_OPPL_EKTEFELLE_UTLAND,
        UT_INNH_OPPL_OPPGITT_SAMBOER,
        UT_OMREGNING_UFOEREPENSJON_TIL_UFOERETRYGD,
        UT_S_HVILENDE_RETT_INFO_4_AAR,
        UT_S_HVILENDE_RETT_MIDL_OPPHOER,
        UT_S_HVILENDE_RETT_OPPHOER,
        UT_S_HVILENDE_RETT_VARSEL_OPPHOER,
        ;

        override fun kode(): String = this.name
    }

    enum class AlltidValgbareVedlegg(override val visningstekst: String) : AlltidValgbartVedleggKode {
        ;

        override val kode = name
    }
}