// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.vilkarsvedtaklist.vilkarsvedtak

data class Vilkarsvedtak(
    val vilkaranvendtvurdering: String?
)
