// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningytelsekomp.tilleggspensjon

import no.nav.pensjon.brevbaker.api.model.BrevbakerType.Kroner

data class Tilleggspensjon(
    val tpbrutto: Kroner?,
    val tpinnvilget: Boolean?,
    val tpnetto: Kroner?
)
