package no.nav.pensjon.brev.api.model.maler

object Brevkode {
    enum class AutoBrev {
        PE_ADHOC_2024_VEDTAK_GJENLEVENDETTER1970,
        PE_AP_ADHOC_2024_REGLERENDRET_GJR_AP_MNTINDV,
        PE_OMSORG_EGEN_AUTO,
        PE_OMSORG_HJELPESTOENAD_AUTO,
        UT_ADHOC_UFOERETRYGD_ETTERBETALING_DAGPENGER,
        UT_ADHOC_UFOERETRYGD_KOMBI_DAGPENGER,
        UT_ADHOC_UFOERETRYGD_KOMBI_DAGPENGER_AVKORTNING,
        UT_ADHOC_VARSEL_OPPHOER_EKTEFELLETILLEGG,
        UT_ADHOC_VARSEL_OPPHOER_MED_HVILENDE_RETT,
        UT_EO_FORHAANDSVARSEL_FEILUTBETALING_AUTO,
        UT_OMREGNING_ENSLIG_AUTO,
        UT_ENDRET_PGA_INNTEKT,
        UT_OPPHOER_BT_AUTO,
        UT_UNG_UFOER_20_AAR_AUTO,
        UT_VARSEL_SAKSBEHANDLINGSTID_AUTO,
        ;
    }

    enum class Redigerbar {
        INFORMASJON_OM_SAKSBEHANDLINGSTID,
        UT_ORIENTERING_OM_SAKSBEHANDLINGSTID,
        ;
    }
}