rootProject.name = "pensjonsbrev"

include("alder-brevbaker-api-model")
include("aldersmaler")
include("brevbaker")
include("brevbaker-api-model-common")
include("brevbaker-dsl")
include("etterlattemaler")
include("pdf-bygger")
include("pensjon-brevbaker")
include("pensjon-brevbaker-api-model")
include("pensjonsmaler")
include("skribenten-backend")
include("template-model-generator")
include("ufoere-brevbaker-api-model")
include("ufoeremaler")