// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.inngangogeksportgrunnlag

data class Inngangogeksportgrunnlag(
    val eksportforbud: Boolean?,
    val eksportunntak: String?,
    val minst20arbotid: Boolean?,
    val minstettarfmnorge: Boolean?,
    val minsttrearsfmnorge: Boolean?,
    val oppfyltettergamleregler: Boolean?,
    val oppfyltvedsammenlegging: Boolean?,
    val unntakfraforutgaendemedlemskap: Boolean?
)
