// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdetidsgrunnlaglisteeos

import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdetidsgrunnlaglisteeos.trygdetidsgrunnlageos.Trygdetidsgrunnlageos

data class Trygdetidsgrunnlaglisteeos(
    val trygdetidsgrunnlageos: Trygdetidsgrunnlageos?
)
