/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplateMalTypeTemplateIdRouteImport } from './routes/template.$malType.$templateId'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateMalTypeTemplateIdRoute =
  TemplateMalTypeTemplateIdRouteImport.update({
    id: '/template/$malType/$templateId',
    path: '/template/$malType/$templateId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/templates': typeof TemplatesRoute
  '/template/$malType/$templateId': typeof TemplateMalTypeTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/templates': typeof TemplatesRoute
  '/template/$malType/$templateId': typeof TemplateMalTypeTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/templates': typeof TemplatesRoute
  '/template/$malType/$templateId': typeof TemplateMalTypeTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/templates' | '/template/$malType/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/templates' | '/template/$malType/$templateId'
  id: '__root__' | '/' | '/templates' | '/template/$malType/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TemplatesRoute: typeof TemplatesRoute
  TemplateMalTypeTemplateIdRoute: typeof TemplateMalTypeTemplateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$malType/$templateId': {
      id: '/template/$malType/$templateId'
      path: '/template/$malType/$templateId'
      fullPath: '/template/$malType/$templateId'
      preLoaderRoute: typeof TemplateMalTypeTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TemplatesRoute: TemplatesRoute,
  TemplateMalTypeTemplateIdRoute: TemplateMalTypeTemplateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
