// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningsinformasjonkapittel19

data class Beregningsinformasjonkapittel19(
    val yug: Int?
)
