// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningytelsekomp.grunnpensjon

import no.nav.pensjon.brevbaker.api.model.BrevbakerType.Kroner

data class Grunnpensjon(
    val gpbrutto: Kroner?,
    val gpnetto: Kroner?
)
