// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.kravhode

import java.time.LocalDate

data class Kravhode(
    val behandlendeenhet: String?,
    val kravmottatdato: LocalDate?,
    val vurderetrygdeavtale: Boolean?
)
