// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningssammendragavdod

import java.time.LocalDate

data class Beregningssammendragavdod(
    val avdoddodsdato: LocalDate?,
    val avdoddodsfallskyldesyrkesskade: Boolean?,
    val avdodflyktning: Boolean?,
    val avdodskadetidspunktyrkesskade: LocalDate?,
    val avdodunguforfodtetter1940: Boolean?,
    val avdodunguforfodtfor1941: Boolean?
)
