// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningperiode.beregningytelseskomp

import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningperiode.beregningytelseskomp.familietillegg.Familietillegg
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningperiode.beregningytelseskomp.fasteutgifter.Fasteutgifter
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningperiode.beregningytelseskomp.grunnpensjon.Grunnpensjon
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningperiode.beregningytelseskomp.sertillegg.Sertillegg
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningperiode.beregningytelseskomp.tilleggspensjon.Tilleggspensjon

data class Beregningytelseskomp(
    val familietillegg: Familietillegg?,
    val fasteutgifter: Fasteutgifter?,
    val grunnpensjon: Grunnpensjon?,
    val sertillegg: Sertillegg?,
    val tilleggspensjon: Tilleggspensjon?
)
