// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdetidsgrunnlaglisteeos.trygdetidsgrunnlageos

import java.time.LocalDate

data class Trygdetidsgrunnlageos(
    val trygdetideosland: String?,
    val trygdetidfomeos: LocalDate?,
    val trygdetidtomeos: LocalDate?
)
