// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningnokkelinfo.beregningnokkelinfo2.spt.poengrekke

import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningnokkelinfo.beregningnokkelinfo2.spt.poengrekke.poengtall.Poengtall

data class Poengrekke(
    val framtidigpoengarnordenbrutto: Int?,
    val framtidigpoengarnordennetto: Int?,
    val framtidigpoengtall: Int?,
    val poengarnevnereos: Int?,
    val poengartellereos: Int?,
    val poengarutenok: Int?,
    val poengarutenoke91: Int?,
    val poengarutenokf92: Int?,
    val poengarutenokfaktiskeeos: Int?,
    val poengarutenokfaktiskenorden: Int?,
    val poengarutenokfaktiskenorge: Int?,
    val poengarutenokteoretiskeos: Int?,
    val poengtall: Poengtall?
)
