#######
# Denne er brukt til å gjøre det mulig å bruke tokens lokalt
#
# secret kan hentes fra cluster med "kubectl -n pensjonsbrev get secret azure-skribenten-backend-lokal -o json | jq '.data | map_values(@base64d)'"
#
# Kjøres en gang eller ved endringer med
# kubectl apply -f .nais/azure-ad-app-lokal.yml
###
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: skribenten-backend-lokal
  namespace: pensjonsbrev
  labels:
    team: pensjonsbrev
database:
  auditlog: "off"
spec:
  secretName: azure-skribenten-backend-lokal
  replyUrls:
    - url: "http://localhost:8082/oauth2/callback"
  claims:
    groups:
      - id: "8bb9b8d1-f46a-4ade-8ee8-5895eccdf8cf" #0000-GA-PENSJON_SAKSBEHANDLER
      - id: "bda6bd68-77e6-4c00-96b9-7ecf5df7413c" #0000-GA-Pensjon_Utland
      - id: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" #0000-GA-Fortrolig_Adresse
      - id: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" #0000-GA-Strengt_Fortrolig_Adresse
      - id: "fc792042-93d8-4d5e-a501-55c45c03c576" #0000-GA-Person-EndreStrengtFortroligUtland
      - id: "63f46f74-84a8-4d1c-87a8-78532ab3ae60" #0000-GA-PENSJON_ATTESTERING
    extra:
      - "azp_name"
  preAuthorizedApplications:
    - application: skribenten-web
      cluster: dev-gcp
      namespace: pensjonsbrev
    - application: skribenten-web
      cluster: dev-gcp
      namespace: pensjonsbrev
