#######
# Denne er brukt til å gjøre det mulig å bruke tokens lokalt
#
# secret kan hentes fra cluster med "kubectl -n pensjonsbrev get secret azure-skribenten-backend-lokal -o json | jq '.data | map_values(@base64d)'"
#
# Kjøres en gang eller ved endringer med
# kubectl apply -f .nais/azure-ad-app-lokal.yml
###
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: skribenten-backend-lokal
  namespace: pensjonsbrev
  labels:
    team: pensjonsbrev
spec:
  secretName: azure-skribenten-backend-lokal
  replyUrls:
    - url: "http://localhost:8082/oauth2/callback"
  claims:
    groups:
      - id: "8bb9b8d1-f46a-4ade-8ee8-5895eccdf8cf" #0000-GA-PENSJON_SAKSBEHANDLER
      - id: "bda6bd68-77e6-4c00-96b9-7ecf5df7413c" #0000-GA-Pensjon_Utland
    extra:
      - "azp_name"
  preAuthorizedApplications:
    - application: skribenten-web
      cluster: dev-gcp
      namespace: pensjonsbrev
    - application: skribenten-web
      cluster: dev-gcp
      namespace: pensjonsbrev
