app-name: "skribenten-backend"
brevbaker-app: "pensjon-brevbaker"
ingresses:
  - "https://pensjon-skribenten-api.intern.dev.nav.no"
env:
  - name: CORS_ALLOW_HOST
    value: "pensjon-skribenten.intern.dev.nav.no"
  - name: PEN_URL
    value: "https://pensjon-pen-q2.dev.adeo.no/pen/springapi/"
  - name: PEN_SCOPE
    value: "api://dev-fss.teampensjon.pensjon-pen-q2/.default"
  - name: BREVBAKER_URL
    value: "https://pensjon-brevbaker.intern.dev.nav.no"
  - name: BREVBAKER_SCOPE
    value: "api://dev-gcp.pensjonsbrev.pensjon-brevbaker/.default"
  - name: BREVMETADATA_URL
    value: "https://pensjon-brevmetadata-q2.intern.dev.nav.no"

preAuthorized:
  - name: skribenten-frontend
    namespace: pensjonsbrev
    cluster: dev-gcp
  - name: skribenten-web
    namespace: pensjonsbrev
    cluster: dev-gcp
  - name: skribenten-frontend-lokal
    namespace: pensjonsbrev
    cluster: dev-gcp