app-name: "skribenten-backend"

groups:
  #0000-GA-PENSJON_BRUKERHJELPA
  - name: "PENSJON_BRUKERHJELPA"
    id: "9e122ddd-e542-4cc1-a7eb-92c99140fe0e"
  #0000-GA-PENSJON_SAKSBEHANDLER
  - name: "PENSJON_SAKSBEHANDLER"
    id: "8bb9b8d1-f46a-4ade-8ee8-5895eccdf8cf"
  #0000-GA-Pensjon_Utland
  - name: "Pensjon_Utland"
    id: "bda6bd68-77e6-4c00-96b9-7ecf5df7413c"
  #0000-GA-Fortrolig_Adresse
  - name: "Fortrolig_Adresse"
    id: "ea930b6b-9397-44d9-b9e6-f4cf527a632a"
  #0000-GA-Strengt_Fortrolig_Adresse
  - name: "Strengt_Fortrolig_Adresse"
    id: "5ef775f2-61f8-4283-bf3d-8d03f428aa14"
  #0000-GA-Person-EndreStrengtFortroligUtland
  - name: "EndreStrengtFortroligUtland"
    id: "fc792042-93d8-4d5e-a501-55c45c03c576"

inboundRules:
  - application: skribenten-web
    namespace: pensjonsbrev
    cluster: dev-gcp
  - application: azure-token-generator
    namespace: aura
    cluster: dev-gcp

outboundRules:
  - application: pensjon-brevbaker
    namespace: pensjonsbrev
    cluster: dev-gcp
  - application: pensjon-brevmetadata-q2
    namespace: pensjonsbrev
    cluster: dev-gcp
  - application: digdir-krr-proxy
    namespace: team-rocket
    cluster: dev-gcp

externalHosts:
  - pdl-api.dev-fss-pub.nais.io
  - pensjon-pen-q2.dev-fss-pub.nais.io
  - saf-q2.dev-fss-pub.nais.io
  - pensjon-persondata-q2.dev-fss-pub.nais.io
  - pensjonsbrev-tjenestebuss-q2.dev-fss-pub.nais.io
  - navansatt.dev-fss-pub.nais.io
  - pensjon-samhandler-proxy-q2.dev-fss-pub.nais.io
  - teampensjon-unleash-api.nav.cloud.nais.io

env:
  - name: CORS_ALLOW_HOST
    value: "pensjon-skribenten-web-q2.intern.dev.nav.no"

  - name: PEN_URL
    value: "https://pensjon-pen-q2.dev-fss-pub.nais.io/pen/api/"
  - name: PEN_SCOPE
    value: "api://dev-fss.pensjon-q2.pensjon-pen-q2/.default"

  - name: BREVBAKER_URL
    value: "http://pensjon-brevbaker"
  - name: BREVBAKER_SCOPE
    value: "api://dev-gcp.pensjonsbrev.pensjon-brevbaker/.default"

  - name: BREVMETADATA_URL
    value: "http://pensjon-brevmetadata-q2"

  - name: PDL_URL
    value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
  - name: PDL_SCOPE
    value: "api://dev-fss.pdl.pdl-api/.default"

  - name: SAF_URL
    value: "https://saf-q2.dev-fss-pub.nais.io/graphql"
  - name: SAF_SCOPE
    value: "api://dev-fss.teamdokumenthandtering.saf/.default"
  - name: SAF_REST_URL
    value: "https://saf-q2.dev-fss-pub.nais.io/rest"

  - name: KRR_URL
    value: "http://digdir-krr-proxy.team-rocket"
  - name: KRR_SCOPE
    value: "api://dev-gcp.team-rocket.digdir-krr-proxy/.default"

  - name: PENSJON_PERSONDATA_URL
    value: "https://pensjon-persondata-q2.dev-fss-pub.nais.io"
  - name: PENSJON_PERSONDATA_SCOPE
    value: "api://dev-fss.pensjon-person.pensjon-persondata-q2/.default"

  - name: TJENESTEBUSS_INTEGRASJON_URL
    value: "https://pensjonsbrev-tjenestebuss-q2.dev-fss-pub.nais.io"
  - name: TJENESTEBUSS_INTEGRASJON_SCOPE
    value: "api://dev-fss.pensjonsbrev.pensjonsbrev-tjenestebuss-q2/.default"

  - name: NAVANSATT_URL
    value: "https://navansatt.dev-fss-pub.nais.io/"
  - name: NAVANSATT_SCOPE
    value: "api://dev-fss.teampensjon.navansatt/.default"

  - name: SAMHANDLER_PROXY_URL
    value: "https://pensjon-samhandler-proxy-q2.dev-fss-pub.nais.io"
  - name: SAMHANDLER_PROXY_SCOPE
    value: "api://dev-fss.pensjon-q2.pensjon-samhandler-proxy-q2/.default"

  - name: FEATURE_brevbakerbrev
    value: "true"
