apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app-name}}
  namespace: "pensjonsbrev"
  labels:
    "team": "pensjonsbrev"
spec:
  image: {{image}}
  port: 8080
  service:
    port: 80
    protocol: http
  liveness:
    path: "/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 10
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
    port: "8080"
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "300m"
    memory: "512Mi"

  azure:
    application:
      enabled: true
      allowAllUsers: {{allowAllUsers}}
      claims:
        extra:
          - azp_name
      replyURLs:
        {{#each ingresses as |url|}}
           - {{url}}/oauth2/callback
        {{/each}}
  accessPolicy:
    outbound:
      rules:
        - application: {{brevbaker-app}}
    inbound:
      rules:
        {{#each preAuthorized as |app|}}
          - application: {{app.name}}
            namespace: {{app.namespace}}
            cluster: {{app.cluster}}
        {{/each}}
  ingresses:
    {{#each ingresses as |url|}}
      - {{url}}
    {{/each}}
  env:
    {{#each env as |e|}}
       - name: {{e.name }}
         value: {{{e.value }}}
    {{/each}}