app-name: "skribenten-backend"

database:
  auditlog: "on"

ingresses:
  - "https://pensjon-skribenten-api.intern.nav.no"

groups:
  #0000-GA-PENSJON_BRUKERHJELPA
  - name: "BrukerhjelpA"
    id: "7845a796-1516-4d14-b500-fd65c001f35c"
  #0000-GA-PENSJON_SAKSBEHANDLER
  - name: "Saksbehandler"
    id: "0af3955f-df85-4eb0-b5b2-45bf2c8aeb9e"
  #0000-GA-Pensjon_Utland
  - name: "Pensjon_Utland"
    id: "7c2f2439-b67a-41c0-b50b-0abb02e3b479"
  #0000-GA-Fortrolig_Adresse
  - name: "Fortrolig_Adresse"
    id: "9ec6487d-f37a-4aad-a027-cd221c1ac32b"
  #0000-GA-Strengt_Fortrolig_Adresse
  - name: "Strengt_Fortrolig_Adresse"
    id: "ad7b87a6-9180-467c-affc-20a566b0fec0"
  #0000-GA-PENSJON_ATTESTERING
  - name: "Attestant"
    id: "11053fd7-e674-4552-9a88-f9fcedfa70b3"
  #0000-GA-Pensjon_VEILEDER
  - name: "Veileder"
    id: "959ead5b-99b5-466b-a0ff-5fdbc687517b"
  #0000-GA-Pensjon_Okonomi
  - name: "Okonomi"
    id: "70ef8e7f-7456-4298-95e0-b13c0ef2422b"
  #0000-GA-PENSJON_KLAGEBEH
  - name: "Klagebehandler"
    id: "8d5e0211-6c41-4ed3-be74-dd19a210ebab"

inboundRules:
  - application: skribenten-web
    namespace: pensjonsbrev
    cluster: prod-gcp

  - application: pensjon-pen
    namespace: pensjondeployer
    cluster: prod-fss

outboundRules:
  - application: pensjon-brevbaker
    namespace: pensjonsbrev
    cluster: prod-gcp
  - application: pensjon-brevmetadata
    namespace: pensjonsbrev
    cluster: prod-gcp
  - application: digdir-krr-proxy
    namespace: team-rocket
    cluster: prod-gcp

externalHosts:
  - pdl-api.prod-fss-pub.nais.io
  - pensjon-pen.prod-fss-pub.nais.io
  - saf.prod-fss-pub.nais.io
  - pensjon-persondata.prod-fss-pub.nais.io
  - pensjonsbrev-tjenestebuss.prod-fss-pub.nais.io
  - navansatt.prod-fss-pub.nais.io
  - pensjon-samhandler-proxy.prod-fss-pub.nais.io
  - teampensjon-unleash-api.nav.cloud.nais.io
  - norg2.intern.nav.no

env:
  - name: CORS_ALLOW_HOST
    value: "pensjon-skribenten.intern.nav.no"

  - name: PEN_URL
    value: "https://pensjon-pen.prod-fss-pub.nais.io/pen/api/"
  - name: PEN_SCOPE
    value: "api://prod-fss.pensjondeployer.pensjon-pen/.default"

  - name: BREVBAKER_URL
    value: "http://pensjon-brevbaker"
  - name: BREVBAKER_SCOPE
    value: "api://prod-gcp.pensjonsbrev.pensjon-brevbaker/.default"

  - name: BREVMETADATA_URL
    value: "http://pensjon-brevmetadata"

  - name: PDL_URL
    value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
  - name: PDL_SCOPE
    value: "api://prod-fss.pdl.pdl-api/.default"

  - name: SAF_URL
    value: "https://saf.prod-fss-pub.nais.io/graphql"
  - name: SAF_SCOPE
    value: "api://prod-fss.teamdokumenthandtering.saf/.default"
  - name: SAF_REST_URL
    value: "https://saf.prod-fss-pub.nais.io/rest"

  - name: KRR_URL
    value: "http://digdir-krr-proxy.team-rocket"
  - name: KRR_SCOPE
    value: "api://prod-gcp.team-rocket.digdir-krr-proxy/.default"

  - name: PENSJON_PERSONDATA_URL
    value: "https://pensjon-persondata.prod-fss-pub.nais.io"
  - name: PENSJON_PERSONDATA_SCOPE
    value: "api://prod-fss.pensjon-person.pensjon-persondata/.default"

  - name: TJENESTEBUSS_INTEGRASJON_URL
    value: "https://pensjonsbrev-tjenestebuss.prod-fss-pub.nais.io"
  - name: TJENESTEBUSS_INTEGRASJON_SCOPE
    value: "api://prod-fss.pensjonsbrev.pensjonsbrev-tjenestebuss/.default"

  - name: NAVANSATT_URL
    value: "https://navansatt.prod-fss-pub.nais.io/"
  - name: NAVANSATT_SCOPE
    value: "api://prod-fss.pensjondeployer.navansatt/.default"

  - name: SAMHANDLER_PROXY_URL
    value: "https://pensjon-samhandler-proxy.prod-fss-pub.nais.io"
  - name: SAMHANDLER_PROXY_SCOPE
    value: "api://prod-fss.pensjondeployer.pensjon-samhandler-proxy/.default"

  - name: NORG2_URL
    value: "https://norg2.intern.nav.no/norg2/"

  - name: SKRIBENTEN_WEB_URL
    value: "https://pensjon-skribenten.intern.nav.no"

  - name: VALKEY_INSTANCE_NAME
    value: "cache"