apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "skribenten-backend"
  namespace: "pensjonsbrev"
  labels:
    "team": "pensjonsbrev"
spec:
  image: {{image}}
  port: 8080
  service:
    port: 80
    protocol: http
  liveness:
    path: "/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 10
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
    port: "8080"
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "300m"
    memory: "512Mi"

  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - azp_name

  accessPolicy:
    inbound:
      rules:
        - application: skribenten-frontend
          namespace: pensjonsbrev
          cluster: dev-gcp
        - application: skribenten-web
          namespace: pensjonsbrev
          cluster: dev-gcp
        - application: skribenten-frontend-lokal
          namespace: pensjonsbrev
          cluster: dev-gcp
    outbound:
      rules:
        - application: pensjon-brevbaker
          namespace: pensjonsbrev
          cluster: dev-gcp
        - application: pensjon-brevmetadata-q2
          namespace: pensjonsbrev
          cluster: dev-gcp
        - application: digdir-krr-proxy
          namespace: team-rocket
          cluster: dev-gcp
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: pensjon-pen-q2.dev-fss-pub.nais.io
        - host: saf.intern.dev.nav.no
        - host: kodeverk.dev-fss-pub.nais.io
        - host: pensjon-persondata-q2.dev.intern.nav.no

  ingresses:
    - "https://pensjon-skribenten-api.intern.dev.nav.no"
  env:
    - name: CORS_ALLOW_HOST
      value: "pensjon-skribenten-eksperiment.intern.dev.nav.no"
    - name: PEN_URL
      value: "https://pensjon-pen-q2.dev-fss-pub.nais.io/pen/springapi/"
    - name: PEN_SCOPE
      value: "api://dev-fss.pensjon-q2.pensjon-pen-q2/.default"
    - name: BREVBAKER_URL
      value: "https://pensjon-brevbaker.intern.dev.nav.no"
    - name: BREVBAKER_SCOPE
      value: "api://dev-gcp.pensjonsbrev.pensjon-brevbaker/.default"
    - name: BREVMETADATA_URL
      value: "https://pensjon-brevmetadata-q2.intern.dev.nav.no"
    - name: MICROSOFT_GRAPH_URL
      value: "https://graph.microsoft.com/"
    - name: MICROSOFT_GRAPH_SCOPE
      value: "https://graph.microsoft.com/User.Read"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "api://dev-fss.pdl.pdl-api/.default"
    - name: SAF_URL
      value: "https://saf.intern.dev.nav.no/graphql"
    - name: SAF_SCOPE
      value: "api://dev-fss.teamdokumenthandtering.saf/.default"
    - name: KRR_SCOPE
      value: "api://dev-gcp.team-rocket.digdir-krr-proxy/.default"
    - name: KRR_URL
      value: "https://digdir-krr-proxy.intern.dev.nav.no"
    - name: KODEVERK_SERVICE
      value: "https://kodeverk.dev-fss-pub.nais.io/api/v1/kodeverk/"
    - name: PENSJON_PERSONDATA_SCOPE
      value: "api://dev-fss.pensjon-person.pensjon-persondata-q2/.default"
    - name: PENSJON_PERSONDATA_URL
      value: "https://pensjon-persondata-q2.dev.intern.nav.no"
