// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagsliste.inngangogeksportgrunnlag

data class Inngangogeksportgrunnlag(
    val eksportunntak: String?,
    val minst20arbotid: Boolean?
)
