package no.nav.pensjon.etterlatte.maler.fraser.common

object Constants {
    const val NAV_URL = "nav.no"
    const val SKATTEETATEN_URL = "skatteetaten.no"
    const val ARBEID_URL = "$NAV_URL/arbeid"
    const val SAKSBEHANDLINGSTIDER_URL = "$NAV_URL/saksbehandlingstider"
    const val BARNEPENSJON_URL = "$NAV_URL/barnepensjon"
    const val FINN_JOBBENE_URL = "$NAV_URL/finn-jobbene"
    const val FULLMAKT_URL = "$NAV_URL/fullmakt"
    const val HELSE_URL = "$NAV_URL/helse"
    const val UTBETALING_URL = "$NAV_URL/utbetalinger"
    const val UTBETALINGSDATOER_URL = "$NAV_URL/utbetalingsdatoer"
    const val SKRIVTILOSS_URL = "$NAV_URL/skriv-til-oss"
    const val KONTONUMMER_URL = "$NAV_URL/kontonummer"
    const val ENDRING_KONTONUMMER_URL = "$NAV_URL/start/soknad-endring-bankkontonummer"
    const val KONTAKT_URL = "$NAV_URL/kontaktoss"
    const val KLAGE_URL = "$NAV_URL/klage"
    const val GRUNNBELOEP_URL = "$NAV_URL/grunnbelopet"
    const val ETTERSENDELSE_URL = "$NAV_URL/ettersende"
    const val ETTERSENDE_OMS_URL = "$NAV_URL/ettersende#omstillingsstonad"
    const val OMS_MELD_INN_ENDRING_URL = "$NAV_URL/omstillingsstonad#melde"
    const val BESKJED_TIL_NAV_URL = "$NAV_URL/send-beskjed"
    const val BP_SKATTETREKK = "$NAV_URL/barnepensjon#skattetrekk"
    const val BP_SKATTEETATEN = "$SKATTEETATEN_URL/barnepensjon"
    const val BP_MELDE = "$NAV_URL/barnepensjon#melde"
    const val SKATTEETATEN_ENDRE_URL = "$SKATTEETATEN_URL/endre"
    const val SKATTEETATEN_KILDESKATTPENSJON_URL = "$SKATTEETATEN_URL/kildeskattpensjon"
    const val SKATTEETATEN_KONTAKTTELEFON_MED_LANDKODE = "(+47) 22 07 70 00"
    const val SKATTETREKK_ETTERBETALING_URL = "$NAV_URL/skattetrekk#etterbetaling"
    const val SKATTETREKK_KILDESKATT_URL = "$NAV_URL/skattetrekk#kildeskatt"
    const val OMS_ETTEROPPGJOER_URL = "$NAV_URL/omstillingsstonad#etteroppgjor"
    const val OMS_HVORLENGE_URL = "$NAV_URL/omstillingsstonad#hvor-lenge"
    const val OMS_AKTIVITET_URL = "$NAV_URL/omstillingsstonad#aktivitet"
    const val OMS_ANDRE_STOENADER_URL = "$NAV_URL/omstillingsstonad#andre-stonader"
    const val OMS_URL = "$NAV_URL/omstillingsstonad"
    const val POSTADRESSE = "Nav skanning, Postboks 1400, 0109 OSLO"
    const val KONTAKTTELEFON_PENSJON = "55 55 33 34"
    const val KONTAKTTELEFON_PENSJON_MED_LANDKODE = "(+47) $KONTAKTTELEFON_PENSJON"
    const val KONTAKTTELEFON_SKATT = "800 80 000"
    const val SAKSBEHANDLINGSTIDER_BP = "$SAKSBEHANDLINGSTIDER_URL#barnepensjon"
    const val SAKSBEHANDLINGSTIDER_OMS = "$SAKSBEHANDLINGSTIDER_URL#omstillingsstonad"

    object Engelsk {
        const val BARNEPENSJON_URL = "${Constants.BARNEPENSJON_URL}/en"
        const val BESKJED_TIL_NAV_URL = "${Constants.BESKJED_TIL_NAV_URL}/en"
        const val ETTERSENDE_OMS_URL = "${Constants.ETTERSENDELSE_URL}en#adjustment-allowance"
        const val ETTERSENDELSE_URL = "${Constants.ETTERSENDELSE_URL}/en"
        const val FULLMAKT_URL = "${Constants.FULLMAKT_URL}/en"
        const val KLAGE_URL = "${Constants.KLAGE_URL}/en"
        const val KONTONUMMER_URL = "${Constants.KONTONUMMER_URL}/en"
        const val KONTAKT_URL = "${Constants.KONTAKT_URL}/en"
        const val SKRIVTILOSS_URL = "${Constants.SKRIVTILOSS_URL}/en"
        const val UTBETALING_INFO = "${Constants.Utland.UTBETALING_INFO}/en"
        const val UTBETALINGSDATOER_URL = "${Constants.UTBETALINGSDATOER_URL}/en"
        const val SAKSBEHANDLINGSTIDER_URL = "${Constants.SAKSBEHANDLINGSTIDER_URL}/en"
        const val SAKSBEHANDLINGSTIDER_BP = "$SAKSBEHANDLINGSTIDER_URL#childrens-pension"
        const val SAKSBEHANDLINGSTIDER_OMS = "$SAKSBEHANDLINGSTIDER_URL#adjustment-allowance"
    }

    object Utland {
        const val BP = "$BARNEPENSJON_URL#utland"
        const val OMS = "$OMS_URL#utland"
        const val UTBETALING_INFO = "${NAV_URL}/utbetaling-utland"
        const val ENDRE_KONTONUMMER_SKJEMA_URL = "${NAV_URL}/soknader/en#bank-account-number-how-to-change"
        const val KONTAKTTELEFON_SKATT = "(+47) 22 07 70 00"
        const val POSTADRESSE = "Nav familie- og pensjonsytelser, Postboks 6600 Etterstad, 0607 Oslo, Norway"
    }
}
