// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning

import java.time.LocalDate
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningnokkelinfo.Beregningnokkelinfo
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningsinformasjonkapittel19.Beregningsinformasjonkapittel19
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningssammendragavdod.Beregningssammendragavdod
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningssammendragbruker.Beregningssammendragbruker
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningytelseskomp.Beregningytelseskomp
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.periodearsakliste.Periodearsakliste
import no.nav.pensjon.brevbaker.api.model.BrevbakerType.Kroner

data class Beregning(
    val beregningektefelleinntektover2g: Boolean?,
    val beregningektefellemottarpensjon: Boolean?,
    val beregningnokkelinfo: Beregningnokkelinfo?,
    val beregningsinformasjonkapittel19: Beregningsinformasjonkapittel19?,
    val beregningsivilstandanvendt: String?,
    val beregningssammendragavdod: Beregningssammendragavdod?,
    val beregningssammendragbruker: Beregningssammendragbruker?,
    val beregningytelseskomp: Beregningytelseskomp?,
    val brutto: Kroner?,
    val grunnbelop: Kroner?,
    val netto: Kroner?,
    val periodearsakliste: Periodearsakliste?,
    val virkdatofom: LocalDate?,
    val yug: Int?
)
