:docinfo: shared
:source-highlighter: highlight.js

= Brevmal struktur

En brevmal inneholder en nøstet struktur av elementer som brukes til å representere innhold.
Strukturen består av ulike DSL-scopes som gir deg tilgang til relevante funksjoner på hvert nivå.

TIP: Se xref:dsl/quickstart.adoc[] for en rask introduksjon til mal-utvikling.

== Scopes og funksjoner

Brevmal-DSL'en definerer ulike scopes hvor du kan definere ulike typer innhold.
DSL'en gjør kun tilgjengelig det innholdet som kan eksistere i en gitt kontekst,
noe som gjør det enklere å utforske muligheter og unngå feil.

For detaljert dokumentasjon av hvert scope, se xref:dsl/scopes.adoc[].

=== Kontrollstrukturer
I nesten alle scopes kan du bruke xref:dsl/kontroll-struktur/oversikt.adoc[]
for å styre visning av innhold:

* xref:dsl/kontroll-struktur/showIf.adoc[] - betinget visning
* xref:dsl/kontroll-struktur/ifNotNull.adoc[] - null-sikker visning
* xref:dsl/kontroll-struktur/forEach.adoc[] - løkker over lister
* xref:dsl/content/ifElse.adoc[] - velg mellom verdier

=== Scope-hierarki

[source]
----
createTemplate(...){ TemplateRootScope }
createAttachment(...){ OutlineScope }
----

==== xref:dsl/scopes.adoc#TemplateRootScope[TemplateRootScope]
Ytterste scope - definerer brevets struktur:
[source]
----
TemplateRootScope {
    title { PlainTextScope }
    outline { OutlineScope }
    includeAttachment
    includeAttachmentIfNotNull
}
----
Se: xref:dsl/vedlegg.adoc[]

==== xref:dsl/scopes.adoc#OutlineScope[OutlineScope]
Hoveddelen av brevet - overskrifter og avsnitt:
[source]
----
OutlineScope {
    includePhrase(OutlinePhrase) <1>
    title1 { PlainTextScope }
    title2 { PlainTextScope }
    title3 { PlainTextScope }
    paragraph { ParagraphScope }
}
----
(1) : xref:dsl/fraser/outlinePhrase.adoc[]

==== xref:dsl/scopes.adoc#ParagraphScope[ParagraphScope]
Inne i avsnitt - tekst, lister, tabeller:
[source]
----
ParagraphScope {
    includePhrase([Paragraph, Text, PlainText]Phrase)
    text(...)
    list { ... }        // Se: xref:dsl/lister.adoc[]
    table { ... }       // Se: xref:dsl/tabeller.adoc[]
    formText            // For redigerbare brev
    formChoice          // For redigerbare brev
    newline
}
----

==== xref:dsl/scopes.adoc#TextScope[TextScope]
Tekst med variabler og formattering:
[source]
----
TextScope {
    includePhrase([Text, PlainText]Phrase)
    text(...)           // Se: xref:dsl/content/formattering.adoc[]
}
----

==== xref:dsl/scopes.adoc#PlainTextScope[PlainTextScope]
Kun ren tekst (brukes i titler):
[source]
----
PlainTextScope {
    includePhrase(PlainTextPhrase)
    text(...)
}
----

== Fraser

Fraser er gjenbrukbare innholdsblokker. Se xref:dsl/fraser/oversikt.adoc[] for full dokumentasjon.

[cols="2,2,2"]
|===
|Frasetype |Brukes i |Dokumentasjon

|OutlinePhrase
|OutlineScope
|xref:dsl/fraser/outlinePhrase.adoc[]

|ParagraphPhrase
|ParagraphScope
|xref:dsl/fraser/paragraphPhrase.adoc[]

|TextOnlyPhrase
|TextScope
|xref:dsl/fraser/textOnlyPhrase.adoc[]

|PlainTextPhrase
|PlainTextScope
|xref:dsl/fraser/plainTextPhrase.adoc[]
|===

== Uttrykk og predikater

For å sammenligne verdier og lage betingelser, se xref:dsl/predikat/predikat.adoc[].

== Videre lesing

* xref:dsl/stegvis_guide_nytt_brev.adoc[]
* xref:dsl/scopes.adoc[]
* xref:dsl/kontroll-struktur/oversikt.adoc[]
* xref:dsl/fraser/oversikt.adoc[]
* xref:dsl/content/formattering.adoc[]
