:docinfo: shared
:source-highlighter: highlight.js
:toc:

= Outline

`outline` er hovedinnholdet i brevet. Her defineres overskrifter, avsnitt, lister og tabeller.

== Syntaks

[source,kotlin]
----
outline {
    title1 { ... }
    paragraph { ... }
    includePhrase(...)
}
----

== Tilgjengelige elementer

Inne i `outline` kan du bruke:

[cols="2,3,2"]
|===
|Element |Beskrivelse |Dokumentasjon

|`title1`
|Hovedoverskrift
|xref:dsl/outline/title1.adoc[title1]

|`title2`
|Underoverskrift
|xref:dsl/outline/title2.adoc[title2]

|`title3`
|Nivå 3 overskrift
|xref:dsl/outline/title3.adoc[title3]

|`paragraph`
|Avsnitt med innhold
|xref:dsl/outline/paragraph.adoc[paragraph]

|`includePhrase`
|Inkluder gjenbrukbar frase
|xref:dsl/phrases/includePhrase.adoc[includePhrase]

|`showIf`
|Betinget visning
|xref:dsl/outline/showIf.adoc[showIf]

|`ifNotNull`
|Null-sikker visning
|xref:dsl/outline/ifNotNull.adoc[ifNotNull]

|`forEach`
|Iterasjon
|xref:dsl/outline/forEach.adoc[forEach]
|===

== Eksempel

[source,kotlin]
----
outline {
    title1 {
        text(
            bokmal { +"Dette får du utbetalt" },
            nynorsk { +"Dette får du utbetalt" },
        )
    }

    paragraph {
        text(
            bokmal {
                +"Du får utbetalt "
                +beloep.format()
                +" kroner per måned."
            },
            nynorsk {
                +"Du får utbetalt "
                +beloep.format()
                +" kroner per månad."
            },
        )
    }

    showIf(harBarnetillegg) {
        title2 {
            text(
                bokmal { +"Barnetillegg" },
                nynorsk { +"Barnetillegg" },
            )
        }

        includePhrase(BarnetilleggInfo(barnetilleggData))
    }
}
----

== Scope

`outline`-blokken bruker `OutlineScope`. Dette betyr at du kan strukturere innholdet med overskrifter og avsnitt, men ikke legge innhold direkte - alt må være inne i et element.

== Beste praksis

* Bruk `title1` for hovedseksjoner
* Bruk `title2` sparsomt for underseksjoner
* Hold struktur flat - unngå dyp nøsting
* Trekk ut gjenbrukbart innhold i xref:dsl/phrases/index.adoc[fraser]

== Relaterte elementer

* xref:dsl/letter-template/index.adoc[Letter Template] - Malstruktur
* xref:dsl/outline/paragraph.adoc[paragraph] - Avsnitt
* xref:dsl/phrases/index.adoc[Phrases] - Gjenbrukbare fraser

