// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningnokkelinfo.beregningnokkelinfo2.spt

import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningnokkelinfo.beregningnokkelinfo2.spt.poengrekke.Poengrekke

data class Spt(
    val poengrekke: Poengrekke?,
    val poengrekkepopulert: Boolean?,
    val sluttpoengtallutenok: Double?,
    val sluttpoengtallutenokeos: Double?,
    val sluttpoengtallutenoknordisk: Double?
)
