import type {NextPage} from 'next'
import Head from 'next/head'
import {AuthenticatedTemplate, UnauthenticatedTemplate, useMsal} from "@azure/msal-react"
import {useState} from "react"
import styles from '../../styles/Home.module.css'
import SkribentenAPI from "../lib/services/skribenten"
import {SkribentenConfig} from "./_app"


export function SignInButton() {
    const {instance} = useMsal()
    return <button onClick={() => instance.loginRedirect()}>Sign in</button>
}

function WelcomeUser() {
    const {accounts} = useMsal()
    const username = accounts[0].username
    return <p>Welcome, {username}</p>
}

interface PdfFileLinkProps {
    pdfFile?: Blob,
}

const PdfFileLink = ({pdfFile}: PdfFileLinkProps) => {
    if (pdfFile == null) {
        return <span>No file</span>
    } else {
        const url = window.URL.createObjectURL(pdfFile)
        return <a href={url} download="omsorg_egen_auto.pdf">Omsorg Egen Auto</a>
    }
}

const Home: NextPage<SkribentenConfig> = (props) => {
    const msal = useMsal()
    const skribentenAPI = new SkribentenAPI(props.api, msal)

    const [penData, setPenData] = useState("unknown")
    const [brevbakerData, setBrevbakerData] = useState<Blob>()

    return (
        <div className={styles.container}>
            <Head>
                <title>Azure AD Authentication using MSAL and Next.js</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <AuthenticatedTemplate>
                <p>This will only render if a user is signed-in.</p>
                <WelcomeUser/>
                <p>Fetch from pesys: {penData}</p>
                <button onClick={() => skribentenAPI.testPesys().then(setPenData)}>Test Pesys</button>
                <p>Generated brev: <PdfFileLink pdfFile={brevbakerData}/></p>
                <button onClick={() => skribentenAPI.testBrevbaker().then(setBrevbakerData)}>Test brevbaker</button>
            </AuthenticatedTemplate>
            <UnauthenticatedTemplate>
                <p>This will only render if a user is not signed-in.</p>
                <SignInButton/>
            </UnauthenticatedTemplate>
        </div>
    )
}

export default Home
