// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningperiode.beregningytelseskomp.familietillegg

import no.nav.pensjon.brevbaker.api.model.BrevbakerType.Kroner

data class Familietillegg(
    val familietilleggbrutto: Kroner?,
    val familietillegginnvilget: Boolean?,
    val familietilleggnetto: Kroner?
)
