:docinfo: shared
:source-highlighter: highlight.js
:toc:

= Letter Template

En brevmal definerer strukturen og innholdet i et brev.

== Maltyper

=== AutobrevTemplate

Brukes for brev som sendes automatisk uten redigering:

[source,kotlin]
----
@TemplateModelHelpers
object MittAutobrev : AutobrevTemplate<MittBrevDto> {
    override val kode = Pesysbrevkoder.AutoBrev.MITT_BREV
    override val template = createTemplate(...) { ... }
}
----

=== RedigerbarTemplate

Brukes for brev som kan redigeres av saksbehandler:

[source,kotlin]
----
@TemplateModelHelpers
object MittRedigerbareBrev : RedigerbarTemplate<MittBrevDto> {
    override val kode = Pesysbrevkoder.Redigerbar.MITT_BREV
    override val template = createTemplate(...) { ... }
}
----

== createTemplate

`createTemplate` definerer selve brevmalen.

=== Parametere

[cols="2,3,4"]
|===
|Parameter |Type |Beskrivelse

|`name`
|`String`
|Unikt navn for malen (typisk `kode.name`)

|`letterDataType`
|`KClass<T>`
|Data-klassen som definerer informasjonsbehovet

|`languages`
|`LanguageSupport`
|Hvilke språk malen støtter

|`letterMetadata`
|`LetterMetadata`
|Metadata om brevet
|===

=== Eksempel

[source,kotlin]
----
override val template = createTemplate(
    name = kode.name,
    letterDataType = MittBrevDto::class,
    languages = languages(Bokmal, Nynorsk, English),
    letterMetadata = LetterMetadata(
        displayTitle = "Vedtak om uføretrygd",
        distribusjonstype = LetterMetadata.Distribusjonstype.VEDTAK,
        brevtype = LetterMetadata.Brevtype.VEDTAKSBREV,
    )
) {
    title { ... }
    outline { ... }
    includeAttachment(...)
}
----

== LetterMetadata

Metadata som beskriver brevet.

=== Egenskaper

[cols="2,3"]
|===
|Egenskap |Beskrivelse

|`displayTitle`
|Tittel som vises i arkivet

|`distribusjonstype`
|Hvordan varslingen ved distribusjon blir

|`brevtype`
|Type brev (vedtak, informasjon)
|===

=== Distribusjonstype

* `VEDTAK` - Vedtaksbrev
* `VIKTIG` - Viktig informasjon
* `ANNET` - Annen informasjon

=== Brevtype

* `VEDTAKSBREV` - Vedtak med klagerett
* `INFORMASJONSBREV` - Informasjonsbrev

== Template-innhold

Inne i `createTemplate`-blokken definerer du:

* xref:dsl/letter-template/title.adoc[title] - Brevets hovedtittel
* xref:dsl/outline/index.adoc[outline] - Hovedinnholdet
* xref:dsl/attachment/includeAttachment.adoc[includeAttachment] - Vedlegg

[source,kotlin]
----
createTemplate(...) {
    title {
        text(
            bokmal { +"Vedtak om uføretrygd" },
            nynorsk { +"Vedtak om uføretrygd" },
        )
    }

    outline {
        // Hovedinnhold
    }

    includeAttachment(beregningDetaljer, beregningsdata)
}
----

== @TemplateModelHelpers

Annotasjonen genererer selector-extensions for DTO-en, slik at du får direkte tilgang til feltene:

[source,kotlin]
----
@TemplateModelHelpers
object MittBrev : AutobrevTemplate<MittBrevDto> {
    // ...
    override val template = createTemplate(...) {
        outline {
            // Direkte tilgang til DTO-felter
            val grad = uforegrad  // I stedet for letterData.uforegrad
        }
    }
}
----

== languages()

Definerer hvilke språk malen støtter:

[source,kotlin]
----
// Kun bokmål
languages(Bokmal)

// Bokmål og nynorsk
languages(Bokmal, Nynorsk)

// Alle tre språk
languages(Bokmal, Nynorsk, English)
----

Kompilatoren gir feil hvis du mangler oversettelser for definerte språk.

== Relaterte elementer

* xref:dsl/letter-template/title.adoc[title] - Brevets hovedtittel
* xref:dsl/outline/index.adoc[outline] - Hovedinnhold
* xref:dsl/attachment/index.adoc[attachment] - Vedlegg

