schema: pdl.graphql # hentet fra https://github.com/navikt/pdl/blob/master/apps/api/src/main/resources/schemas/pdl.graphqls
extensions:
  endpoints:
    PDL GraphQL Endpoint:
      url: https://pdl-api.dev.intern.nav.no/graphql
      headers:
        user-agent: 'skribenten-backend-lokal'
      introspect: false
