// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag

import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagsliste.Persongrunnlagsliste
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.Persongrunnlagslisteavdod

data class Grunnlag(
    val persongrunnlagsliste: Persongrunnlagsliste?,
    val persongrunnlagslisteavdod: Persongrunnlagslisteavdod?
)
