#######
# Denne er brukt til å gjøre det mulig å bruke tokens lokalt
#
# secret kan hentes fra cluster med samme kommando som i brevbaker/locust/fetch-secrets.sh
#
# Kjøres en gang eller ved endringer med
# kubectl apply -f .deploy/azure-ad-app-lokal.yaml
###
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: locust
  namespace: pensjonsbrev
  labels:
    team: pensjonsbrev
spec:
  secretName: azure-locust
