import { SamhandlerTypeCode, SpraakKode } from "./apiTypes";

export const SPRAAK_ENUM_TO_TEXT = {
  [SpraakKode.Bokmaal]: "Bokmål",
  [SpraakKode.Nynorsk]: "Nynorsk",
  [SpraakKode.Engelsk]: "Engelsk",
};

export const SAMHANDLER_ENUM_TO_TEXT = {
  [SamhandlerTypeCode.AA]: "Ambulansearbeider",
  [SamhandlerTypeCode.ADVO]: "Advokat / Jurist",
  [SamhandlerTypeCode.AFPO]: "AFP-ordning",
  [SamhandlerTypeCode.AK]: "Arbeidskontor",
  [SamhandlerTypeCode.AMI]: "Arbeidsmarkedsinstitutt",
  [SamhandlerTypeCode.AN]: "Ankenemnda for sykepenger",
  [SamhandlerTypeCode.AP]: "Audiopedagog",
  [SamhandlerTypeCode.APOP]: "Apotek - privat",
  [SamhandlerTypeCode.APOS]: "Apotek - sykehus",
  [SamhandlerTypeCode.ART]: "Arbeidstilsynet",
  [SamhandlerTypeCode.ASEN]: "Arbeidslivssenter",
  [SamhandlerTypeCode.AT]: "Apotektekniker",
  [SamhandlerTypeCode.ATU]: "Attfringsutvalg",
  [SamhandlerTypeCode.AU]: "Audiograf",
  [SamhandlerTypeCode.BAND]: "Bandasjist",
  [SamhandlerTypeCode.BB]: "Begravelsesbyr",
  [SamhandlerTypeCode.BBE]: "Bobestyrer",
  [SamhandlerTypeCode.BEH]: "Behandler",
  [SamhandlerTypeCode.BF]: "Bidragsfogden",
  [SamhandlerTypeCode.BH]: "Barnehage",
  [SamhandlerTypeCode.BHT]: "Bedriftshelsetjeneste",
  [SamhandlerTypeCode.BI]: "Bioingenir",
  [SamhandlerTypeCode.BU]: "Bilutvalget",
  [SamhandlerTypeCode.EOS]: "ES-Land",
  [SamhandlerTypeCode.ET]: "Ergoterapeut",
  [SamhandlerTypeCode.FA]: "Farmasyt",
  [SamhandlerTypeCode.FB]: "Fiskehelsebiolog",
  [SamhandlerTypeCode.FFU]: "Folketrygdkontoret for utenlandssaker",
  [SamhandlerTypeCode.FKL]: "Fellesordningen LO/NHO",
  [SamhandlerTypeCode.FL]: "Fylkeslegen",
  [SamhandlerTypeCode.FO]: "Fotterapeut",
  [SamhandlerTypeCode.FS]: "Forsikringsselskap",
  [SamhandlerTypeCode.FT]: "Fysioterapeut",
  [SamhandlerTypeCode.FTK]: "Fylkestrygdekontor",
  [SamhandlerTypeCode.FULL]: "Fullmektig",
  [SamhandlerTypeCode.GVS]: "Grunn- og videregende skole",
  [SamhandlerTypeCode.HE]: "Helsesekretr",
  [SamhandlerTypeCode.HF]: "Helsefagarbeider",
  [SamhandlerTypeCode.HFO]: "Helseforetak",
  [SamhandlerTypeCode.HJS]: "Hjemmesykepleien",
  [SamhandlerTypeCode.HMS]: "Hjelpemiddelsentral",
  [SamhandlerTypeCode.HP]: "Hjelpepleier",
  [SamhandlerTypeCode.HPRD]: "HPR-dummy",
  [SamhandlerTypeCode.HS]: "Helsesster",
  [SamhandlerTypeCode.HSTA]: "Helsestasjon",
  [SamhandlerTypeCode.HSV]: "Hovedstevnevitnet",
  [SamhandlerTypeCode.HTF]: "Helsetjeneste forvaltning",
  [SamhandlerTypeCode.HU]: "Hyskole/universitet",
  [SamhandlerTypeCode.INST]: "Institusjon",
  [SamhandlerTypeCode.IS]: "Innkrevingssentralen",
  [SamhandlerTypeCode.JO]: "Jordmor",
  [SamhandlerTypeCode.KA]: "Klage- og Ankeenhet",
  [SamhandlerTypeCode.KE]: "Klinisk ernringsfysiolog",
  [SamhandlerTypeCode.KEMN]: "Kemner",
  [SamhandlerTypeCode.KI]: "Kiropraktor",
  [SamhandlerTypeCode.KOMM]: "Kommune",
  [SamhandlerTypeCode.KON]: "Konvensjonsland",
  [SamhandlerTypeCode.KRED]: "Kreditor",
  [SamhandlerTypeCode.KRU]: "Klageinstans reiseutgift",
  [SamhandlerTypeCode.KYND]: "Sakkyndig",
  [SamhandlerTypeCode.LABO]: "Laboratorium - offentlig",
  [SamhandlerTypeCode.LABP]: "Laboratorium - privat",
  [SamhandlerTypeCode.LARO]: "Lab/rntgen - privat",
  [SamhandlerTypeCode.LBS]: "Landsdekkende bilsenter",
  [SamhandlerTypeCode.LE]: "Lege",
  [SamhandlerTypeCode.LEBE]: "Bedriftslege",
  [SamhandlerTypeCode.LEFA]: "Fastlege",
  [SamhandlerTypeCode.LEKO]: "Kommunelege",
  [SamhandlerTypeCode.LERA]: "Rdgivende lege",
  [SamhandlerTypeCode.LFK]: "Legemiddel fagkontor",
  [SamhandlerTypeCode.LHK]: "Leverandr helsetrygdkort",
  [SamhandlerTypeCode.LK]: "Ligningskontor",
  [SamhandlerTypeCode.LM]: "Leverandr Motorkjrety",
  [SamhandlerTypeCode.LOGO]: "Logoped",
  [SamhandlerTypeCode.LRB]: "Lsreregister Brnnysund",
  [SamhandlerTypeCode.LS]: "Legesenter",
  [SamhandlerTypeCode.MT]: "Manuellterapeut",
  [SamhandlerTypeCode.NB]: "Namsmannen",
  [SamhandlerTypeCode.OA]: "Omsorgsarbeider",
  [SamhandlerTypeCode.OI]: "Ortopediingenir",
  [SamhandlerTypeCode.OM]: "Ombygger bil",
  [SamhandlerTypeCode.OP]: "Optiker",
  [SamhandlerTypeCode.OR]: "Ortoptist",
  [SamhandlerTypeCode.ORVE]: "Ortopedisk verksted",
  [SamhandlerTypeCode.PE]: "Perfusjonist",
  [SamhandlerTypeCode.PF]: "Provisorfarmasyt",
  [SamhandlerTypeCode.POLI]: "Poliklinikk",
  [SamhandlerTypeCode.PPT]: "Psykologisk pedagogisk tjeneste",
  [SamhandlerTypeCode.PS]: "Psykolog",
  [SamhandlerTypeCode.RA]: "Radiograf",
  [SamhandlerTypeCode.REGO]: "Regional oppgjrsenhet",
  [SamhandlerTypeCode.RF]: "Reseptarfarmasyt",
  [SamhandlerTypeCode.RFK]: "Rogaland fylkestrygdekontor",
  [SamhandlerTypeCode.RHFO]: "Regionalt helseforetak",
  [SamhandlerTypeCode.RKK]: "Regionklagekontor",
  [SamhandlerTypeCode.ROL]: "Rdgivende overlege",
  [SamhandlerTypeCode.RONO]: "Rntgeninstitutt - offentlig",
  [SamhandlerTypeCode.RONP]: "Rntgeninstitutt - privat",
  [SamhandlerTypeCode.RT]: "Rdgivende tannlege",
  [SamhandlerTypeCode.RTK]: "Regionstrygdekontor",
  [SamhandlerTypeCode.RTV]: "Rikstrygdeverket",
  [SamhandlerTypeCode.SAD]: "Samleadressat",
  [SamhandlerTypeCode.SFK]: "Sentralfylkestrygdekontor",
  [SamhandlerTypeCode.SK]: "Sosialkontor",
  [SamhandlerTypeCode.SP]: "Sykepleier",
  [SamhandlerTypeCode.SR]: "Skifteretten",
  [SamhandlerTypeCode.STKO]: "Stttekontakt",
  [SamhandlerTypeCode.SUD]: "Statens utlendingsdirektorat",
  [SamhandlerTypeCode.SYKH]: "Sykehus",
  [SamhandlerTypeCode.TEPE]: "Tjenestepensjonsordningar",
  [SamhandlerTypeCode.TH]: "Tannhelsesekretr",
  [SamhandlerTypeCode.TI]: "Takseringsinstanser",
  [SamhandlerTypeCode.TK]: "Trygdekontor",
  [SamhandlerTypeCode.TL]: "Tannlege",
  [SamhandlerTypeCode.TLO]: "Tannlege offentlig",
  [SamhandlerTypeCode.TOLK]: "Tolk",
  [SamhandlerTypeCode.TP]: "Tannpleier",
  [SamhandlerTypeCode.TR]: "Trygderetten",
  [SamhandlerTypeCode.TRAN]: "Transportr",
  [SamhandlerTypeCode.TT]: "Tanntekniker",
  [SamhandlerTypeCode.UTL]: "Utenlandske samhandler",
  [SamhandlerTypeCode.VE]: "Veterinr",
  [SamhandlerTypeCode.VIRT]: "Virtuelt trygdekontor",
  [SamhandlerTypeCode.VP]: "Vernepleier",
  [SamhandlerTypeCode.X]: "Diverse",
  [SamhandlerTypeCode.YH]: "Yrkeshygieniker",
  [SamhandlerTypeCode.YM]: "Yrkesmedisiner",
};
