import type { AdresseType, SakType } from "./apiTypes";
import { SamhandlerTypeCode, SpraakKode } from "./apiTypes";

export const SPRAAK_ENUM_TO_TEXT = {
  [SpraakKode.Bokmaal]: "Bokmål",
  [SpraakKode.Nynorsk]: "Nynorsk",
  [SpraakKode.Engelsk]: "Engelsk",
  [SpraakKode.Fransk]: "Fransk",
  [SpraakKode.NordSamisk]: "Nordsamisk",
};

export const SAK_TYPE_TO_TEXT: Record<SakType, string> = {
  AFP: "AFP",
  AFP_PRIVAT: "AFP Privat",
  ALDER: "Alderspensjon",
  BARNEP: "Barnepensjon",
  FAM_PL: "Familiepleierytelse",
  GAM_YRK: "Gammel yrkesskade",
  GENRL: "Generell",
  GJENLEV: "Gjenlevendeytelse",
  GRBL: "Grunnblanketter",
  KRIGSP: "Krigspensjon",
  OMSORG: "Omsorgopptjening",
  UFOREP: "Uføretrygd",
};

export const SAMHANDLER_ENUM_TO_TEXT = {
  [SamhandlerTypeCode.AA]: "Ambulansearbeider",
  [SamhandlerTypeCode.ADVO]: "Advokat / Jurist",
  [SamhandlerTypeCode.AFPO]: "AFP-ordning",
  [SamhandlerTypeCode.AK]: "Arbeidskontor",
  [SamhandlerTypeCode.AMI]: "Arbeidsmarkedsinstitutt",
  [SamhandlerTypeCode.AN]: "Ankenemnda for sykepenger",
  [SamhandlerTypeCode.AP]: "Audiopedagog",
  [SamhandlerTypeCode.APOP]: "Apotek - privat",
  [SamhandlerTypeCode.APOS]: "Apotek - sykehus",
  [SamhandlerTypeCode.ART]: "Arbeidstilsynet",
  [SamhandlerTypeCode.ASEN]: "Arbeidslivssenter",
  [SamhandlerTypeCode.AT]: "Apotektekniker",
  [SamhandlerTypeCode.ATU]: "Attføringsutvalg",
  [SamhandlerTypeCode.AU]: "Audiograf",
  [SamhandlerTypeCode.BAND]: "Bandasjist",
  [SamhandlerTypeCode.BB]: "Begravelsesbyrå",
  [SamhandlerTypeCode.BBE]: "Bobestyrer",
  [SamhandlerTypeCode.BEH]: "Behandler",
  [SamhandlerTypeCode.BF]: "Bidragsfogden",
  [SamhandlerTypeCode.BH]: "Barnehage",
  [SamhandlerTypeCode.BHT]: "Bedriftshelsetjeneste",
  [SamhandlerTypeCode.BI]: "Bioingeniør",
  [SamhandlerTypeCode.BU]: "Bilutvalget",
  [SamhandlerTypeCode.EOS]: "EØS-Land",
  [SamhandlerTypeCode.ET]: "Ergoterapeut",
  [SamhandlerTypeCode.FA]: "Farmasøyt",
  [SamhandlerTypeCode.FB]: "Fiskehelsebiolog",
  [SamhandlerTypeCode.FFU]: "Folketrygdkontoret for utenlandssaker",
  [SamhandlerTypeCode.FKL]: "Fellesordningen LO/NHO",
  [SamhandlerTypeCode.FL]: "Fylkeslegen",
  [SamhandlerTypeCode.FO]: "Fotterapeut",
  [SamhandlerTypeCode.FS]: "Forsikringsselskap",
  [SamhandlerTypeCode.FT]: "Fysioterapeut",
  [SamhandlerTypeCode.FTK]: "Fylkestrygdekontor",
  [SamhandlerTypeCode.FULL]: "Fullmektig",
  [SamhandlerTypeCode.GVS]: "Grunn- og videregående skole",
  [SamhandlerTypeCode.HE]: "Helsesekretær",
  [SamhandlerTypeCode.HF]: "Helsefagarbeider",
  [SamhandlerTypeCode.HFO]: "Helseforetak",
  [SamhandlerTypeCode.HJS]: "Hjemmesykepleien",
  [SamhandlerTypeCode.HMS]: "Hjelpemiddelsentral",
  [SamhandlerTypeCode.HP]: "Hjelpepleier",
  [SamhandlerTypeCode.HPRD]: "HPR-dummy",
  [SamhandlerTypeCode.HS]: "Helsesøster",
  [SamhandlerTypeCode.HSTA]: "Helsestasjon",
  [SamhandlerTypeCode.HSV]: "Hovedstevnevitnet",
  [SamhandlerTypeCode.HTF]: "Helsetjeneste forvaltning",
  [SamhandlerTypeCode.HU]: "Høyskole/universitet",
  [SamhandlerTypeCode.INST]: "Institusjon",
  [SamhandlerTypeCode.IS]: "Innkrevingssentralen",
  [SamhandlerTypeCode.JO]: "Jordmor",
  [SamhandlerTypeCode.KA]: "Klage- og Ankeenhet",
  [SamhandlerTypeCode.KE]: "Klinisk ernæringsfysiolog",
  [SamhandlerTypeCode.KEMN]: "Kemner",
  [SamhandlerTypeCode.KI]: "Kiropraktor",
  [SamhandlerTypeCode.KOMM]: "Kommune",
  [SamhandlerTypeCode.KON]: "Konvensjonsland",
  [SamhandlerTypeCode.KRED]: "Kreditor",
  [SamhandlerTypeCode.KRU]: "Klageinstans reiseutgift",
  [SamhandlerTypeCode.KYND]: "Sakkyndig",
  [SamhandlerTypeCode.LABO]: "Laboratorium - offentlig",
  [SamhandlerTypeCode.LABP]: "Laboratorium - privat",
  [SamhandlerTypeCode.LARO]: "Lab/røntgen - privat",
  [SamhandlerTypeCode.LBS]: "Landsdekkende bilsenter",
  [SamhandlerTypeCode.LE]: "Lege",
  [SamhandlerTypeCode.LEBE]: "Bedriftslege",
  [SamhandlerTypeCode.LEFA]: "Fastlege",
  [SamhandlerTypeCode.LEKO]: "Kommunelege",
  [SamhandlerTypeCode.LERA]: "Rådgivende lege",
  [SamhandlerTypeCode.LFK]: "Legemiddel fagkontor",
  [SamhandlerTypeCode.LHK]: "Leverandør helsetrygdkort",
  [SamhandlerTypeCode.LK]: "Ligningskontor",
  [SamhandlerTypeCode.LM]: "Leverandør Motorkjøretøy",
  [SamhandlerTypeCode.LOGO]: "Logoped",
  [SamhandlerTypeCode.LRB]: "Løsøreregister Brønnøysund",
  [SamhandlerTypeCode.LS]: "Legesenter",
  [SamhandlerTypeCode.MT]: "Manuellterapeut",
  [SamhandlerTypeCode.NB]: "Namsmannen",
  [SamhandlerTypeCode.OA]: "Omsorgsarbeider",
  [SamhandlerTypeCode.OI]: "Ortopediingeniør",
  [SamhandlerTypeCode.OM]: "Ombygger bil",
  [SamhandlerTypeCode.OP]: "Optiker",
  [SamhandlerTypeCode.OR]: "Ortoptist",
  [SamhandlerTypeCode.ORVE]: "Ortopedisk verksted",
  [SamhandlerTypeCode.PE]: "Perfusjonist",
  [SamhandlerTypeCode.PF]: "Provisorfarmasøyt",
  [SamhandlerTypeCode.POLI]: "Poliklinikk",
  [SamhandlerTypeCode.PPT]: "Psykologisk pedagogisk tjeneste",
  [SamhandlerTypeCode.PS]: "Psykolog",
  [SamhandlerTypeCode.RA]: "Radiograf",
  [SamhandlerTypeCode.REGO]: "Regional oppgjørsenhet",
  [SamhandlerTypeCode.RF]: "Reseptarfarmasøyt",
  [SamhandlerTypeCode.RFK]: "Rogaland fylkestrygdekontor",
  [SamhandlerTypeCode.RHFO]: "Regionalt helseforetak",
  [SamhandlerTypeCode.RKK]: "Regionklagekontor",
  [SamhandlerTypeCode.ROL]: "Rådgivende overlege",
  [SamhandlerTypeCode.RONO]: "Røntgeninstitutt - offentlig",
  [SamhandlerTypeCode.RONP]: "Røntgeninstitutt - privat",
  [SamhandlerTypeCode.RT]: "Rådgivende tannlege",
  [SamhandlerTypeCode.RTK]: "Regionstrygdekontor",
  [SamhandlerTypeCode.RTV]: "Rikstrygdeverket",
  [SamhandlerTypeCode.SAD]: "Samleadressat",
  [SamhandlerTypeCode.SFK]: "Sentralfylkestrygdekontor",
  [SamhandlerTypeCode.SK]: "Sosialkontor",
  [SamhandlerTypeCode.SP]: "Sykepleier",
  [SamhandlerTypeCode.SR]: "Skifteretten",
  [SamhandlerTypeCode.STKO]: "Støttekontakt",
  [SamhandlerTypeCode.SUD]: "Statens utlendingsdirektorat",
  [SamhandlerTypeCode.SYKH]: "Sykehus",
  [SamhandlerTypeCode.TEPE]: "Tjenestepensjonsordningar",
  [SamhandlerTypeCode.TH]: "Tannhelsesekretær",
  [SamhandlerTypeCode.TI]: "Takseringsinstanser",
  [SamhandlerTypeCode.TK]: "Trygdekontor",
  [SamhandlerTypeCode.TL]: "Tannlege",
  [SamhandlerTypeCode.TLO]: "Tannlege offentlig",
  [SamhandlerTypeCode.TOLK]: "Tolk",
  [SamhandlerTypeCode.TP]: "Tannpleier",
  [SamhandlerTypeCode.TR]: "Trygderetten",
  [SamhandlerTypeCode.TRAN]: "Transportør",
  [SamhandlerTypeCode.TT]: "Tanntekniker",
  [SamhandlerTypeCode.UTL]: "Utenlandske samhandler",
  [SamhandlerTypeCode.VE]: "Veterinær",
  [SamhandlerTypeCode.VIRT]: "Virtuelt trygdekontor",
  [SamhandlerTypeCode.VP]: "Vernepleier",
  [SamhandlerTypeCode.X]: "Diverse",
  [SamhandlerTypeCode.YH]: "Yrkeshygieniker",
  [SamhandlerTypeCode.YM]: "Yrkesmedisiner",
};

export function getAdresseTypeName(adresseType?: AdresseType) {
  if (adresseType?.toLowerCase().includes("verge")) {
    return "Verge";
  }

  return "Bruker";
}
