// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata

import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.Beregning
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningperiode.Beregningperiode
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningsrelasjoner.Beregningsrelasjoner

data class Beregningsdata(
    val beregning: Beregning?,
    val beregningantallperioder: Int?,
    val beregningperiode: List<Beregningperiode>?,
    val beregningsrelasjoner: Beregningsrelasjoner?
)
