@startuml

object "pensjon-brevbaker" as brevbaker
brevbaker : dagens applikasjon

object pensjonsmalene #pink
pensjonsmalene : - her ligger malene og malkodene. \n denne skal bort

object ufoeremalene #pink
ufoeremalene : - her ligger malene og malkodene

object aldersmalene #pink
aldersmalene : - her ligger malene og malkodene

object "etterlattemaler" as etterlatte #pink

object "pensjon-brevbaker-api-model" as pensjonapimodel #pink
pensjonapimodel : denne skal bort

object "alder:api-model" as alderapimodel #pink
alderapimodel : som i dag

object ":ufoere:api-model" as ufoereapimodel #pink
ufoereapimodel : som i dag

object "brevbaker:dsl" as dsl
dsl : - ny modul
dsl : - det som trengs for å lage en mal

object "brevbaker-bibliotek" as bibliotek
bibliotek : skal eksponeres

object Gjenny #yellow

object "brevbaker-model" as modelcommon
modelcommon : - som i dag
modelcommon : - dagens brevbaker-api-model-common

object "brevbaker-selector-generator" as tmg
tmg : dagens template-model-generator

object PEN #yellow

object Skribenten
Skribenten : som i dag

bibliotek --> dsl
brevbaker --> pensjonsmalene
brevbaker --> aldersmalene
brevbaker --> ufoeremalene
brevbaker --> etterlatte
pensjonsmalene --> pensjonapimodel

aldersmalene --> alderapimodel
ufoeremalene --> ufoereapimodel

pensjonsmalene -> bibliotek
etterlatte --> bibliotek
pensjonapimodel --> modelcommon
alderapimodel --> modelcommon
ufoereapimodel --> modelcommon
dsl --> modelcommon
tmg --> dsl
etterlatte ..> tmg
pensjonsmalene ..> tmg
ufoeremalene ..> tmg
bibliotek ..> tmg

PEN --> pensjonapimodel
PEN --> alderapimodel
PEN --> ufoereapimodel
Gjenny --> modelcommon

Skribenten --> modelcommon

@enduml