@startuml

legend top left
  |<#pink><color:#pink>WWWWWWWWWW</color> | publisert artefakt (Maven/GitHub Packages) |
  |<#lightskyblue><color:#lightskyblue>WWWWWWWWWW</color> | våre applikasjoner (kjørende tjenester) |
  |<#yellow><color:#yellow>WWWWWWWWWW</color> | eksternt system |
endlegend

package "brevbaker" {
  package "brevbaker:markup" {
    object "markup (main)" as markup #pink
    markup : - markup-modellen og den publiserte DSLen
    markup : - ingen runtime-avhengigheter
    markup : - hentes av andre moduler som\n  publisert artefakt

    object "markup (apiInternal)" as markupInternal
    markupInternal : - utvidet DSL (letterMarkupExtended,\n  attachmentExtended, markupElement)
    markupInternal : - eget kildesett med friend-tilgang\n  til main (associateWith)
    markupInternal : - publiseres aldri, eksponeres som\n  konfigurasjonen apiInternalElements
  }

  object "brevbaker:api-model-common" as modelcommon #pink
  modelcommon : - felles API-modell mot bestillersystemene

  object "brevbaker:internal" as internal
  internal : - eneste vei inn til markup +\n  api-model-common for modulene i repoet
  internal : - re-eksporterer begge med api(...)
  internal : - Jackson-serialisering av intern trafikk\n  (internalObjectMapper)
  internal : - publiseres aldri

  object "brevbaker:dsl" as dsl
  dsl : - det som trengs for å lage en mal

  object "brevbaker:core" as core
  core : - rendringsmotor, Letter2Markup

  object "brevbaker:template-model-generator" as tmg
  tmg : - KSP: genererer *Selectors\n  fra @TemplateModelHelpers

  object "brevbaker:pdf-bygger" as pdfbygger #lightskyblue
  pdfbygger : - egen tjeneste
  pdfbygger : - kompilerer Typst til PDF
}

package "maler" {
  object "pensjon:maler" as pensjonsmalene
  object "alder:maler" as aldersmalene
  object "ufoere:maler" as ufoeremalene
  object "etterlattemaler" as etterlatte
  object "planlegge-pensjon-maler" as planlegge
}

package "api-model" {
  object "pensjon:api-model" as pensjonapimodel #pink
  object "alder:api-model" as alderapimodel #pink
  object "ufoere:api-model" as ufoereapimodel #pink
}

object "pensjon:brevbaker" as brevbakerApp #lightskyblue
brevbakerApp : - applikasjonen som samler alle malene\n  og eksponerer dem via API

object "skribenten-backend" as skribenten #lightskyblue
object PEN #yellow
object Gjenny #yellow

' brevbaker-modulene
internal --> markupInternal : prosjektavhengighet\n(apiInternalElements)
markupInternal ..> markup : friend / associateWith
internal --> modelcommon
dsl --> internal
core --> dsl
tmg --> dsl
pdfbygger --> internal

' malmoduler
pensjonsmalene --> core
aldersmalene --> core
ufoeremalene --> core
etterlatte --> core
planlegge --> core

pensjonsmalene --> pensjonapimodel
aldersmalene --> alderapimodel
ufoeremalene --> ufoereapimodel

pensjonapimodel --> modelcommon
alderapimodel --> modelcommon
ufoereapimodel --> modelcommon

' applikasjonen
brevbakerApp --> pensjonsmalene
brevbakerApp --> aldersmalene
brevbakerApp --> ufoeremalene
brevbakerApp --> etterlatte
brevbakerApp --> planlegge
brevbakerApp ..> pdfbygger : HTTP

' konsumenter
skribenten --> internal
skribenten ..> brevbakerApp : HTTP
PEN --> pensjonapimodel
PEN --> alderapimodel
PEN --> ufoereapimodel
Gjenny --> modelcommon

@enduml
