== Oktober 2025

=== Nye ting vi har laget
* Tastatursnarveier for kopier og lim inn (ctrl+c og ctrl+v)
* Viser kun tekstvalg i venstremenyen som er relevante for valgt mal og sakskontekst
* P1 automatisk utfylling av data basert på alle P6000 SED'er som er valgt inn i P7000 i EESSI-pensjon og data fra Pesys
* Ved endring av mottaker kan man nå markere at brevet skal til en annen mottaker enn bruker
* Mulighet til å sette markøren inn i fritekstfelt ved behov

=== Ting vi har forbedret
* Redigering av titler i brev. Nå kan tittelen til brev også redigeres i Skribenten
* Rolle vises ikke lenger i signatur. Dette er endret slik at vi følger brevstandard
* Håndtering av utenlandske adresser ved manuell endring av mottaker
* Saksbehandler kan nå selv sette vedtaksbrev tilbake til status "kladd" fra "Klar til attestering"

=== Ting vi har fikset
* Avsnitt om etterbetaling er nå et valg i venstremenyen slik som før. Det kom stadig tilfeller der avsnittet var uønsket og vi har derfor gjemt det bak et tekstvalg for å unngå problemer. Det kan nå velges inn ved behov
* Fikset slik at attestant får litt bedre respons når de sletter en kladd fra skjermbildet "Brevbehandler". Tidligere skjedde det ingenting når man trykket slett brev
* Henter nå ny PDF selv når dokumentdato er ulik dagens dato
* Viser kun relevante hurtigtaster for overskrifter
* Vise slett knappen hvis vi ikke klarer å hente PDF slik at kladden kan slettes ved behov

=== Ting vi jobber med
Ingenting spesielt å nevne her denne måneden

=== Kjente problemer og behov vi tenker på
* Ikke mulig å slette kladder med ett trykk fra dokumentoversikten
* Legge ved skjema for innhenting av opplysninger som vedlegg til brev ved behov
* Datakvaliteten til brevet P1 med forsidebrev er svak. Krever høyst sannsynlig redigering av noen felt
