== November 2025

=== Nye ting vi har laget
* Validering av adresser, postnummer og poststed når man legger til adresse manuelt
* Personlinjen inneholder nå mer informasjon om bruker når vi har den informasjonen. Inkludert vergemål, skjerming o.l.

=== Ting vi har forbedret
* Oppdatering av data fra Pesys ved flere tilfeller for å sikre at siste endringer er med. Henter også ny PDF i forhåndsvisning når data er oppdatert, og vi gir beskjed i Skribenten hvis dette skjer
* Forbedret tekstmarkering
* Forbedret feilhåndtering og feilmeldinger slik at de gir mer informasjon
* Bedre søk i Brevvelger. Det trenger ikke lenger være fullstendig match med tekst i tittel på brev. Søk på kategori slik som "Skribenten" fungerer også

=== Ting vi har fikset
* P1 gjort om til informasjonsbrev, og dermed tilgjengelig fra brukeroversikten i Pesys også
* Rettet flere utfordringer med datakvalitet i P1 ved automatisk utfylling
* Fjernet lenke til Teams i "Meld feil" meldingen da denne lenken ikke fungerte for alle brukere
* Man kunne ikke redigere fritekstfelt hvis man brukte hurtigtasten "tab" for å tabbe seg til neste felt

=== Ting vi jobber med
* Redigering av P1. Vi jobber med å få ut redigering av P1 slik at saksbehandler kan justere data fra utland som er manglende eller feil før utsendelse
* Legge til vedlegg for innhenting av opplysninger ved behov
* Tekstmarkering forsvinner etter at man legger på formatering

=== Kjente problemer
* Autolagring kan i enkelte tilfeller henge seg litt opp hvis fanen har vært åpen lenge. Løses ofte ved gå ut og inn av redigering
