import type { P1RedigerbarForm } from "~/types/p1FormTypes";

export const filledP1: P1RedigerbarForm = {
  innehaver: {
    fornavn: "Ola",
    etternavn: "Nordmann",
    etternavnVedFoedsel: "Hansen",
    foedselsdato: "1955-03-15",
    adresselinje: "Storgata 123",
    poststed: "Oslo",
    postnummer: "0182",
    landkode: "NO",
  },
  forsikrede: {
    fornavn: "Kari",
    etternavn: "Nordmann",
    etternavnVedFoedsel: "Olsen",
    foedselsdato: "1960-07-22",
    adresselinje: "Lillegata 45",
    poststed: "Bergen",
    postnummer: "5003",
    landkode: "NO",
  },
  sakstype: "ALDER",

  innvilgedePensjoner: [
    {
      institusjon: {
        institusjonsnavn: "NAV Pensjon",
        pin: "12345678901",
        saksnummer: "SAK-2024-001",
        vedtaksdato: "2024-01-15",
        land: "NO",
      },
      pensjonstype: "Alder",
      datoFoersteUtbetaling: "2024-02-01",
      utbetalt: "15 000 NOK månedlig",
      grunnlagInnvilget: "IHenholdTilNasjonalLovgivning",
      reduksjonsgrunnlag: null,
      vurderingsperiode: "01.01.2024 - 31.12.2024",
      adresseNyVurdering: "NAV Klageinstans, Postboks 123, 0001 Oslo",
    },
    {
      institusjon: {
        institusjonsnavn: "Deutsche Rentenversicherung",
        pin: "DE-987654321",
        saksnummer: "DRV-2024-555",
        vedtaksdato: "2024-02-20",
        land: "DE",
      },
      pensjonstype: "Alder",
      datoFoersteUtbetaling: "2024-03-01",
      utbetalt: "800 EUR månedlig",
      grunnlagInnvilget: "ProRata",
      reduksjonsgrunnlag: "PaaGrunnAvOverlappendeGodskrevnePerioder",
      vurderingsperiode: "01.03.2024 - 28.02.2025",
      adresseNyVurdering: "DRV Berlin, Postfach 456, 10115 Berlin, Germany",
    },
    {
      institusjon: {
        institusjonsnavn: "Försäkringskassan",
        pin: "SE-123456789",
        saksnummer: "FK-2024-789",
        vedtaksdato: "2024-03-10",
        land: "SE",
      },
      pensjonstype: "Ufoere",
      datoFoersteUtbetaling: "2024-04-01",
      utbetalt: "12 000 SEK månedlig",
      grunnlagInnvilget: "MindreEnnEttAar",
      reduksjonsgrunnlag: "PaaGrunnAvAndreYtelserEllerAnnenInntekt",
      vurderingsperiode: "01.04.2024 - 31.03.2025",
      adresseNyVurdering: "Försäkringskassan, Box 100, 103 51 Stockholm, Sweden",
    },
    {
      institusjon: {
        institusjonsnavn: "INPS Italia",
        pin: "IT-555666777",
        saksnummer: "INPS-2024-333",
        vedtaksdato: "2024-04-05",
        land: "IT",
      },
      pensjonstype: "Etterlatte",
      datoFoersteUtbetaling: "2024-05-01",
      utbetalt: "600 EUR månedlig",
      grunnlagInnvilget: "IHenholdTilNasjonalLovgivning",
      reduksjonsgrunnlag: null,
      vurderingsperiode: "01.05.2024 - 30.04.2025",
      adresseNyVurdering: "INPS, Via Ciro il Grande 21, 00144 Roma, Italy",
    },
    {
      institusjon: {
        institusjonsnavn: "",
        pin: "",
        saksnummer: "",
        vedtaksdato: "",
        land: "",
      },
      pensjonstype: null,
      datoFoersteUtbetaling: "",
      utbetalt: "",
      grunnlagInnvilget: null,
      reduksjonsgrunnlag: null,
      vurderingsperiode: "",
      adresseNyVurdering: "",
    },
  ],

  avslaattePensjoner: [
    {
      institusjon: {
        institusjonsnavn: "Kela Finland",
        pin: "FI-111222333",
        saksnummer: "KELA-2024-101",
        vedtaksdato: "2024-01-20",
        land: "FI",
      },
      pensjonstype: "Alder",
      avslagsbegrunnelse: "IngenOpptjeningsperioder",
      vurderingsperiode: "01.02.2024 - 31.01.2025",
      adresseNyVurdering: "Kela, PL 450, 00056 Helsinki, Finland",
    },
    {
      institusjon: {
        institusjonsnavn: "Social Security Administration",
        pin: "US-999888777",
        saksnummer: "SSA-2024-202",
        vedtaksdato: "2024-02-15",
        land: "US",
      },
      pensjonstype: "Ufoere",
      avslagsbegrunnelse: "KravTilKvalifiseringsperiodeEllerAndreKvalifiseringskravErIkkeOppfylt",
      vurderingsperiode: "01.03.2024 - 28.02.2025",
      adresseNyVurdering: "SSA, 6401 Security Blvd, Baltimore, MD 21235, USA",
    },
    {
      institusjon: {
        institusjonsnavn: "CNAV France",
        pin: "FR-444555666",
        saksnummer: "CNAV-2024-303",
        vedtaksdato: "2024-03-25",
        land: "FR",
      },
      pensjonstype: "Etterlatte",
      avslagsbegrunnelse: "InntektstakErOverskredet",
      vurderingsperiode: "01.04.2024 - 31.03.2025",
      adresseNyVurdering: "CNAV, 110 avenue de Flandre, 75019 Paris, France",
    },
    {
      institusjon: {
        institusjonsnavn: "",
        pin: "",
        saksnummer: "",
        vedtaksdato: "",
        land: "",
      },
      pensjonstype: null,
      avslagsbegrunnelse: null,
      vurderingsperiode: "",
      adresseNyVurdering: "",
    },
    {
      institusjon: {
        institusjonsnavn: "",
        pin: "",
        saksnummer: "",
        vedtaksdato: "",
        land: "",
      },
      pensjonstype: null,
      avslagsbegrunnelse: null,
      vurderingsperiode: "",
      adresseNyVurdering: "",
    },
  ],

  utfyllendeInstitusjon: {
    navn: "NAV Internasjonalt",
    adresselinje: "Postboks 6600 Etterstad",
    poststed: "Oslo",
    postnummer: "0607",
    landkode: "NO",
    institusjonsID: "NAV-INT-001",
    faksnummer: "+47 21 07 17 00",
    telefonnummer: "+47 21 07 37 00",
    epost: "nav.internasjonalt@nav.no",
    dato: "2024-12-02",
  },
};
