package no.nav.pensjon.brev.api.model.vedlegg

import no.nav.pensjon.brev.api.model.BorMedSivilstand
import no.nav.pensjon.brev.api.model.Sivilstand
import no.nav.pensjon.brevbaker.api.model.Kroner
import java.time.LocalDate

@Suppress("unused")
data class OpplysningerBruktIBeregningenLegacyDto(
    val tabellUfoereOpplysninger: TabellufoereOpplysningerDto,
    val opplysningerOmMinstetillegg: OpplysningerOmMinstetilleggDto?,
    val opplysningerOmBarnetillegg: OpplysningerOmBarnetilleggDto?,

    // Tittel
    val inntektsgrenseAar: Kroner,
    val inntektstak: Kroner,
    val beregnetUTPerMaanedGjeldendeVirkFom: LocalDate,
    val beregnetUTPerMaanedGjeldendeGrunnbeloep: Kroner,

    // Legacy format data:
    val FF01_webadresse_grunnbelop: String,
    val PE_BarnetilleggFelles_JusteringsbelopPerArUtenMinus: Kroner,
    val PE_BarnetilleggSerkull_JusteringsbelopPerArUtenMinus: Kroner,
    val PE_Grunnlag_PersongrunnlagAvdod_BrukerFlyktning: Boolean,
    val PE_Grunnlag_PersongrunnlagAvdod_Fodselsnummer: String,
    val PE_Grunnlag_PersongrunnlagAvdod_TrygdetidsgrunnlagEOS_TrygdetidEOSLand: String,
    val PE_Grunnlag_PersongrunnlagAvdod_TrygdetidsgrunnlagEOS_TrygdetidFomEOS: LocalDate,
    val PE_Grunnlag_PersongrunnlagAvdod_TrygdetidsgrunnlagEOS_TrygdetidTomEOS: LocalDate,
    val PE_Grunnlag_PersongrunnlagAvdod_TrygdetidsgrunnlagListeBilateral_TrygdetidsgrunnlagBilateral_TrygdetidBilateralLand: String,
    val PE_Grunnlag_PersongrunnlagAvdod_TrygdetidsgrunnlagListeBilateral_TrygdetidsgrunnlagBilateral_TrygdetidFomBilateral: LocalDate,
    val PE_Grunnlag_PersongrunnlagAvdod_TrygdetidsgrunnlagListeBilateral_TrygdetidsgrunnlagBilateral_TrygdetidTomBilateral: LocalDate,
    val PE_Grunnlag_PersongrunnlagAvdod_TrygdetidsgrunnlagListeNor_Trygdetidsgrunnlag_TrygdetidFom: LocalDate,
    val PE_Grunnlag_PersongrunnlagAvdod_TrygdetidsgrunnlagListeNor_Trygdetidsgrunnlag_TrygdetidTom: LocalDate,
    val PE_Grunnlag_Persongrunnlagsliste_BrukerFlyktning: Boolean,
    val PE_Grunnlag_Persongrunnlagsliste_PersonBostedsland: String,
    val PE_Grunnlag_Persongrunnlagsliste_Trygdeavtaler_Avtaleland: String,
    val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeBilateral_TrygdetidsgrunnlagBilateral_TrygdetidBilateralLand: String,
    val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeBilateral_TrygdetidsgrunnlagBilateral_TrygdetidFomBilateral: LocalDate,
    val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeBilateral_TrygdetidsgrunnlagBilateral_TrygdetidTomBilateral: LocalDate,
    val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeEOS_TrygdetidsgrunnlagEOS_TrygdetidEOSLand: String,
    val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeEOS_TrygdetidsgrunnlagEOS_TrygdetidFomEOS: LocalDate,
    val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeEOS_TrygdetidsgrunnlagEOS_TrygdetidTomEOS: LocalDate,
    val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeNor_Trygdetidsgrunnlag_TrygdetidFom: LocalDate?,
    val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeNor_Trygdetidsgrunnlag_TrygdetidTom: LocalDate,
    val PE_SivilstandAnvendt_bormed_1Bindestrek5: String,
    val PE_SivilstandAnvendt_bormed_3_2: String,
    val PE_SivilstandAnvendt_bormed_ektefelle: String,
    val PE_SivilstandAnvendt_bormed_registrert_partner: String,
    val PE_SivilstandAnvendt_gift_men_lever_adskilt: String,
    val PE_SivilstandAnvendt_registrert_partner_men_lever_adskilt: String,
    val PE_Sivilstand_Ektefelle_Partner_Samboer_Bormed_UT: String,
    val PE_Sivilstand_Ektefelle_Partner_Samboer_Bormed_UT_EN: String,
    val PE_Sivilstand_Ektefelle_Partner_Samboer_Bormed_UT_EN_cohabiting_partner: String,
    val PE_Sivilstand_Ektefelle_Partner_Samboer_Bormed_UT_NN_entall: String,
    val PE_UT_AntallBarnSerkullogFelles: Int,
    val PE_UT_BTFBInntektBruktiAvkortningMinusBTFBfribelop: Double,
    val PE_UT_BTSBinntektBruktiAvkortningMinusBTSBfribelop: Double,
    val PE_UT_Barnet_Barna_Felles: String,
    val PE_UT_Barnet_Barna_Innvilget: String,
    val PE_UT_Barnet_Barna_Serkull: String,
    val PE_UT_Inntektsgrense_faktisk: Double,
    val PE_UT_Kompensasjonsgrad_EN: Double,
    val PE_UT_Minsteytelse_Sats_EN: Double,
    val PE_UT_NettoAkk_pluss_NettoRestAr: Kroner,
    val PE_UT_NettoAkk_pluss_NettoRestAr_pluss_ForventetInntekt: Double,
    val PE_UT_OpplyningerOmBergeningen_NettoPerAr: Double,
    val PE_UT_Overskytende: Double,
    val PE_UT_SUM_FaTTNorge_FramtidigTTNorge_DIV_12: Int,
    val PE_UT_SUM_FaTTNorge_FramtidigTTNorge_DIV_12_avdod: Int,
    val PE_UT_VilkarGjelderPersonAlder: Int,
    val PE_UT_VilkarGjelderPerson_fodselsdato: LocalDate,
    val PE_UT_fattNorgePlusfattEOS_Avdod: Int,
    val PE_UT_fattnorgePlusfatta10netto_Avdod: Int,
    val PE_UT_fattnorgePlusfattbilateral_Avdod: Int,
    val PE_UT_sum_FaTTNorge_FaTTBilateral: Int,
    val PE_UT_sum_FaTTNorge_FaTTEOS: Int,
    val PE_UT_sum_FaTTNorge_FaTT_A10_netto: Int,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggFelles_AvkortningsInformasjon_AvkortingsbelopPerAr: Kroner,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggFelles_AvkortningsInformasjon_FribelopPeriodisert: Boolean,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggFelles_AvkortningsInformasjon_InntektPeriodisert: Boolean,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggFelles_AvkortningsInformasjon_Inntektstak: Double,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggFelles_AvkortningsInformasjon_JusteringsbelopPerAr: Kroner,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggFelles_AvkortningsInformasjon_JusteringsbelopPerAr_UtenMinus: Double,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggFelles_BTFBbelopFratrukketAnnenForeldersInntekt: Kroner,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggFelles_BTFBinntektAnnenForelder: Double,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggSerkull_AvkortningsInformasjon_AvkortingsbelopPerAr: Double,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggSerkull_AvkortningsInformasjon_FribelopPeriodisert: Boolean,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggSerkull_AvkortningsInformasjon_InntektPeriodisert: Boolean,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggSerkull_AvkortningsInformasjon_Inntektstak: Double,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggSerkull_AvkortningsInformasjon_JusteringsbelopPerAr: Kroner,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggSerkull_AvkortningsInformasjon_JusteringsbelopPerAr_UtenMinus: Double,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_Reduksjonsgrunnlag_BarnetilleggRegelverkType: String,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_Reduksjonsgrunnlag_GradertOppjustertIFU: Double,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_Reduksjonsgrunnlag_ProsentsatsOIFUForTak: Double,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_Reduksjonsgrunnlag_SumBruttoEtterReduksjonBT: Double,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_Reduksjonsgrunnlag_SumBruttoForReduksjonBT: Kroner,
    val PE_Vedtaksbrev_Vedtaksdata_BeregningsData_BeregningUfore_Reduksjonsgrunnlag_TotaltAntallBarn: Int,
    val PE_Vedtaksbrev_Vedtaksdata_Kravhode_BrukerKonvertertUP: Boolean,
    val PE_Vedtaksbrev_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_Vilkar_FortsattMedlemskap_InngangUnntak: String,
    val PE_Vedtaksbrev_Vedtaksdata_VilkarsVedtak_Vilkar_MedlemskapForUTEtterTrygdeavtaler_OppfyltVedSammenlegging: Boolean,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BelopRedusert: Boolean,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_Belopsendring_UforetrygdOrdinerYK_BelopGammelUT: Kroner,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_Belopsendring_UforetrygdOrdinerYK_BelopNyUT: Kroner,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningVirkningDatoFom: LocalDate,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggFelles_BTFBBrukersInntektTilAvkortning: Kroner,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggFelles_BTFBbruttoPerAr: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggFelles_BTFBnettoPerAr: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggSerkull_BTSBbruttoPerAr: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_BarnetilleggSerkull_BTSBnettoPerAr: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_Gjenlevendetillegg_GTinnvilget: Boolean,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_Gjenlevendetillegg_GjenlevendetilleggInformasjon_AnvendtTrygdetid: Int,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_Gjenlevendetillegg_GjenlevendetilleggInformasjon_BeregningsgrunnlagAvdodOrdiner_Arsbelop: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_Gjenlevendetillegg_GjenlevendetilleggInformasjon_BeregningsgrunnlagAvdodOrdiner_OpptjeningUTListe_OpptjeningUT_Ar: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_Gjenlevendetillegg_GjenlevendetilleggInformasjon_BeregningsgrunnlagAvdodOrdiner_OpptjeningUTListe_OpptjeningUT_AvkortetBelop: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_Gjenlevendetillegg_GjenlevendetilleggInformasjon_BeregningsgrunnlagAvdodOrdiner_OpptjeningUTListe_OpptjeningUT_Brukt: Boolean,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_Gjenlevendetillegg_GjenlevendetilleggInformasjon_BeregningsgrunnlagAvdodOrdiner_OpptjeningUTListe_OpptjeningUT_Forstegansgstjeneste: Boolean,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_Gjenlevendetillegg_GjenlevendetilleggInformasjon_BeregningsgrunnlagAvdodOrdiner_OpptjeningUTListe_OpptjeningUT_InntektIAvtaleLand: Boolean,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_Gjenlevendetillegg_GjenlevendetilleggInformasjon_BeregningsgrunnlagAvdodOrdiner_OpptjeningUTListe_OpptjeningUT_JustertBelop: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_Gjenlevendetillegg_GjenlevendetilleggInformasjon_BeregningsgrunnlagAvdodOrdiner_OpptjeningUTListe_OpptjeningUT_Omsorgsaar: Boolean,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_Gjenlevendetillegg_GjenlevendetilleggInformasjon_BeregningsgrunnlagAvdodOrdiner_OpptjeningUTListe_OpptjeningUT_Pgi: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_Gjenlevendetillegg_GjenlevendetilleggInformasjon_BeregningsgrunnlagAvdodYrkesskadeArsbelop: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_Gjenlevendetillegg_GjenlevendetilleggInformasjon_InntektVedSkadetidspunktet: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_Gjenlevendetillegg_GjenlevendetilleggInformasjon_MinsteYtelseBenyttetUngUfor: Boolean,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_Gjenlevendetillegg_GjenlevendetilleggInformasjon_Uforetidspunkt: LocalDate,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_Gjenlevendetillegg_GjenlevendetilleggInformasjon_Yrkesskadegrad: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_Gjenlevendetillegg_NyttGjenlevendetillegg: Kroner,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_AvkortningsInformasjon_Belopsgrense: Kroner,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_AvkortningsInformasjon_ForventetInntekt: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_AvkortningsInformasjon_Inntektsgrense: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_AvkortningsInformasjon_Inntektstak: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_AvkortningsInformasjon_Kompensasjonsgrad: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_AvkortningsInformasjon_Oifu: Kroner,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_AvkortningsInformasjon_UgradertBruttoPerAr: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_AvkortningsInformasjon_Utbetalingsgrad: Int,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_Fradrag: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_Minsteytelse_OppfyltUngUfor: Boolean,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_Minsteytelse_Sats: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_NettoAkk: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_NettoRestAr: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_Ytelsesgrunnlag_BeregningsgrunnlagOrdinar_AntallArInntektIAvtaleland: Int,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_Ytelsesgrunnlag_BeregningsgrunnlagOrdinar_AntallArOver1G: Int,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_Ytelsesgrunnlag_BeregningsgrunnlagOrdinar_BeregningsgrunnlagOrdinerArsbelop: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_Ytelsesgrunnlag_BeregningsgrunnlagOrdinar_OpptjeningUTListe_OpptjeningUT_Ar: Int,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_Ytelsesgrunnlag_BeregningsgrunnlagOrdinar_OpptjeningUTListe_OpptjeningUT_AvkortetBelop: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_Ytelsesgrunnlag_BeregningsgrunnlagOrdinar_OpptjeningUTListe_OpptjeningUT_Brukt: Boolean,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_Ytelsesgrunnlag_BeregningsgrunnlagOrdinar_OpptjeningUTListe_OpptjeningUT_Forstegansgstjeneste: Boolean,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_Ytelsesgrunnlag_BeregningsgrunnlagOrdinar_OpptjeningUTListe_OpptjeningUT_InntektIAvtaleLand: Boolean,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_Ytelsesgrunnlag_BeregningsgrunnlagOrdinar_OpptjeningUTListe_OpptjeningUT_JustertBelop: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_Ytelsesgrunnlag_BeregningsgrunnlagOrdinar_OpptjeningUTListe_OpptjeningUT_Omsorgsaar: Boolean,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_Ytelsesgrunnlag_BeregningsgrunnlagOrdinar_OpptjeningUTListe_OpptjeningUT_Pgi: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_Ytelsesgrunnlag_BeregningsgrunnlagYrkesskadeArsbelop: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_BeregningYtelsesKomp_UforetrygdOrdiner_Ytelsesgrunnlag_InntektVedSkadetidspunktet: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_Reduksjonsgrunnlag_AndelYtelseAvOIFU: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_TotalNetto: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_Uforetrygdberegning_AnvendtTrygdetid: Int,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_Uforetrygdberegning_BeregningsMetode: String,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_Uforetrygdberegning_Grunnbelop: Double,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_Uforetrygdberegning_Mottarminsteytelse: Boolean,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_Uforetrygdberegning_ProratabrokNevner: Int,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_Uforetrygdberegning_ProratabrokTeller: Int,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_Uforetrygdberegning_Uforegrad: Int,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_Uforetrygdberegning_Uforetidspunkt: LocalDate,
    val PE_Vedtaksdata_BeregningsData_BeregningUfore_Uforetrygdberegning_Yrkesskadegrad: Int,
    val PE_Vedtaksdata_BeregningsData_Beregning_BeregningBrukerSivilstand: String,
    val PE_Vedtaksdata_BeregningsData_Beregning_BeregningSivilstandAnvendt: String,
    val PE_Vedtaksdata_BeregningsData_Beregning_BeregningYtelseKomp_BarnetilleggFelles_AntallBarnFelles: Int,
    val PE_Vedtaksdata_BeregningsData_Beregning_BeregningYtelseKomp_BarnetilleggFelles_BTFBInntektBruktiAvkortning: Kroner,
    val PE_Vedtaksdata_BeregningsData_Beregning_BeregningYtelseKomp_BarnetilleggFelles_BTFBfribelop: Kroner,
    val PE_Vedtaksdata_BeregningsData_Beregning_BeregningYtelseKomp_BarnetilleggFelles_BTFBinnvilget: Boolean,
    val PE_Vedtaksdata_BeregningsData_Beregning_BeregningYtelseKomp_BarnetilleggFelles_BTFBnetto: Kroner,
    val PE_Vedtaksdata_BeregningsData_Beregning_BeregningYtelseKomp_BarnetilleggSerkull_AntallBarnSerkull: Int,
    val PE_Vedtaksdata_BeregningsData_Beregning_BeregningYtelseKomp_BarnetilleggSerkull_BTSBInntektBruktiAvkortning: Double,
    val PE_Vedtaksdata_BeregningsData_Beregning_BeregningYtelseKomp_BarnetilleggSerkull_BTSBfribelop: Kroner,
    val PE_Vedtaksdata_BeregningsData_Beregning_BeregningYtelseKomp_BarnetilleggSerkull_BTSBinnvilget: Boolean,
    val PE_Vedtaksdata_BeregningsData_Beregning_BeregningYtelseKomp_BarnetilleggSerkull_BTSBnetto: Kroner,
    val PE_Vedtaksdata_BeregningsData_Beregning_BeregningYtelseKomp_Ektefelletillegg_ETinnvilget: Boolean,
    val PE_Vedtaksdata_Kravhode_BoddArbeidUtlandAvdod: Boolean,
    val PE_Vedtaksdata_Kravhode_BoddArbeidUtland: Boolean,
    val PE_Vedtaksdata_Kravhode_KravArsakType: String,
    val PE_Vedtaksdata_Kravhode_KravGjelder: String,
    val PE_Vedtaksdata_Kravhode_VurdereTrygdeavtale: Boolean,
    val PE_Vedtaksdata_TrygdetidAvdod_FaTTEOS: Double,
    val PE_Vedtaksdata_TrygdetidAvdod_FaTTNorge: Double,
    val PE_Vedtaksdata_TrygdetidAvdod_FaTT_A10_netto: Double,
    val PE_Vedtaksdata_TrygdetidAvdod_FramtidigTTEOS: Double,
    val PE_Vedtaksdata_TrygdetidAvdod_FramtidigTTNorsk: Double,
    val PE_Vedtaksdata_TrygdetidAvdod_TTNevnerEOS: Double,
    val PE_Vedtaksdata_TrygdetidAvdod_TTNevnerNordisk: Double,
    val PE_Vedtaksdata_TrygdetidAvdod_TTNordisk: Double,
    val PE_Vedtaksdata_TrygdetidAvdod_TTTellerEOS: Double,
    val PE_Vedtaksdata_TrygdetidAvdod_TTTellerNordisk: Double,
    val PE_Vedtaksdata_TrygdetidAvdod_TTUtlandTrygdeAvtale_FaTTBilateral: Double,
    val PE_Vedtaksdata_TrygdetidAvdod_TTUtlandTrygdeAvtale_FramtidigTTAvtaleland: Double,
    val PE_Vedtaksdata_TrygdetidAvdod_TTUtlandTrygdeAvtale_TTNevnerBilateral: Double,
    val PE_Vedtaksdata_TrygdetidAvdod_TTUtlandTrygdeAvtale_TTTellerBilateral: Double,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_BeregningsVilkar_IEUBegrunnelse: String,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_BeregningsVilkar_IEUInntekt: Kroner,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_BeregningsVilkar_IFUBegrunnelse: String,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_BeregningsVilkar_IFUInntekt: Kroner,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_BeregningsVilkar_Skadetidspunkt: LocalDate,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_BeregningsVilkar_TTUtlandTrygdeAvtaleListe_TTUtlandTrygdeAvtale_FaTTBilateral: Int,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_BeregningsVilkar_Trygdetid_FaTTEOS: Int,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_BeregningsVilkar_Trygdetid_FaTTNorge: Int,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_BeregningsVilkar_Trygdetid_FramtidigTTEOS: Int,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_BeregningsVilkar_Trygdetid_FramtidigTTNorsk: Int,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_BeregningsVilkar_Trygdetid_RedusertFramtidigTrygdetid: Boolean,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_BeregningsVilkar_Trygdetid_TTNevnerEOS: Int,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_BeregningsVilkar_Trygdetid_TTNevnerNordisk: Int,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_BeregningsVilkar_Trygdetid_TTNordisk: Int,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_BeregningsVilkar_Trygdetid_TTTellerEOS: Int,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_BeregningsVilkar_Trygdetid_TTTellerNordisk: Int,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_BeregningsVilkar_Uforegrad: Double,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_Vilkar_UngUforResultat: String,
    val PE_Vedtaksdata_VilkarsVedtakList_VilkarsVedtak_Vilkar_YrkesskadeResultat: String,
    val PE_pebrevkode: String,

    // strengt nødvendige ekstra variabler for legacy:
    val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeNor: List<TrygdetidNor>,
    val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeEOS: List<TrygdetidEOS>,
    val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeBilateral: List<TrygdetidBilateral>,
){

    data class TrygdetidNor(
        val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeNor_Trygdetidsgrunnlag_TrygdetidFom: LocalDate,
        val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeNor_Trygdetidsgrunnlag_TrygdetidTom: LocalDate?,
    )

    data class TrygdetidEOS(
        val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeEOS_TrygdetidsgrunnlagEOS_TrygdetidEOSLand: String ,
        val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeEOS_TrygdetidsgrunnlagEOS_TrygdetidFomEOS: LocalDate,
        val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeEOS_TrygdetidsgrunnlagEOS_TrygdetidTomEOS: LocalDate?,
    )

    data class TrygdetidBilateral(
        val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeBilateral_TrygdetidsgrunnlagBilateral_TrygdetidBilateralLand: String ,
        val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeBilateral_TrygdetidsgrunnlagBilateral_TrygdetidFomBilateral: LocalDate,
        val PE_Grunnlag_Persongrunnlagsliste_TrygdetidsgrunnlagListeBilateral_TrygdetidsgrunnlagBilateral_TrygdetidTomBilateral: LocalDate?,
    )

    data class TabellufoereOpplysningerDto(
        val ufoeretrygdGjeldende: OpplysningerBruktIBeregningUTDto.UfoeretrygdGjeldende,
        val yrkesskadeGjeldende: OpplysningerBruktIBeregningUTDto.YrkesskadeGjeldende?,
        val inntektFoerUfoereGjeldende: OpplysningerBruktIBeregningUTDto.InntektFoerUfoereGjeldende,
        val inntektsAvkortingGjeldende: OpplysningerBruktIBeregningUTDto.InntektsAvkortingGjeldende,
        val inntektsgrenseErUnderTak: Boolean,
        val beregnetUTPerManedGjeldende: OpplysningerBruktIBeregningUTDto.BeregnetUTPerManedGjeldende,
        val inntektEtterUfoereGjeldendeBeloep: Kroner?,
        val erUngUfoer: Boolean,
        val trygdetidsdetaljerGjeldende: OpplysningerBruktIBeregningUTDto.TrygdetidsdetaljerGjeldende,
        val barnetilleggGjeldende: OpplysningerBruktIBeregningUTDto.BarnetilleggGjeldende?,
        val harMinsteytelse: Boolean,
        val brukersSivilstand: Sivilstand,
        val borMedSivilstand: BorMedSivilstand?,
        val kravGjelderFoerstegangsbehandlingBosattUtland: Boolean,
        val antallAarOver1G: Int,
        val antallAarOverInntektIAvtaleland: Int,
        val ufoeretrygd_reduksjonsgrunnlag_gradertOppjustertIFU: Kroner,
        val beregningUfore_andelYtelseAvOIFU: Int,
        val beregningUfore_BeregningVirkningDatoFom: LocalDate,
        val beregningUfore_prosentsatsOIFUForTak: Int,
    )

    data class OpplysningerOmMinstetilleggDto(
        val minsteytelseGjeldendeSats: Double?,
        val ungUfoerGjeldende_erUnder20Aar: Boolean?,
        val ufoeretrygdGjeldende: OpplysningerBruktIBeregningUTDto.UfoeretrygdGjeldende,
        val inntektFoerUfoereGjeldende: OpplysningerBruktIBeregningUTDto.InntektFoerUfoereGjeldende,
        val inntektsgrenseErUnderTak: Boolean,
    )

    data class OpplysningerOmBarnetilleggDto(
        val barnetillegg: OpplysningerBruktIBeregningUTDto.BarnetilleggGjeldende,
        val anvendtTrygdetid: Int,
        val harYrkesskade: Boolean,
        val harKravaarsakEndringInntekt: Boolean,
        val fraOgMedDatoErNesteAar: Boolean,
    )
}