// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2

import no.nav.pensjon.brevbaker.api.model.BrevbakerType.Kroner
import java.time.LocalDate

data class PEgruppe2(
    val vedtaksbrev: Vedtaksbrev?
) {
    data class Vedtaksbrev(
        val vedtaksdata: Vedtaksdata?
    ) {
        data class Vedtaksdata(
            val beregningsdata: Beregningsdata?,
            val etterbetaling: Boolean?,
            val kravhode: Kravhode?,
            val vilkarsvedtaklist: Vilkarsvedtaklist?,
            val virkningfom: LocalDate?,
            val virkningtom: LocalDate?
        ) {
            data class Beregningsdata(
                val beregningantallperioder: Int?,
                val beregningperiode: List<Beregningperiode>?,
                val beregningsrelasjoner: Beregningsrelasjoner?,
                val beregningufore: Beregningufore?
            ) {
                data class Beregningperiode(
                    val beregningssammendragbruker: Beregningssammendragbruker?,
                    val beregningytelsekomp: Beregningytelsekomp?,
                    val brutto: Kroner?,
                    val grunnbelop: Kroner?,
                    val netto: Kroner?,
                    val periodearsakliste: List<Periodearsakliste>?,
                    val virkdatofom: LocalDate?,
                    val virkdatotom: LocalDate?
                ) {
                    data class Beregningssammendragbruker(
                        val brukerfpi: Int?
                    )

                    data class Beregningytelsekomp(
                        val familietillegg: Familietillegg?,
                        val fasteutgifter: Fasteutgifter?,
                        val grunnpensjon: Grunnpensjon?,
                        val sertillegg: Sertillegg?,
                        val tilleggspensjon: Tilleggspensjon?
                    ) {
                        data class Familietillegg(
                            val familietilleggbrutto: Kroner?,
                            val familietillegginnvilget: Boolean?,
                            val familietilleggnetto: Kroner?
                        )

                        data class Fasteutgifter(
                            val fasteutgifterbrutto: Kroner?,
                            val fasteutgifterinnvilget: Boolean?,
                            val fasteutgifternetto: Kroner?
                        )

                        data class Grunnpensjon(
                            val gpbrutto: Kroner?,
                            val gpnetto: Kroner?
                        )

                        data class Sertillegg(
                            val stbrutto: Kroner?,
                            val stinnvilget: Boolean?,
                            val stnetto: Kroner?
                        )

                        data class Tilleggspensjon(
                            val tpbrutto: Kroner?,
                            val tpinnvilget: Boolean?,
                            val tpnetto: Kroner?
                        )
                    }

                    data class Periodearsakliste(
                        val periodearsakkode: String?
                    )
                }

                data class Beregningsrelasjoner(
                    val avdodetternavn: String?,
                    val avdodfornavn: String?,
                    val avdodmellomnavn: String?
                )

                data class Beregningufore(
                    val beregningektefelleinntektover2g: Boolean?,
                    val beregningektefellemottarpensjon: Boolean?,
                    val beregningnokkelinfo: Beregningnokkelinfo?,
                    val beregningsinformasjonkapittel19: Beregningsinformasjonkapittel19?,
                    val beregningsivilstandanvendt: String?,
                    val beregningssammendragavdod: Beregningssammendragavdod?,
                    val beregningssammendragbruker: Beregningssammendragbruker?,
                    val beregningytelseskomp: Beregningytelseskomp?,
                    val brutto: Kroner?,
                    val grunnbelop: Kroner?,
                    val netto: Kroner?,
                    val periodearsakliste: List<Periodearsakliste>?,
                    val virkdatofom: LocalDate?,
                    val yug: Int?
                ) {
                    data class Beregningnokkelinfo(
                        val beregningnokkelinfo2: Beregningnokkelinfo2?,
                        val ttanvbest: Int?
                    ) {
                        data class Beregningnokkelinfo2(
                            val beregningsmetode2: String?,
                            val opt: Opt?,
                            val penpersonfnr: String?,
                            val spt: Spt?,
                            val ttanv: Int?,
                            val ypt: Ypt?
                        ) {
                            data class Opt(
                                val sluttpoengtallmedok: Double?,
                                val sluttpoengtallmedokeos: Double?,
                                val sluttpoengtallmedoknordisk: Double?
                            )

                            data class Spt(
                                val poengrekke: Poengrekke?,
                                val poengrekkepopulert: Boolean?,
                                val sluttpoengtallutenok: Double?,
                                val sluttpoengtallutenokeos: Double?,
                                val sluttpoengtallutenoknordisk: Double?
                            ) {
                                data class Poengrekke(
                                    val framtidigpoengarnordenbrutto: Int?,
                                    val framtidigpoengarnordennetto: Int?,
                                    val framtidigpoengtall: Int?,
                                    val poengarnevnereos: Int?,
                                    val poengartellereos: Int?,
                                    val poengarutenok: Int?,
                                    val poengarutenoke91: Int?,
                                    val poengarutenokf92: Int?,
                                    val poengarutenokfaktiskeeos: Int?,
                                    val poengarutenokfaktiskenorden: Int?,
                                    val poengarutenokfaktiskenorge: Int?,
                                    val poengarutenokteoretiskeos: Int?,
                                    val poengtall: List<Poengtall>?
                                ) {
                                    data class Poengtall(
                                        val ar: Ar?
                                    ) {
                                        data class Ar(
                                            val arstall: String?,
                                            val grunnbelopveiet: Kroner?,
                                            val pensjonsgivendeinntekt: Kroner?,
                                            val pensjonspoeng: Double?,
                                            val poengtallstype: String?
                                        )
                                    }
                                }
                            }

                            data class Ypt(
                                val poengrekke: Poengrekke?,
                                val sluttpoengtallyrke: Double?
                            ) {
                                data class Poengrekke(
                                    val poengaryrke: Int?,
                                    val poengaryrkee91: Int?,
                                    val poengaryrkef92: Int?
                                )
                            }
                        }
                    }

                    data class Beregningsinformasjonkapittel19(
                        val yug: Int?
                    )

                    data class Beregningssammendragavdod(
                        val avdoddodsdato: LocalDate?,
                        val avdoddodsfallskyldesyrkesskade: Boolean?,
                        val avdodflyktning: Boolean?,
                        val avdodskadetidspunktyrkesskade: LocalDate?,
                        val avdodunguforfodtetter1940: Boolean?,
                        val avdodunguforfodtfor1941: Boolean?
                    )

                    data class Beregningssammendragbruker(
                        val brukerflyktning: Boolean?,
                        val brukerfpi: Int?
                    )

                    data class Beregningytelseskomp(
                        val familietillegg: Familietillegg?,
                        val fasteutgifter: Fasteutgifter?,
                        val grunnpensjon: Grunnpensjon?,
                        val sertillegg: Sertillegg?,
                        val tilleggspensjon: Tilleggspensjon?
                    ) {
                        data class Familietillegg(
                            val familietilleggbrutto: Kroner?,
                            val familietillegginnvilget: Boolean?,
                            val familietilleggnetto: Kroner?
                        )

                        data class Fasteutgifter(
                            val fasteutgifterbrutto: Kroner?,
                            val fasteutgifterinnvilget: Boolean?,
                            val fasteutgifternetto: Kroner?
                        )

                        data class Grunnpensjon(
                            val gpbrutto: Kroner?,
                            val gpnetto: Kroner?
                        )

                        data class Sertillegg(
                            val stbrutto: Kroner?,
                            val stinnvilget: Boolean?,
                            val stnetto: Kroner?
                        )

                        data class Tilleggspensjon(
                            val tpbrutto: Kroner?,
                            val tpinnvilget: Boolean?,
                            val tpnetto: Kroner?
                        )
                    }

                    data class Periodearsakliste(
                        val periodearsakkode: String?
                    )
                }
            }

            data class Kravhode(
                val behandlendeenhet: String?,
                val kravmottatdato: LocalDate?,
                val vurderetrygdeavtale: Boolean?
            )

            data class Vilkarsvedtaklist(
                val vilkarsvedtak: List<Vilkarsvedtak>?
            ) {
                data class Vilkarsvedtak(
                    val vilkaranvendtvurdering: String?
                )
            }
        }
    }
}
