// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2

import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.Grunnlag
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.Vedtaksbrev

data class PEgruppe2(
    val grunnlag: Grunnlag?,
    val vedtaksbrev: Vedtaksbrev?
)
