// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagsliste

import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagsliste.inngangogeksportgrunnlag.Inngangogeksportgrunnlag
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagsliste.trygdeavtaler.Trygdeavtaler

data class Persongrunnlagsliste(
    val inngangogeksportgrunnlag: Inngangogeksportgrunnlag?,
    val trygdeavtaler: Trygdeavtaler?
)
