package no.nav.pensjon.etterlatte

import no.nav.pensjon.brevbaker.api.model.Felles
import no.nav.pensjon.brevbaker.api.model.LanguageCode

enum class EtterlatteBrevKode {
    BARNEPENSJON_AVSLAG,
    BARNEPENSJON_AVSLAG_IKKEYRKESSKADE,
    BARNEPENSJON_INNVILGELSE,
    BARNEPENSJON_INNVILGELSE_NY,
    BARNEPENSJON_REVURDERING_ADOPSJON,
    BARNEPENSJON_REVURDERING_ENDRING,
    BARNEPENSJON_REVURDERING_FENGSELSOPPHOLD,
    BARNEPENSJON_REVURDERING_HAR_STANSET,
    BARNEPENSJON_REVURDERING_OMGJOERING_AV_FARSKAP,
    BARNEPENSJON_REVURDERING_OPPHOER,
    BARNEPENSJON_REVURDERING_SOESKENJUSTERING,
    BARNEPENSJON_REVURDERING_UT_AV_FENGSELSOPPHOLD,
    BARNEPENSJON_REVURDERING_YRKESSKADE,
    OMS_FOERSTEGANGSVEDTAK_INNVILGELSE,
    OMS_FOERSTEGANGSVEDTAK_INNVILGELSE_UTFALL,
    OMS_INNVILGELSE_MANUELL,
    OMS_INNVILGELSE_AUTO,
    OMS_OPPHOER_MANUELL
}

data class EtterlatteBrevRequest(val kode: EtterlatteBrevKode, val letterData: Any, val felles: Felles, val language: LanguageCode)
