package no.nav.pensjon.etterlatte

import no.nav.pensjon.brevbaker.api.model.Felles
import no.nav.pensjon.brevbaker.api.model.LanguageCode

enum class EtterlatteBrevKode {
    BARNEPENSJON_AVSLAG,
    BARNEPENSJON_AVSLAG_UTFALL,
    BARNEPENSJON_INNVILGELSE,
    BARNEPENSJON_INNVILGELSE_UTFALL,
    BARNEPENSJON_OPPHOER,
    BARNEPENSJON_OPPHOER_UTFALL,
    BARNEPENSJON_REVURDERING,
    BARNEPENSJON_REVURDERING_UTFALL,
    BARNEPENSJON_VEDTAK_OMREGNING,
    BARNEPENSJON_VEDTAK_OMREGNING_FERDIG,
    BARNEPENSJON_FORHAANDSVARSEL_OMREGNING,
    OMSTILLINGSSTOENAD_AVSLAG,
    OMSTILLINGSSTOENAD_AVSLAG_UTFALL,
    OMSTILLINGSSTOENAD_INNVILGELSE,
    OMSTILLINGSSTOENAD_INNVILGELSE_UTFALL,
    OMSTILLINGSSTOENAD_OPPHOER,
    OMSTILLINGSSTOENAD_OPPHOER_UTFALL,
    OMSTILLINGSSTOENAD_REVURDERING,
    TILBAKEKREVING_INNHOLD,
    TILBAKEKREVING_FERDIG,
    TOM_MAL,
    TOM_DELMAL,
    TOM_MAL_INFORMASJONSBREV,
    UTSATT_KLAGEFRIST,
}

data class EtterlatteBrevRequest(val kode: EtterlatteBrevKode, val letterData: Any, val felles: Felles, val language: LanguageCode)
