package no.nav.pensjon.etterlatte

import no.nav.pensjon.brevbaker.api.model.Felles
import no.nav.pensjon.brevbaker.api.model.LanguageCode

enum class EtterlatteBrevKode {
    BARNEPENSJON_AVSLAG,
    BARNEPENSJON_AVSLAG_ENKEL,
    BARNEPENSJON_INNVILGELSE,
    BARNEPENSJON_INNVILGELSE_ENKEL,
    BARNEPENSJON_INNVILGELSE_NY,
    BARNEPENSJON_REVURDERING_ADOPSJON,
    BARNEPENSJON_REVURDERING_ENDRING,
    BARNEPENSJON_REVURDERING_OMGJOERING_AV_FARSKAP,
    BARNEPENSJON_REVURDERING_OPPHOER,
    BARNEPENSJON_REVURDERING_SOESKENJUSTERING,
    BARNEPENSJON_VEDTAK_OMREGNING,
    BARNEPENSJON_FORHAANDSVARSEL_OMREGNING,
    OMS_FOERSTEGANGSVEDTAK_INNVILGELSE,
    OMS_FOERSTEGANGSVEDTAK_INNVILGELSE_UTFALL,
    OMS_INNVILGELSE_MANUELL,
    OMS_INNVILGELSE_AUTO,
    OMS_AVSLAG,
    OMS_AVSLAG_BEGRUNNELSE,
    OMS_OPPHOER_MANUELL,
    OMS_REVURDERING_ENDRING,
    OMS_REVURDERING_OPPHOER,
    OMS_REVURDERING_OPPHOER_GENERELL,
    TILBAKEKREVING_INNHOLD,
    TILBAKEKREVING_FERDIG,
    TOM_MAL,
}

data class EtterlatteBrevRequest(val kode: EtterlatteBrevKode, val letterData: Any, val felles: Felles, val language: LanguageCode)
