package no.nav.pensjon.brev.alder.model

import no.nav.pensjon.brev.api.model.maler.Brevkode.Automatisk
import no.nav.pensjon.brev.api.model.maler.Brevkode.Redigerbart

object Aldersbrevkoder {
    enum class AutoBrev : Automatisk {
        INFO_EPS_60_AAR_AUTO,
        INFO_EPS_62_AAR_AUTO,
        INFO_FYLLER_67_AAR_SAERSKILT_SATS,
        PE_ADHOC_2024_FEIL_INFOBREV_AP_SENDT_BRUKER,
        PE_AFP_2024_INFO_TOLERANSEBELOP,
        PE_AP_2024_IKKEUTBET_FT_VARSEL_OPPH,
        PE_AP_2024_UTBET_FT_VARSEL_OPPH,
        PE_AP_ADHOC_2024_GJR_AP_MNTINDV_2,
        PE_AP_ADHOC_2024_REGLERENDRET_GJR_AP_MNTINDV,
        PE_AP_ADHOC_2025_OPPRYDDING_GJT_KAP_20,
        PE_AP_ADHOC_2025_SKJERMT_FEIL_BEROERT_BRUKER,
        PE_AP_ADHOC_2025_SKJERMT_FEIL_MOTTAKER,
        PE_AP_ADHOC_2025_VARSELBREV_GJT_KAP_20,
        PE_AP_AVSLAG_GRAD_FOER_NORM_PEN_ALDER_AP2016_AUTO,
        PE_AP_AVSLAG_GRAD_FOER_NORM_PEN_ALDER_AUTO,
        PE_AP_AVSLAG_GRAD_FOER_NORM_PEN_ALDER_ETT_AAR_AUTO,
        PE_AP_AVSLAG_UTTAK_FOER_NORM_PEN_ALDER_AP2016_AUTO,
        PE_AP_AVSLAG_UTTAK_FOER_NORM_PEN_ALDER_AUTO,
        PE_AP_ENDRING_AV_ALDERSPENSJON_SIVILSTAND_AUTO,
        PE_AP_ENDRING_FORDI_DU_FYLLER_75_AAR_AUTO,
        PE_AP_INFO_ALDERSOVERGANG_67_AAR_AUTO,
        PE_AP_OMREGNING_ALDER_UFORE_2016_AUTO,
        VEDTAK_ALDERSOVERGANG_67_AAR_GARANTITILLEGG_AUTO,
        VEDTAK_ENDRING_AV_AFP_ENDRET_OPPTJENING_AUTO,
        VEDTAK_OMREGNING_GJP_TIL_ALDER_AUTO,
        ;

        override fun kode(): String = this.name
    }

    enum class Redigerbar : Redigerbart {
        PE_AP_ENDRING_AV_ALDERSPENSJON_GARANTITILLEGG,
        PE_AP_ENDRING_AV_ALDERSPENSJON_SAERSKILT_SATS,
        PE_AP_ENDRING_AV_ALDERSPENSJON_SIVILSTAND,
        PE_AP_AVSLAG_GRAD_FOER_NORM_PEN_ALDER,
        PE_AP_AVSLAG_GRAD_FOER_NORM_PEN_ALDER_AP2016,
        PE_AP_AVSLAG_GRAD_FOER_NORM_PEN_ALDER_ETT_AAR,
        PE_AP_AVSLAG_UTTAK_FOER_NORM_PEN_ALDER,
        PE_AP_AVSLAG_UTTAK_FOER_NORM_PEN_ALDER_AP2016,
        PE_AP_OMREGNING_ALDER_UFORE_2016,
        PE_AP_STANS_FLYTTING_MELLOM_LAND
        ;

        override fun kode(): String = this.name
    }
}
