// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod

import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.inngangogeksportgrunnlag.Inngangogeksportgrunnlag
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdeavtaledetaljer.Trygdeavtaledetaljer
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdeavtaler.Trygdeavtaler
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdetid.Trygdetid
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdetidsgrunnlaglistebilateral.Trygdetidsgrunnlaglistebilateral
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdetidsgrunnlaglisteeos.Trygdetidsgrunnlaglisteeos
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdetidsgrunnlaglistenor.Trygdetidsgrunnlaglistenor
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.ttutlandtrygdeavtale.Ttutlandtrygdeavtale

data class Persongrunnlagslisteavdod(
    val inngangogeksportgrunnlag: Inngangogeksportgrunnlag?,
    val trygdeavtaledetaljer: Trygdeavtaledetaljer?,
    val trygdeavtaler: Trygdeavtaler?,
    val trygdetid: Trygdetid?,
    val trygdetidsgrunnlaglistebilateral: Trygdetidsgrunnlaglistebilateral?,
    val trygdetidsgrunnlaglisteeos: Trygdetidsgrunnlaglisteeos?,
    val trygdetidsgrunnlaglistenor: Trygdetidsgrunnlaglistenor?,
    val ttutlandtrygdeavtale: Ttutlandtrygdeavtale?
)
