name: "pr-suksess"
description: "Verifiser at PR-en er suksessfull og klar til merge"
branding:
  icon: "lock"
  color: "green"
runs:
  using: "composite"
  steps:
    - id: ok
      shell: bash
      run: |
        echo "Klar til merge"