// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningnokkelinfo.beregningnokkelinfo2.spt.poengrekke.poengtall.ar

import no.nav.pensjon.brevbaker.api.model.BrevbakerType.Kroner

data class Ar(
    val arstall: String?,
    val grunnbelopveiet: Kroner?,
    val pensjonsgivendeinntekt: Kroner?,
    val pensjonspoeng: Double?,
    val poengtallstype: String?
)
