// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdetidsgrunnlaglistebilateral.trygdetidsgrunnlagbilateral

import java.time.LocalDate

data class Trygdetidsgrunnlagbilateral(
    val trygdetidbilateralland: String?,
    val trygdetidfombilateral: LocalDate?,
    val trygdetidtombilateral: LocalDate?
)
