apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pensjon-pdf-bygger
  namespace: pensjonsbrev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pensjon-pdf-bygger
  minReplicas: 12
  maxReplicas: 150
  metrics:
    - type: External
      external:
        metric:
          name: pensjonsbrev_pdf_compile_active_active
        target:
          type: AverageValue
          averageValue: "4" #PDF_BYGGER_LATEX_PARALLELISM / 2