apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app-name}}
  namespace: "pensjonsbrev"
  labels:
    "team": "pensjonsbrev"
spec:
  image: {{image}}
  port: 8080
  terminationGracePeriodSeconds: 60
  service:
    port: 8080
    protocol: http
  liveness:
    path: "/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isReady"
    port: 8080
    initialDelay: 20
    timeout: 5
  replicas:
    min: 12
    max: 300
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
    port: "8080"
  resources:
    requests:
      cpu: "2"
      memory: "2048Mi"
    limits:
      memory: "8192Mi"
  accessPolicy:
    inbound:
      rules:
        - application: {{brevbaker-app}}
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/tmp
  env:
    - name: PDF_BYGGER_COMPILE_TIMEOUT
      value: "120s"
    - name: PDF_BYGGER_LATEX_PARALLELISM
      value: "16"
    - name: PDF_BYGGER_COMPILE_QUEUE_WAIT_TIMEOUT
      value: "4s"