apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app-name}}
  namespace: "pensjonsbrev"
  labels:
    "team": "pensjonsbrev"
spec:
  image: {{image}}
  port: 8080
  service:
    port: 8080
    protocol: http
  liveness:
    path: "/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 10
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
    port: "8080"
  resources:
    requests:
      cpu: "1"
      memory: "1024Mi"
    limits:
      cpu: "2"
      memory: "2048Mi"
  accessPolicy:
    inbound:
      rules:
        - application: {{brevbaker-app}}
#  env:
#    {{#each env as |e|}}
#       - name: {{e.name }}
#         value: {{{e.value }}}
#    {{/each}}