apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: pdfByggerRender
  namespace: pensjonsbrev
  labels:
    team: pensjonsbrev
spec:
  pool: nais-dev
  acl:
    - team: pensjonsbrev
      application: pensjon-brevbaker
      access: write
    - team: pensjonsbrev
      application: pensjon-pdf-bygger-async
      access: read
  config:
    partitions: 20