apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app-name}}
  namespace: "pensjonsbrev"
  labels:
    "team": "pensjonsbrev"
spec:
  image: {{image}}
  port: 3000
  service:
    port: 80
    protocol: http
  liveness:
    path: "/health"
    port: 3000
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/health"
    port: 3000
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 10
    cpuThresholdPercentage: 50
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "300m"
    memory: "512Mi"

  azure:
    application:
      enabled: true
      singlePageApplication: true
      replyUrls:
        {{#each ingresses as |url|}}
           - {{url}}/
        {{/each}}
  ingresses:
    {{#each ingresses as |url|}}
      - {{url}}
    {{/each}}
  env:
    {{#each env as |e|}}
      - name: {{e.name }}
        value: {{{e.value }}}
    {{/each}}