// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdetidsgrunnlaglistenor

import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdetidsgrunnlaglistenor.trygdetidsgrunnlag.Trygdetidsgrunnlag

data class Trygdetidsgrunnlaglistenor(
    val trygdetidsgrunnlag: Trygdetidsgrunnlag?
)
