// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdetidsgrunnlaglistebilateral

import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdetidsgrunnlaglistebilateral.trygdetidsgrunnlagbilateral.Trygdetidsgrunnlagbilateral

data class Trygdetidsgrunnlaglistebilateral(
    val trygdetidsgrunnlagbilateral: Trygdetidsgrunnlagbilateral?
)
