// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdeavtaledetaljer

data class Trygdeavtaledetaljer(
    val art10bruktgp: Boolean?,
    val ttnordiskar: Int?,
    val ttnordiskmnd: Int?
)
