// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningperiode.beregningssammendragbruker

data class Beregningssammendragbruker(
    val brukerfpi: Int?
)
