package no.nav.pensjon.brev.ufore.maler.vedlegg

import no.nav.brev.brevbaker.LetterTestImpl
import no.nav.brev.brevbaker.TestTags
import no.nav.brev.brevbaker.createVedleggTestTemplate
import no.nav.brev.brevbaker.renderTestHtml
import no.nav.pensjon.brev.api.model.maler.EmptyAutobrevdata
import no.nav.pensjon.brev.template.Language
import no.nav.pensjon.brev.template.dsl.expression.expr
import no.nav.pensjon.brev.template.dsl.languages
import no.nav.pensjon.brev.ufore.Fixtures
import no.nav.pensjon.brev.ufore.api.model.vedlegg.Beregningsmetode
import no.nav.pensjon.brev.ufore.api.model.vedlegg.BorMedSivilstand
import no.nav.pensjon.brev.ufore.api.model.vedlegg.Kravaarsaktype
import no.nav.pensjon.brev.ufore.api.model.vedlegg.OpplysningerBruktIBeregningUTLegacyDto as Dto
import no.nav.pensjon.brev.ufore.api.model.vedlegg.Sivilstand
import no.nav.pensjon.brev.ufore.api.model.vedlegg.SivilstatusVisning
import no.nav.pensjon.brev.ufore.maler.vedlegg.opplysningerbruktiberegning.vedleggOpplysningerBruktIBeregningUTLegacy
import no.nav.pensjon.brevbaker.api.model.BrevbakerType.Kroner
import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.Test
import java.time.LocalDate

@Tag(TestTags.MANUAL_TEST)
class OpplysningerBruktIBeregningUTLegacyTest {

    @Test
    fun `lag vedlegg paa bokmaal`() {
        render(Language.Bokmal, "OpplysningerBruktIBeregningUTLegacy_Bokmal")
    }

    @Test
    fun `lag vedlegg paa nynorsk`() {
        render(Language.Nynorsk, "OpplysningerBruktIBeregningUTLegacy_Nynorsk")
    }

    private fun render(language: Language, fileName: String) {
        val template = createVedleggTestTemplate(
            vedleggOpplysningerBruktIBeregningUTLegacy,
            createOpplysningerBruktIBeregningUTLegacyDto().expr(),
            languages(Language.Bokmal, Language.Nynorsk),
        )
        LetterTestImpl(template, EmptyAutobrevdata, language, Fixtures.felles).renderTestHtml(fileName)
    }
}

fun createOpplysningerBruktIBeregningUTLegacyDto(): Dto = Dto(
    beregning = Dto.Beregning(
        grunnbeloep = Kroner(124028),
        beregningVirkningDatoFom = LocalDate.of(2026, 1, 1),
        ufoeregrad = 70,
        ufoeretidspunkt = LocalDate.of(2018, 6, 1),
        beregningsmetode = Beregningsmetode.CANADA,
        anvendtTrygdetid = 35,
        mottarMinsteytelse = true,
        proRataBroekTeller = 35,
        proRataBroekNevner = 40,
        yrkesskadegrad = 40,
        totalNetto = Kroner(245000),
        beloepRedusert = true,
        brukerKonvertertUP = true,
    ),
    avkortning = Dto.Avkortning(
        forventetInntektAar = Kroner(180000),
        inntektsgrenseAar = Kroner(110000),
        inntektsgrenseFaktisk = Kroner(90000),
        inntektstak = Kroner(650000),
        beloepsgrense = Kroner(60000),
        kompensasjonsgrad = 66.0,
        utbetalingsgrad = 65,
        oifu = Kroner(520000),
        andelYtelseAvOifu = 0.45,
        prosentsatsOifuForTak = 80.0,
        gradertOppjustertIFU = Kroner(360000),
        ugradertBruttoPerAar = Kroner(310000),
        fradrag = Kroner(25000),
        nettoAkk = Kroner(120000),
        nettoRestAar = Kroner(125000),
        overskytendeInntekt = Kroner(70000),
        reduksjonPerAar = Kroner(42000),
        nettoAkkPlussNettoRestAar = Kroner(245000),
        nettoAkkPlussNettoRestAarPlussForventetInntekt = Kroner(425000),
    ),
    ytelsesgrunnlag = Dto.Ytelsesgrunnlag(
        beregningsgrunnlagOrdinaerAarsbeloep = Kroner(520000),
        yrkesskadeAarsbeloep = Kroner(480000),
        inntektVedSkadetidspunkt = Kroner(430000),
        antallAarOver1G = 12,
        antallAarInntektIAvtaleland = 4,
        opptjeningUTListe = listOf(opptjening(2024, brukt = true)),
    ),
    minsteytelse = Dto.Minsteytelse(
        sats = 2.91,
        oppfyltUngUfoer = true,
    ),
    inntektFoerUfoere = Dto.InntektFoerUfoere(
        ifuInntekt = Kroner(520000),
        ifuBegrunnelse = "Fastsettelsen bygger på de tre beste inntektsårene før uføretidspunktet.",
        ieuInntekt = Kroner(180000),
        ieuBegrunnelse = "Forventet inntekt etter uførhet er oppgitt av bruker.",
    ),
    trygdetid = Dto.Trygdetid(
        faktiskTTNorge = 25,
        framtidigTTNorsk = 10,
        faktiskTTEOS = 5,
        framtidigTTEOS = 3,
        tellerTTEOS = 28,
        nevnerTTEOS = 40,
        faktiskTTNordisk = 6,
        tellerTTNordisk = 31,
        nevnerTTNordisk = 40,
        faktiskTTBilateral = 4,
        framtidigTTAvtaleland = 2,
        tellerTTBilateral = 29,
        nevnerTTBilateral = 40,
        sumFattNorgeFattEOS = 33,
        sumFattNorgeFattA10Netto = 31,
        sumFattNorgeFattBilateral = 29,
        sumFattNorgeFramtidigTTNorgeDiv12 = 35,
        redusertFramtidigTrygdetid = true,
        trygdetidFomNorge = LocalDate.of(2000, 1, 1),
        trygdetidFomBilateral = LocalDate.of(2008, 1, 1),
        avtaleland = "Canada",
        perioderNorge = listOf(periode(LocalDate.of(2000, 1, 1), LocalDate.of(2020, 12, 31))),
        perioderEOS = listOf(periodeMedLand("Sverige", LocalDate.of(2021, 1, 1), LocalDate.of(2023, 12, 31))),
        perioderBilateral = listOf(periodeMedLand("Canada", LocalDate.of(2024, 1, 1), LocalDate.of(2025, 12, 31))),
    ),
    trygdetidAvdoed = Dto.TrygdetidAvdoed(
        faktiskTTNorge = 20,
        framtidigTTNorsk = 12,
        faktiskTTEOS = 4,
        framtidigTTEOS = 2,
        tellerTTEOS = 26,
        nevnerTTEOS = 40,
        faktiskTTNordisk = 5,
        tellerTTNordisk = 27,
        nevnerTTNordisk = 40,
        faktiskTTBilateral = 3,
        framtidigTTAvtaleland = 2,
        tellerTTBilateral = 25,
        nevnerTTBilateral = 40,
        fattNorgePlussFattEOSAvdoed = 26,
        fattNorgePlussFattA10NettoAvdoed = 27,
        fattNorgePlussFattBilateralAvdoed = 25,
        sumFattNorgeFramtidigTTNorgeDiv12Avdoed = 32,
        framtidigTrygdetidUnder40Aar = true,
        trygdetidFomNorge = LocalDate.of(2002, 1, 1),
        trygdetidFomBilateral = LocalDate.of(2010, 1, 1),
        perioderNorge = listOf(periode(LocalDate.of(2002, 1, 1), LocalDate.of(2017, 12, 31))),
        perioderEOS = listOf(periodeMedLand("Danmark", LocalDate.of(2018, 1, 1), LocalDate.of(2020, 12, 31))),
        perioderBilateral = listOf(periodeMedLand("USA", LocalDate.of(2021, 1, 1), LocalDate.of(2023, 12, 31))),
    ),
    gjenlevendetillegg = Dto.Gjenlevendetillegg(
        nyttGjenlevendetillegg = true,
        gtInnvilget = true,
        avdoedFoedselsnummer = "01017012345",
        avdoedErFlyktning = true,
        anvendtTrygdetid = 32,
        ufoeretidspunkt = LocalDate.of(2017, 5, 1),
        yrkesskadegrad = 30,
        inntektVedSkadetidspunkt = Kroner(410000),
        beregningsgrunnlagAvdoedAarsbeloep = Kroner(460000),
        yrkesskadeAarsbeloep = Kroner(440000),
        minsteytelseBenyttetUngUfoer = true,
        opptjeningUTListeAvdoed = listOf(opptjening(2023, brukt = true)),
    ),
    barnetilleggFelles = barnetillegg(
        antallBarn = 1,
        netto = Kroner(15000),
        justeringsbeloepPerAar = Kroner(1200),
        justeringsbeloepPerAarUtenMinus = Kroner(1200),
    ),
    barnetilleggSaerkull = barnetillegg(
        antallBarn = 1,
        netto = Kroner(12000),
        justeringsbeloepPerAar = Kroner(800),
        justeringsbeloepPerAarUtenMinus = Kroner(800),
    ),
    antallBarnTotalt = 2,
    harEktefelletillegg = true,
    belopsendring = Dto.Belopsendring(
        beloepGammelUT = Kroner(230000),
        beloepNyUT = Kroner(245000),
    ),
    yrkesskade = Dto.Yrkesskade(
        yrkesskadegrad = 40,
        skadetidspunkt = LocalDate.of(2015, 3, 15),
        inntektVedSkadetidspunkt = Kroner(430000),
        beregningsgrunnlagBeloepAar = Kroner(480000),
    ),
    krav = Dto.Krav(
        kravaarsaktype = Kravaarsaktype.ENDRET_INNTEKT,
        onsketVirkningsdato = LocalDate.of(2026, 1, 1),
        boddArbeidetUtland = true,
        boddArbeidetUtlandAvdoed = true,
        vurderTrygdeavtale = true,
    ),
    person = Dto.Person(
        foedselsdato = LocalDate.of(1980, 4, 12),
        sivilstand = Sivilstand.GIFT,
        borMedSivilstand = BorMedSivilstand.EKTEFELLE,
        erFlyktning = true,
        bostedsland = "Norge",
        sivilstatusVisning = SivilstatusVisning.GIFT,
        foedselsdatoTilBarnTilleggErInnvilgetFor = listOf(LocalDate.of(2012, 8, 20), LocalDate.of(2015, 11, 5)),
    ),
    visningsflagg = Dto.Visningsflagg(
        visTrygdetid = true,
        visStandardFastsettelseTrygdetid = true,
        harFramtidigTrygdetid = true,
        yrkesskadeVilkaarOppfylt = true,
        ufoeregradLikYrkesskadegrad = true,
        erMaanedEtterFoedsel = true,
        visTrygdetidNorgeTabell = true,
        visTrygdetidEOS = true,
        visTrygdetidBilateral = true,
        visRedusertFramtidigTrygdetidTekst = true,
        visInntektsseksjon = true,
        visInntektsgrunnlagAvdoed = true,
        visInntektsgrunnlagAvdoedUtland = true,
        visTrygdetidAvdoedNorgeTabell = true,
        visTrygdetidAvdoedEOS = true,
        visTrygdetidAvdoedBilateral = true,
        harOpptjeningUTMedFoerstegangstjenesteOgOmsorg = true,
        harOpptjeningUTMedFoerstegangstjenesteOgIkkeOmsorg = true,
        harOpptjeningUTMedOmsorgOgIkkeFoerstegangstjeneste = true,
        harOpptjeningUTMedOpptjeningBruktAaretFoerOgFoerstegangstjeneste = true,
        avdoedHarOpptjeningUTMedFoerstegangstjenesteOgOmsorg = true,
        avdoedHarOpptjeningUTMedFoerstegangstjenesteOgIkkeOmsorg = true,
        avdoedHarOpptjeningUTMedOmsorgOgIkkeFoerstegangstjeneste = true,
        tbu056v = true,
        tbu069v = true,
        tbu501v = true,
        tbu601v604v = true,
        tbu605 = true,
        tbu605vEllerTilDin = true,
        tbu606v608v = true,
        tbu606v611v = true,
        tbu608FaarIkke = true,
        tbu609v611v = true,
        tbu611FaarIkke = true,
        tbu613v = true,
        tbu613v1_3 = true,
        tbu613v4_5 = true,
        etteroppgjoerBtUtbetalt = true,
        visBrukerKonvertertUP = true,
        visEndringBeregningsgrunnlag = true,
        visEndringGjelderGjenlevende = true,
        visOektUfoeregrad = true,
        visGjenlevendetilleggOekerMedGrad = true,
        visBeregningStandardFemAar = true,
        visBeregningLigningIkkeFerdig = true,
        visBeregningFoerstegangstjeneste = true,
        visBeregningOmsorgsaar = true,
        visBeregningEOS = true,
        visGrunnbeloepJustering = true,
        visYrkesskadeBeregning = true,
        visMinsteytelse = true,
        visMinsteytelseSatsBlokk1 = true,
        visMinsteytelseSatsBlokk2 = true,
        visMinsteytelseSatsBlokk3 = true,
        visMinsteytelseSatsBlokk4 = true,
        ungUfoerUnder20 = true,
        visUngUfoerOver20EtterJuli2024 = true,
        visUngUfoerOver20FoerJuli2024 = true,
        visMinsteytelseEosSats = true,
        visUngUfoerUnder20Fremtid = true,
        visUngUfoerUnder20FremtidEtterJuli2024 = true,
        borMedEktefelleEllerSamboer = true,
        visHalvMinsteytelse = true,
        visEosBeregningIkkeSammenlegging = true,
        visEosBeregningSammenlegging = true,
        visBilateralBeregningSammenlegging = true,
        visFolketrygdVurdertTrygdeavtale = true,
        visAvdoedOpplysningerTabell = true,
        visBeregningsgrunnlag = true,
        visInntektFoerUfoere = true,
        visInntektsgrense = true,
        visForventetInntekt = true,
        visReduksjonsprosent = true,
        inntektsgrenseLavereEnnInntektstak = true,
        visSivilstatusRad = true,
        visPartnerAnnetBosted = true,
        visEktefelleAnnetBosted = true,
        visUngUfoerRad = true,
        beregningsmetodeErBilateral = true,
        visNorskFramtidigTrygdetid = true,
        visAarOver1G = true,
        visTotaltAntallBarn = true,
        visOifuFortak = true,
        visSamletInntektBarnetillegg = true,
        barnetilleggFellesInnvilget = true,
        barnetilleggSaerkullInnvilget = true,
        visSamletInntektAnnenForelder = true,
        visBarnetilleggSaerkullIkkeUtbetalt = true,
        visBarnetilleggFellesIkkeUtbetalt = true,
        visBarnetilleggRedusertKortTrygdetid = true,
        visBarnetilleggIkkeUtbetaltPgaInntekt = true,
        visBarnetilleggRedusertTilDegOgPartner = true,
        visBarnetilleggRedusertDin = true,
        visBarnetilleggBeggeTyperKortTrygdetidEtter2016 = true,
        visBarnetilleggEndretInntekt = true,
        visBarnetilleggIkkeEndretInntekt = true,
        visBarnetilleggTbu605EllerTilDinFellesMedPartner = true,
        visBarnetilleggEndretInntektFellesMedPartner = true,
        visBarnetilleggIkkeEndretInntektMedPartner = true,
        visBarnetilleggEndretInntektMedPartner = true,
        visBarnetilleggFribeloepEllerInntektPeriodisert = true,
        visBarnetilleggIngenPeriodisering = true,
        visBarnetilleggIngenJustering = true,
        visBarnetilleggHarJustering = true,
        visBarnetilleggJusteringPositiv = true,
        visBarnetilleggJusteringNegativ = true,
        visBarnetilleggVirkningFomFoersteJanuar = true,
        visBarnetilleggFellesNettoPositiv = true,
        visBarnetilleggFellesNettoNull = true,
        visBarnetilleggFellesNettoNullMedJustering = true,
        visBarnetilleggFellesVisReduksjonsrader = true,
        visBarnetilleggFellesVisAvkortingsbeloep = true,
        visBarnetilleggFellesHarJustering = true,
        visBarnetilleggFellesJusteringPositiv = true,
        visBarnetilleggFellesVisInntektstak = true,
        visBarnetilleggSaerkullNettoPositiv = true,
        visBarnetilleggSaerkullNettoNull = true,
        visBarnetilleggSaerkullNettoNullMedJustering = true,
        visBarnetilleggSaerkullVisReduksjonsrader = true,
        visBarnetilleggSaerkullVisAvkortingsbeloep = true,
        visBarnetilleggSaerkullHarJustering = true,
        visBarnetilleggSaerkullJusteringPositiv = true,
        visBarnetilleggSaerkullVisInntektstak = true,
        visFastsetterInntektFoerUfoer = true,
        visMinstenivaaInntektFoerUfoer = true,
        visSlikFastsetterViInntektEtterUfoer = true,
        visKompensasjonOppjustertInntekt = true,
        visReduksjonAvUforetrygd = true,
        visUtbetalingNaarInntektEndres = true,
        visUtbetalingNaarInntektEndresDetaljer = true,
        visUtbetalingFoerSkattTabell = true,
        visUtbetalingFoerSkattTittelKun = true,
        visMaanedligReduksjon = true,
        visUforetrygdInntektSum = true,
        visUtbetalingRedusertIkkeUtbetalt = true,
        visIkkeUtbetaltOver80Prosent = true,
        visFaarTilbakeUtenSoknad = true,
        visGjenlevendetilleggBeregning = true,
        visGjenlevendetilleggBeregningUP = true,
        visEktefelletilleggInnvilgetIkkeUnntak = true,
        visEktefelletilleggBeregningSeksjon = true,
        visEktefelletilleggBeregningUP = true,
        visEktefelletilleggMinstepensjon60 = true,
        visEtteroppgjoer = true,
    ),
)

private fun opptjening(aar: Int, brukt: Boolean) = Dto.Ytelsesgrunnlag.OpptjeningUT(
    aar = aar,
    brukt = brukt,
    pensjonsgivendeInntekt = Kroner(520000),
    justertBeloep = Kroner(500000),
    avkortetBeloep = Kroner(480000),
    omsorgsaar = true,
    foerstegangstjeneste = true,
    inntektIAvtaleland = true,
)

private fun periode(fom: LocalDate, tom: LocalDate) = Dto.Trygdetid.Periode(
    fom = fom,
    tom = tom,
)

private fun periodeMedLand(land: String, fom: LocalDate, tom: LocalDate) = Dto.Trygdetid.PeriodeMedLand(
    land = land,
    fom = fom,
    tom = tom,
)

private fun barnetillegg(
    antallBarn: Int,
    netto: Kroner,
    justeringsbeloepPerAar: Kroner,
    justeringsbeloepPerAarUtenMinus: Kroner,
) = Dto.Barnetillegg(
    innvilget = true,
    antallBarn = antallBarn,
    netto = netto,
    brutto = Kroner(18000),
    bruttoPerAar = Kroner(216000),
    nettoPerAar = Kroner(180000),
    fribeloep = Kroner(50000),
    inntektBruktIAvkortning = Kroner(170000),
    inntektBruktIAvkortningMinusFribeloep = Kroner(120000),
    avkortingsbeloepPerAar = Kroner(18000),
    justeringsbeloepPerAar = justeringsbeloepPerAar,
    justeringsbeloepPerAarUtenMinus = justeringsbeloepPerAarUtenMinus,
    inntektstak = Kroner(650000),
    fribeloepErPeriodisert = true,
    inntektErPeriodisert = true,
    brukersInntektTilAvkortning = Kroner(180000),
    beloepFratrukketAnnenForeldersInntekt = Kroner(15000),
    inntektAnnenForelder = Kroner(260000),
)
