// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata

import java.time.LocalDate
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.Beregningsdata
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.kravhode.Kravhode
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.vilkarsvedtaklist.Vilkarsvedtaklist

data class Vedtaksdata(
    val beregningsdata: Beregningsdata?,
    val etterbetaling: Boolean?,
    val kravhode: Kravhode?,
    val vilkarsvedtaklist: Vilkarsvedtaklist?,
    val virkningfom: LocalDate?,
    val virkningtom: LocalDate?
)
