/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SaksnummerIndexImport } from './routes/saksnummer.index'
import { Route as SaksnummerSaksIdRouteImport } from './routes/saksnummer_/$saksId/route'
import { Route as SaksnummerSaksIdKvitteringRouteImport } from './routes/saksnummer_/$saksId/kvittering/route'
import { Route as SaksnummerSaksIdBrevvelgerRouteImport } from './routes/saksnummer_/$saksId/brevvelger/route'
import { Route as SaksnummerSaksIdBrevbehandlerRouteImport } from './routes/saksnummer_/$saksId/brevbehandler/route'
import { Route as SaksnummerSaksIdBrevBrevIdImport } from './routes/saksnummer_/$saksId/brev.$brevId'
import { Route as SaksnummerSaksIdVedtakBrevIdRedigeringRouteImport } from './routes/saksnummer_/$saksId/vedtak.$brevId/redigering/route'
import { Route as SaksnummerSaksIdVedtakBrevIdKvitteringRouteImport } from './routes/saksnummer_/$saksId/vedtak.$brevId/kvittering/route'
import { Route as SaksnummerSaksIdVedtakBrevIdForhandsvisningRouteImport } from './routes/saksnummer_/$saksId/vedtak.$brevId/forhandsvisning/route'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SaksnummerIndexRoute = SaksnummerIndexImport.update({
  path: '/saksnummer/',
  getParentRoute: () => rootRoute,
} as any)

const SaksnummerSaksIdRouteRoute = SaksnummerSaksIdRouteImport.update({
  path: '/saksnummer/$saksId',
  getParentRoute: () => rootRoute,
} as any)

const SaksnummerSaksIdKvitteringRouteRoute =
  SaksnummerSaksIdKvitteringRouteImport.update({
    path: '/kvittering',
    getParentRoute: () => SaksnummerSaksIdRouteRoute,
  } as any)

const SaksnummerSaksIdBrevvelgerRouteRoute =
  SaksnummerSaksIdBrevvelgerRouteImport.update({
    path: '/brevvelger',
    getParentRoute: () => SaksnummerSaksIdRouteRoute,
  } as any)

const SaksnummerSaksIdBrevbehandlerRouteRoute =
  SaksnummerSaksIdBrevbehandlerRouteImport.update({
    path: '/brevbehandler',
    getParentRoute: () => SaksnummerSaksIdRouteRoute,
  } as any)

const SaksnummerSaksIdBrevBrevIdRoute = SaksnummerSaksIdBrevBrevIdImport.update(
  {
    path: '/brev/$brevId',
    getParentRoute: () => SaksnummerSaksIdRouteRoute,
  } as any,
)

const SaksnummerSaksIdVedtakBrevIdRedigeringRouteRoute =
  SaksnummerSaksIdVedtakBrevIdRedigeringRouteImport.update({
    path: '/vedtak/$brevId/redigering',
    getParentRoute: () => SaksnummerSaksIdRouteRoute,
  } as any)

const SaksnummerSaksIdVedtakBrevIdKvitteringRouteRoute =
  SaksnummerSaksIdVedtakBrevIdKvitteringRouteImport.update({
    path: '/vedtak/$brevId/kvittering',
    getParentRoute: () => SaksnummerSaksIdRouteRoute,
  } as any)

const SaksnummerSaksIdVedtakBrevIdForhandsvisningRouteRoute =
  SaksnummerSaksIdVedtakBrevIdForhandsvisningRouteImport.update({
    path: '/vedtak/$brevId/forhandsvisning',
    getParentRoute: () => SaksnummerSaksIdRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/saksnummer/$saksId': {
      preLoaderRoute: typeof SaksnummerSaksIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/saksnummer/': {
      preLoaderRoute: typeof SaksnummerIndexImport
      parentRoute: typeof rootRoute
    }
    '/saksnummer/$saksId/brevbehandler': {
      preLoaderRoute: typeof SaksnummerSaksIdBrevbehandlerRouteImport
      parentRoute: typeof SaksnummerSaksIdRouteImport
    }
    '/saksnummer/$saksId/brevvelger': {
      preLoaderRoute: typeof SaksnummerSaksIdBrevvelgerRouteImport
      parentRoute: typeof SaksnummerSaksIdRouteImport
    }
    '/saksnummer/$saksId/kvittering': {
      preLoaderRoute: typeof SaksnummerSaksIdKvitteringRouteImport
      parentRoute: typeof SaksnummerSaksIdRouteImport
    }
    '/saksnummer/$saksId/brev/$brevId': {
      preLoaderRoute: typeof SaksnummerSaksIdBrevBrevIdImport
      parentRoute: typeof SaksnummerSaksIdRouteImport
    }
    '/saksnummer/$saksId/vedtak/$brevId/forhandsvisning': {
      preLoaderRoute: typeof SaksnummerSaksIdVedtakBrevIdForhandsvisningRouteImport
      parentRoute: typeof SaksnummerSaksIdRouteImport
    }
    '/saksnummer/$saksId/vedtak/$brevId/kvittering': {
      preLoaderRoute: typeof SaksnummerSaksIdVedtakBrevIdKvitteringRouteImport
      parentRoute: typeof SaksnummerSaksIdRouteImport
    }
    '/saksnummer/$saksId/vedtak/$brevId/redigering': {
      preLoaderRoute: typeof SaksnummerSaksIdVedtakBrevIdRedigeringRouteImport
      parentRoute: typeof SaksnummerSaksIdRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SaksnummerSaksIdRouteRoute.addChildren([
    SaksnummerSaksIdBrevbehandlerRouteRoute,
    SaksnummerSaksIdBrevvelgerRouteRoute,
    SaksnummerSaksIdKvitteringRouteRoute,
    SaksnummerSaksIdBrevBrevIdRoute,
    SaksnummerSaksIdVedtakBrevIdForhandsvisningRouteRoute,
    SaksnummerSaksIdVedtakBrevIdKvitteringRouteRoute,
    SaksnummerSaksIdVedtakBrevIdRedigeringRouteRoute,
  ]),
  SaksnummerIndexRoute,
])

/* prettier-ignore-end */
