// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SaksnummerIndexImport } from './routes/saksnummer.index'
import { Route as SaksnummerSakIdImport } from './routes/saksnummer_.$sakId'
import { Route as SaksnummerSakIdBrevvelgerImport } from './routes/saksnummer_.$sakId.brevvelger'
import { Route as SaksnummerSakIdBrevvelgerTemplateIdImport } from './routes/saksnummer_.$sakId.brevvelger.$templateId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SaksnummerIndexRoute = SaksnummerIndexImport.update({
  path: '/saksnummer/',
  getParentRoute: () => rootRoute,
} as any)

const SaksnummerSakIdRoute = SaksnummerSakIdImport.update({
  path: '/saksnummer/$sakId',
  getParentRoute: () => rootRoute,
} as any)

const SaksnummerSakIdBrevvelgerRoute = SaksnummerSakIdBrevvelgerImport.update({
  path: '/brevvelger',
  getParentRoute: () => SaksnummerSakIdRoute,
} as any)

const SaksnummerSakIdBrevvelgerTemplateIdRoute =
  SaksnummerSakIdBrevvelgerTemplateIdImport.update({
    path: '/$templateId',
    getParentRoute: () => SaksnummerSakIdBrevvelgerRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/saksnummer/$sakId': {
      preLoaderRoute: typeof SaksnummerSakIdImport
      parentRoute: typeof rootRoute
    }
    '/saksnummer/': {
      preLoaderRoute: typeof SaksnummerIndexImport
      parentRoute: typeof rootRoute
    }
    '/saksnummer/$sakId/brevvelger': {
      preLoaderRoute: typeof SaksnummerSakIdBrevvelgerImport
      parentRoute: typeof SaksnummerSakIdImport
    }
    '/saksnummer/$sakId/brevvelger/$templateId': {
      preLoaderRoute: typeof SaksnummerSakIdBrevvelgerTemplateIdImport
      parentRoute: typeof SaksnummerSakIdBrevvelgerImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SaksnummerSakIdRoute.addChildren([
    SaksnummerSakIdBrevvelgerRoute.addChildren([
      SaksnummerSakIdBrevvelgerTemplateIdRoute,
    ]),
  ]),
  SaksnummerIndexRoute,
])
