// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SaksnummerImport } from './routes/saksnummer'
import { Route as BrevvelgerImport } from './routes/brevvelger'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SaksnummerRoute = SaksnummerImport.update({
  path: '/saksnummer',
  getParentRoute: () => rootRoute,
} as any)

const BrevvelgerRoute = BrevvelgerImport.update({
  path: '/brevvelger',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/brevvelger': {
      preLoaderRoute: typeof BrevvelgerImport
      parentRoute: typeof rootRoute
    }
    '/saksnummer': {
      preLoaderRoute: typeof SaksnummerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  BrevvelgerRoute,
  SaksnummerRoute,
])
