#file: noinspection KubernetesUnknownValues
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{app-name}}
  namespace: pensjonsbrev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{app-name}}
  minReplicas: 1
  maxReplicas: {{maxReplicas}}
  metrics:
    - type: External
      external:
        metric:
          name: kafka_consumergroup_group_lag
          selector:
            matchLabels:
              group: {{kafka.consumer-group-id}}
        target:
          type: AverageValue
          averageValue: "50"