apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: pdf-bygger-render
  namespace: pensjonsbrev
  labels:
    team: pensjonsbrev
spec:
  pool: nav-dev
  acl:
    - team: pensjonsbrev
      application: pensjon-brevbaker
      access: write
    - team: pensjonsbrev
      application: pensjon-pdf-bygger-async
      access: read
  config:
    partitions: 100
    cleanupPolicy: "delete"
    retentionBytes: -1
    retentionHours: 336 # 2 uker for å agere på feil.