// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningnokkelinfo.beregningnokkelinfo2.opt

data class Opt(
    val sluttpoengtallmedok: Double?,
    val sluttpoengtallmedokeos: Double?,
    val sluttpoengtallmedoknordisk: Double?
)
