// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.trygdeavtaler

data class Trygdeavtaler(
    val avtaleland: String?,
    val avtaletype: String?,
    val bostedslandbeskrivelse: String?
)
