// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningperiode.beregningytelsekomp.fasteutgifter

import no.nav.pensjon.brevbaker.api.model.BrevbakerType.Kroner

data class Fasteutgifter(
    val fasteutgifterbrutto: Kroner?,
    val fasteutgifterinnvilget: Boolean?,
    val fasteutgifternetto: Kroner?
)
