// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagslisteavdod.ttutlandtrygdeavtale

data class Ttutlandtrygdeavtale(
    val fattbilateral: Int?,
    val framtidigttavtaleland: Int?,
    val ttnevnerbilateral: Int?,
    val tttellerbilateral: Int?
)
