@file:Suppress("FunctionName")

package no.nav.pensjon.brev.maler.legacy

import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.PEgruppe10
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.selectors.pEgruppe10.exstreamFunctions.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.selectors.pEgruppe10.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.selectors.grunnlag.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.selectors.persongrunnlagAvdod.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.selectors.persongrunnlag.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.selectors.trygdeavtaler.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.instopphfasteutgifterperiode.selectors.instOpphFasteUtgifterPeriodeListe.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.instopphfasteutgifterperiode.selectors.instOpphFasteUtgifterPeriode.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.instopphreduksjonsperiode.selectors.instOpphReduksjonsPeriodeListe.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.instopphreduksjonsperiode.selectors.instOpphReduksjonsPeriode.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.trygdetidsgrunnlagbilateral.TrygdetidsgrunnlagBilateral
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.trygdetidsgrunnlagbilateral.selectors.trygdetidsgrunnlagBilateral.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.trygdetidsgrunnlagbilateral.selectors.trygdetidsgrunnlagListeBilateral.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.trygdetidsgrunnlageos.TrygdetidsgrunnlagEOS
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.trygdetidsgrunnlageos.selectors.trygdetidsgrunnlagEOS.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.trygdetidsgrunnlageos.selectors.trygdetidsgrunnlagListeEOS.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.trygdetidsgrunnlagnorge.Trygdetidsgrunnlag
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.trygdetidsgrunnlagnorge.selectors.trygdetidsgrunnlagListeNor.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.trygdetidsgrunnlagnorge.selectors.trygdetidsgrunnlag.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.uforetrygdetteroppgjor.selectors.fratrekkListe.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.uforetrygdetteroppgjor.selectors.inntektListe.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.uforetrygdetteroppgjor.Inntektsgrunnlag
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.uforetrygdetteroppgjor.selectors.uforetrygdEtteroppgjorDetaljBruker.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.uforetrygdetteroppgjor.selectors.uforetrygdEtteroppgjorDetaljEPS.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.grunnlag.uforetrygdetteroppgjor.selectors.uforetrygdEtteroppgjor.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.selectors.vedtaksbrev.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.selectors.vedtaksdata.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.selectors.beregningsData.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.selectors.barnetilleggFellesYK.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.selectors.barnetilleggSerkullYK.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.selectors.belopsendring.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.selectors.beregningUfore.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.selectors.minsteytelse.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.selectors.reduksjonsgrunnlag.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.selectors.uforetrygdOrdinerYK.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.beregningytelseskomp.selectors.avkortningsInformasjonBT.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.beregningytelseskomp.selectors.avkortningsInformasjon.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.beregningytelseskomp.selectors.barnetilleggFelles.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.beregningytelseskomp.selectors.barnetilleggSerkull.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.beregningytelseskomp.selectors.beregningYtelsesKomp.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.beregningytelseskomp.selectors.beregningsgrunnlagOrdinar.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.beregningytelseskomp.selectors.ektefelletillegg.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.beregningytelseskomp.selectors.gjenlevendetilleggInformasjon.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.beregningytelseskomp.selectors.gjenlevendetillegg.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.beregningytelseskomp.OpptjeningUT
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.beregningytelseskomp.selectors.opptjeningUT.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.beregningytelseskomp.selectors.uforetrygdOrdiner.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.beregningytelseskomp.selectors.ytelsesgrunnlag.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.beregningytelseskomp.beregningsgrunnlagavdodordiner.selectors.beregningsgrunnlagAvdodOrdiner.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregningufore.uforetrygdberegning.selectors.uforetrygdberegning.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.beregningsdata.beregninguforeperiode.selectors.beregningUforePeriode.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.etteroppgjorresultat.selectors.etteroppgjoerresultat.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.forrigeetteroppgjor.selectors.eoEndringBruker.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.forrigeetteroppgjor.selectors.eoEndringEps.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.forrigeetteroppgjor.selectors.forrigeEtteroppgjor.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.kravhode.selectors.kravhode.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.kravhode.selectors.kravlinje.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.trygdetidavdod.selectors.tTutlandTrygdeavtale.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.trygdetidavdod.selectors.trygdetidAvdod.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.vilkarsvedtaklist.selectors.vilkarsVedtakList.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.vilkarsvedtaklist.vilkarsvedtak.selectors.fortsattMedlemskap.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.vilkarsvedtaklist.vilkarsvedtak.selectors.forutgaendeMedlemskap.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.vilkarsvedtaklist.vilkarsvedtak.selectors.medlemskapForUTetterTrygdeavtaler.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.vilkarsvedtaklist.vilkarsvedtak.selectors.vilkar.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.vilkarsvedtaklist.vilkarsvedtak.selectors.vilkarsVedtak.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.vilkarsvedtaklist.vilkarsvedtak.beregningsvilkar.selectors.beregningsVilkar.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.vilkarsvedtaklist.vilkarsvedtak.beregningsvilkar.selectors.trygdetid.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.vilkarsvedtaklist.vilkarsvedtak.beregningsvilkar.ttutlandtrygdeavtaleliste.selectors.tTUtlandTrygdeAvtaleListe.*
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe10.vedtaksbrev.vedtaksdata.vilkarsvedtaklist.vilkarsvedtak.beregningsvilkar.ttutlandtrygdeavtaleliste.selectors.tTUtlandTrygdeAvtale.*
import no.nav.pensjon.brev.template.Expression
import no.nav.pensjon.brev.template.dsl.expression.*
import no.nav.pensjon.brevbaker.api.model.BrevbakerType.Kroner
import java.time.LocalDate
import java.time.Month


fun Expression<PEgruppe10>.avdodHarOpptjeningUTMedFoerstegangstjenesteOgIkkeOmsorg(): Expression<Boolean> = functions.avdodHarOpptjeningUTMedFoerstegangstjenesteOgIkkeOmsorg
fun Expression<PEgruppe10>.avdodHarOpptjeningUTMedFoerstegangstjenesteOgOmsorg(): Expression<Boolean> = functions.avdodHarOpptjeningUTMedFoerstegangstjenesteOgOmsorg
fun Expression<PEgruppe10>.avdodHarOpptjeningUTMedOmsorgOgIkkeFoerstegangstjeneste(): Expression<Boolean> = functions.avdodHarOpptjeningUTMedOmsorgOgIkkeFoerstegangstjeneste
fun Expression<PEgruppe10>.avdod_fremtidig_trygdetid_under_40_aar(): Expression<Boolean> = vedtaksdata_trygdetidavdod_framtidigttnorsk().lessThan(480)
fun Expression<PEgruppe10>.barnetilleggfelles_justeringsbelopperarutenminus(): Expression<Kroner> = vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggfelles_avkortningsinformasjon_justeringsbelopperar_utenminus()
fun Expression<PEgruppe10>.barnetilleggserkull_justeringsbelopperarutenminus(): Expression<Kroner> = vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggserkull_avkortningsinformasjon_justeringsbelopperar_utenminus()
fun Expression<PEgruppe10>.grunnlag_persongrunnlagavdod_brukerflyktning(): Expression<Boolean> = vedtaksbrev.safe{ grunnlag }.safe{ persongrunnlagavdod }.getOrNull().safe{ brukerflyktning }.ifNull(false)
fun Expression<PEgruppe10>.grunnlag_persongrunnlagavdod_fodselsnummer(): Expression<String> = vedtaksbrev.safe{ grunnlag }.safe{ persongrunnlagavdod }.getOrNull().safe{ fodselsnummer }.ifNull("")
fun Expression<PEgruppe10>.grunnlag_persongrunnlagavdod_trygdetidsgrunnlageos_trygdetidsgrunnlageos(): Expression<List<TrygdetidsgrunnlagEOS>> = vedtaksbrev.safe{ grunnlag }.safe { persongrunnlagavdod }.getOrNull().safe{ trygdetidsgrunnlaglisteeos }.safe{ trygdetidsgrunnlageos }.ifNull(emptyList())
fun Expression<PEgruppe10>.grunnlag_persongrunnlagavdod_trygdetidsgrunnlaglistebilateral_trygdetidsgrunnlagbilateral(): Expression<List<TrygdetidsgrunnlagBilateral>> = vedtaksbrev.safe{ grunnlag }.safe{ persongrunnlagavdod }.getOrNull().safe{ trygdetidsgrunnlaglistebilateral }.safe{ trygdetidsgrunnlagbilateral }.ifNull(emptyList())
fun Expression<PEgruppe10>.grunnlag_persongrunnlagavdod_trygdetidsgrunnlaglistebilateral_trygdetidsgrunnlagbilateral_trygdetidfombilateral(): Expression<LocalDate?> = vedtaksbrev.safe{ grunnlag }.safe{ persongrunnlagavdod }.getOrNull().safe{ trygdetidsgrunnlaglistebilateral }.safe{ trygdetidsgrunnlagbilateral }.getOrNull().safe{ trygdetidfombilateral }
fun Expression<PEgruppe10>.grunnlag_persongrunnlagavdod_trygdetidsgrunnlaglistenor_trygdetidsgrunnlag(): Expression<List<Trygdetidsgrunnlag>> = vedtaksbrev.safe { grunnlag }.safe{ persongrunnlagavdod }.getOrNull().safe{ trygdetidsgrunnlaglistenor }.safe{ trygdetidsgrunnlag }.ifNull(emptyList())
fun Expression<PEgruppe10>.grunnlag_persongrunnlagavdod_trygdetidsgrunnlaglistenor_trygdetidsgrunnlag_trygdetidfom(): Expression<LocalDate?> = vedtaksbrev.safe{ grunnlag }.safe{ persongrunnlagavdod }.getOrNull().safe{ trygdetidsgrunnlaglistenor }.safe{ trygdetidsgrunnlag} .getOrNull().safe{ trygdetidfom }
fun Expression<PEgruppe10>.grunnlag_persongrunnlagsliste_personbostedsland(): Expression<String> = vedtaksbrev.safe { grunnlag }.safe{ persongrunnlagsliste }.getOrNull().safe{ personbostedsland }.ifNull("")
fun Expression<PEgruppe10>.grunnlag_persongrunnlagsliste_trygdeavtaler_avtaleland(): Expression<String> = vedtaksbrev.safe { grunnlag }.safe{ persongrunnlagsliste }.getOrNull().safe{ trygdeavtaler }.safe{ avtaleland }.ifNull("")
fun Expression<PEgruppe10>.grunnlag_persongrunnlagsliste_trygdeavtaler_avtaletype(): Expression<String> = vedtaksbrev.safe { grunnlag }.safe{ persongrunnlagsliste }.getOrNull().safe{ trygdeavtaler }.safe{ avtaletype }.ifNull("")
fun Expression<PEgruppe10>.grunnlag_persongrunnlagsliste_trygdetidsgrunnlaglistebilateral_trygdetidsgrunnlagbilateral_trygdetidfombilateral(): Expression<LocalDate?> = vedtaksbrev.safe { grunnlag }.safe{ persongrunnlagsliste }.getOrNull().safe{ trygdetidsgrunnlaglistebilateral }.safe{ trygdetidsgrunnlagbilateral }.getOrNull().safe{ trygdetidfombilateral }
fun Expression<PEgruppe10>.grunnlag_persongrunnlagsliste_trygdetidsgrunnlaglistebilateral_trygdetidsgrunnlagbilateral_trygdetidtombilateral(): Expression<LocalDate?> = vedtaksbrev.safe { grunnlag }.safe{ persongrunnlagsliste }.getOrNull().safe{ trygdetidsgrunnlaglistebilateral }.safe{ trygdetidsgrunnlagbilateral }.getOrNull().safe{ trygdetidtombilateral }
fun Expression<PEgruppe10>.grunnlag_persongrunnlagsliste_trygdetidsgrunnlaglistenor_trygdetidsgrunnlag_trygdetidfom(): Expression<LocalDate?> = vedtaksbrev.safe { grunnlag }.safe{ persongrunnlagsliste }.getOrNull().safe{ trygdetidsgrunnlaglistenor }.safe{ trygdetidsgrunnlag }.getOrNull().safe{ trygdetidfom }
fun Expression<PEgruppe10>.grunnlag_persongrunnlagsliste_trygdetidsgrunnlaglistenor_trygdetidsgrunnlag_trygdetidtom(): Expression<LocalDate?> = vedtaksbrev.safe { grunnlag }.safe{ persongrunnlagsliste }.getOrNull().safe{ trygdetidsgrunnlaglistenor }.safe{ trygdetidsgrunnlag }.getOrNull().safe{ trygdetidtom }
fun Expression<PEgruppe10>.grunnlag_persongrunnlagsliste_uforehistorikkgarantigrad(): Expression<Int> = vedtaksbrev.safe {grunnlag}.safe {persongrunnlagsliste}.getOrNull().safe {uforehistorikkgarantigrad}.ifNull(0)
fun Expression<PEgruppe10>.harOpptjeningUTMedFoerstegangstjenesteOgIkkeOmsorg(): Expression<Boolean> = functions.harOpptjeningUTMedFoerstegangstjenesteOgIkkeOmsorg
fun Expression<PEgruppe10>.harOpptjeningUTMedFoerstegangstjenesteOgOmsorg(): Expression<Boolean> = functions.harOpptjeningUTMedFoerstegangstjenesteOgOmsorg
fun Expression<PEgruppe10>.harOpptjeningUTMedOmsorg(): Expression<Boolean> = functions.harOpptjeningUTMedOmsorg
fun Expression<PEgruppe10>.harOpptjeningUTMedOpptjeningBruktAaretFoerOgFoerstegangstjeneste(): Expression<Boolean> = functions.harOpptjeningUTMedOpptjeningBruktAaretFoerOgFoerstegangstjeneste
fun Expression<PEgruppe10>.harOpptjeningUTMedOmsorgOgIkkeFoerstegangstjeneste(): Expression<Boolean> = functions.harOpptjeningUTMedOmsorgOgIkkeFoerstegangstjeneste
fun Expression<PEgruppe10>.nettoakk_pluss_nettorestar(): Expression<Kroner> = functions.pe_ut_nettoakk_pluss_nettorestar
fun Expression<PEgruppe10>.pebrevkode(): Expression<String> = pebrevkode.ifNull("")
fun Expression<PEgruppe10>.sivilstand_ektefelle_partner_samboer_bormed_ut(): Expression<String> = functions.pe_sivilstand_ektefelle_partner_samboer_bormed_ut.ifNull("")
fun Expression<PEgruppe10>.sivilstand_ektefelle_partner_samboer_bormed_ut_en(): Expression<String> = functions.pe_sivilstand_ektefelle_partner_samboer_bormed_ut_en.ifNull("")
fun Expression<PEgruppe10>.sivilstand_ektefelle_partner_samboer_bormed_ut_en_cohabiting_partner(): Expression<String> = functions.pe_sivilstand_ektefelle_partner_samboer_bormed_ut_en_cohabiting_partner.ifNull("")
fun Expression<PEgruppe10>.sivilstand_ektefelle_partner_samboer_bormed_ut_nn_entall(): Expression<String> = functions.pe_sivilstand_ektefelle_partner_samboer_bormed_ut_nn_entall.ifNull("")
fun Expression<PEgruppe10>.sivilstand_ektefelle_partner_samboer_bormed_ut_alle_spraak_entall(): Expression<String> = functions.pe_sivilstand_ektefelle_partner_samboer_bormed_ut_alle_spraak_entall.ifNull("")
fun Expression<PEgruppe10>.ut_antallbarnserkullogfelles(): Expression<Int> = functions.pe_ut_antallbarnserkullogfelles
fun Expression<PEgruppe10>.ut_avviksbeloptfbutenminus(): Expression<Kroner> = vedtaksbrev_vedtaksdata_etteroppgjorresultat_avviksbeloptfb().absoluteValue()
fun Expression<PEgruppe10>.ut_avviksbeloptsbutenminus(): Expression<Kroner> = vedtaksbrev_vedtaksdata_etteroppgjorresultat_avviksbeloptsb().absoluteValue()
fun Expression<PEgruppe10>.ut_avviksbeloputenminus(): Expression<Kroner> = vedtaksbrev_vedtaksdata_etteroppgjorresultat_avviksbelop()
fun Expression<PEgruppe10>.ut_avviksbelopututenminus(): Expression<Kroner> = vedtaksbrev_vedtaksdata_etteroppgjorresultat_avviksbelop().absoluteValue()
fun Expression<PEgruppe10>.ut_btfbinntektbruktiavkortningminusbtfbfribelop(): Expression<Kroner> = functions.pe_ut_btfbinntektbruktiavkortningminusbtfbfribelop.ifNull(Kroner(0))
fun Expression<PEgruppe10>.ut_btsbinntektbruktiavkortningminusbtsbfribelop(): Expression<Kroner> = functions.pe_ut_btsbinntektbruktiavkortningminusbtsbfribelop.ifNull(Kroner(0))
fun Expression<PEgruppe10>.ut_etteroppgjorfratrekklistebrukeretterbetaling() = functions.pe_ut_etteroppgjorfratrekklistebrukeretterbetaling
fun Expression<PEgruppe10>.ut_fattnorgeplusfatta10netto_avdod(): Expression<Int> = functions.pe_ut_fattnorgeplusfatta10netto_avdod
fun Expression<PEgruppe10>.ut_fattnorgeplusfattbilateral_avdod(): Expression<Int> = functions.pe_ut_fattnorgeplusfattbilateral_avdod.ifNull(0)
fun Expression<PEgruppe10>.ut_fattnorgeplusfatteos_avdod(): Expression<Int> = functions.pe_ut_fattnorgeplusfatteos_avdod
fun Expression<PEgruppe10>.ut_forstegangstjenesteikkenull(): Expression<Boolean> = functions.pe_ut_forstegangstjenesteikkenull
fun Expression<PEgruppe10>.ut_grunnikkereduksjon_lik_erstatning_innttap_ertstoppgj_finnes(): Expression<Boolean> = functions.pe_ut_grunnikkereduksjon_lik_erstatning_innttap_ertstoppgj_finnes
fun Expression<PEgruppe10>.ut_inntekt_trukket_fra_personinntekt(): Expression<Kroner> = functions.pe_ut_inntekt_trukket_fra_personinntekt
fun Expression<PEgruppe10>.ut_inntektsgrense_faktisk_minus_60000(): Expression<Kroner> = functions.pe_ut_inntektsgrense_faktisk_minus_60000
fun Expression<PEgruppe10>.ut_inntektslandtruehvorbruktlikfalse_avdod(): Expression<Boolean> = functions.pe_ut_inntektslandtruehvorbruktlikfalse_avdod
fun Expression<PEgruppe10>.ut_inntektslandtruehvorbruktliktrue_avdod(): Expression<Boolean> = functions.pe_ut_inntektslandtruehvorbruktliktrue_avdod
fun Expression<PEgruppe10>.ut_kravlinjekode_vedtakresultat_forekomst_bt_innv(): Expression<Int> = functions.pe_ut_kravlinjekode_vedtakresultat_forekomst_bt_innv.ifNull(0)
fun Expression<PEgruppe10>.ut_nettoakk_pluss_nettorestar(): Expression<Kroner> = functions.pe_ut_nettoakk_pluss_nettorestar
fun Expression<PEgruppe10>.ut_sisteopptjeningarlikuforetidspunkt(): Expression<Boolean> = functions.pe_ut_sisteopptjeningarlikuforetidspunkt
fun Expression<PEgruppe10>.ut_sum_fattnorge_fatt_a10_netto(): Expression<Int> = functions.pe_ut_sum_fattnorge_fatt_a10_netto
fun Expression<PEgruppe10>.ut_sum_fattnorge_fattbilateral(): Expression<Int> = functions.pe_ut_sum_fattnorge_fattbilateral
fun Expression<PEgruppe10>.ut_sum_fattnorge_fatteos(): Expression<Int> = functions.pe_ut_sum_fattnorge_fatteos
fun Expression<PEgruppe10>.ut_sum_fattnorge_framtidigttnorge_div_12(): Expression<Int> = functions.pe_ut_sum_fattnorge_framtidigttnorge_div_12
fun Expression<PEgruppe10>.ut_sum_fattnorge_framtidigttnorge_div_12_avdod(): Expression<Int> = functions.pe_ut_sum_fattnorge_framtidigttnorge_div_12_avdod
fun Expression<PEgruppe10>.ut_uforetrygdetteroppgjor_periodefom_year(): Expression<Int> = vedtaksbrev_grunnlag_persongrunnlagsliste_uforetrygdetteroppgjor_periodefom().ifNull(LocalDate.of(1000,1,1)).year
fun Expression<PEgruppe10>.ut_vilfylle67ivirkningfomar(): Expression<Boolean> = functions.pe_ut_vilfylle67ivirkningfomar
fun Expression<PEgruppe10>.ut_vilkargjelderpersonalder(): Expression<Int> = functions.pe_ut_vilkargjelderpersonalder
fun Expression<PEgruppe10>.ut_virkningfomar(): Expression<Int> = functions.pe_ut_virkningfomar
fun Expression<PEgruppe10>.ut_virkningstidpunktarminus1ar(): Expression<Int> = functions.pe_ut_virkningstidpunktarminus1ar
fun Expression<PEgruppe10>.ut_uforetidspunkt_foer_17(): Expression<Boolean> = functions.pe_uforetidspunkt_foer_17.ifNull(true)
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_uforetrygdetteroppgjor_barnetilleggfb(): Expression<Boolean> = vedtaksbrev.safe { grunnlag }.safe { persongrunnlagsliste }.getOrNull().safe { uforetrygdetteroppgjor }.safe { barnetilleggfb }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_uforetrygdetteroppgjor_barnetilleggsb(): Expression<Boolean> = vedtaksbrev.safe { grunnlag }.safe { persongrunnlagsliste }.getOrNull().safe { uforetrygdetteroppgjor }.safe { barnetilleggsb }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_uforetrygdetteroppgjor_periodefom(): Expression<LocalDate?> = vedtaksbrev.safe { grunnlag }.safe { persongrunnlagsliste }.getOrNull().safe { uforetrygdetteroppgjor }.safe { periodefom }
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_uforetrygdetteroppgjor_periodetom(): Expression<LocalDate?> = vedtaksbrev.safe { grunnlag }.safe { persongrunnlagsliste }.getOrNull().safe { uforetrygdetteroppgjor }.safe { periodetom }
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_uforetrygdetteroppgjor_uforetrygdetteroppgjordetaljbruker_fratrekkliste_inntektsgrunnlag(): Expression<List<Inntektsgrunnlag>> = vedtaksbrev.safe { grunnlag }.safe { persongrunnlagsliste }.getOrNull().safe { uforetrygdetteroppgjor }.safe { uforetrygdetteroppgjordetaljbruker }.safe { fratrekkliste }.safe { inntektsgrunnlag }.ifNull(emptyList())
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_uforetrygdetteroppgjor_uforetrygdetteroppgjordetaljbruker_fratrekkliste_inntektsgrunnlag_grunnikkereduksjon_har_erstatning_innttap_erstoppgj() = functions.fratrekkliste_inntektsgrunnlag_grunnikkereduksjon_har_erstatning_innttap_erstoppgj
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_uforetrygdetteroppgjor_uforetrygdetteroppgjordetaljbruker_fratrekkliste_inntektsgrunnlag_grunnikkereduksjon_har_etterslepsinnt_avslt_akt() = functions.fratrekkliste_inntektsgrunnlag_grunnikkereduksjon_har_etterslepsinnt_avslt_akt
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_uforetrygdetteroppgjor_uforetrygdetteroppgjordetaljbruker_inntektliste_inntektsgrunnlag(): Expression<List<Inntektsgrunnlag>> = vedtaksbrev.safe { grunnlag }.safe { persongrunnlagsliste }.getOrNull().safe { uforetrygdetteroppgjor }.safe { uforetrygdetteroppgjordetaljbruker }.safe { inntektliste }.safe { inntektsgrunnlag }.ifNull(emptyList())
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_uforetrygdetteroppgjor_uforetrygdetteroppgjordetaljbruker_sumfratrekkbt(): Expression<Kroner> = vedtaksbrev.safe { grunnlag }.safe { persongrunnlagsliste }.getOrNull().safe { uforetrygdetteroppgjor }.safe { uforetrygdetteroppgjordetaljbruker }.safe { sumfratrekkbt }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_uforetrygdetteroppgjor_uforetrygdetteroppgjordetaljbruker_sumfratrekkut(): Expression<Kroner> = vedtaksbrev.safe { grunnlag }.safe { persongrunnlagsliste }.getOrNull().safe { uforetrygdetteroppgjor }.safe { uforetrygdetteroppgjordetaljbruker }.safe { sumfratrekkut }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_uforetrygdetteroppgjor_uforetrygdetteroppgjordetaljbruker_suminntekterbt(): Expression<Kroner> = vedtaksbrev.safe { grunnlag }.safe { persongrunnlagsliste }.getOrNull().safe { uforetrygdetteroppgjor }.safe { uforetrygdetteroppgjordetaljbruker }.safe { suminntekterbt }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_uforetrygdetteroppgjor_uforetrygdetteroppgjordetaljbruker_suminntekterut(): Expression<Kroner> = vedtaksbrev.safe { grunnlag }.safe { persongrunnlagsliste }.getOrNull().safe { uforetrygdetteroppgjor }.safe { uforetrygdetteroppgjordetaljbruker }.safe { suminntekterut }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_uforetrygdetteroppgjor_uforetrygdetteroppgjordetaljeps_fratrekkliste_inntektsgrunnlag() = vedtaksbrev.safe { grunnlag }.safe { persongrunnlagsliste }.getOrNull().safe { uforetrygdetteroppgjor }.safe { uforetrygdetteroppgjordetaljeps }.safe { fratrekkListe }.safe { inntektsgrunnlag }.ifNull(emptyList())
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_uforetrygdetteroppgjor_uforetrygdetteroppgjordetaljeps_inntektliste_inntektsgrunnlag() = vedtaksbrev.safe { grunnlag }.safe { persongrunnlagsliste }.getOrNull().safe { uforetrygdetteroppgjor }.safe { uforetrygdetteroppgjordetaljeps }.safe { inntektliste }.safe { inntektsgrunnlag }.ifNull(emptyList())
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_uforetrygdetteroppgjor_uforetrygdetteroppgjordetaljeps_sumfratrekkbt(): Expression<Kroner> = vedtaksbrev.safe { grunnlag }.safe { persongrunnlagsliste }.getOrNull().safe { uforetrygdetteroppgjor }.safe { uforetrygdetteroppgjordetaljeps }.safe { sumfratrekkbt }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_uforetrygdetteroppgjor_uforetrygdetteroppgjordetaljeps_suminntekterbt(): Expression<Kroner> = vedtaksbrev.safe { grunnlag }.safe { persongrunnlagsliste }.getOrNull().safe { uforetrygdetteroppgjor }.safe { uforetrygdetteroppgjordetaljeps }.safe { suminntekterbt }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggfelles_avkortningsinformasjon_avkortingsbelopperar(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { avkortningsinformasjon }.safe { avkortingsbelopperar }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggfelles_avkortningsinformasjon_fribelopperiodisert(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { avkortningsinformasjon }.safe { fribelopperiodisert }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggfelles_avkortningsinformasjon_inntektperiodisert(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { avkortningsinformasjon }.safe { inntektperiodisert }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggfelles_avkortningsinformasjon_inntektstak(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { avkortningsinformasjon }.safe { inntektstak }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggfelles_avkortningsinformasjon_justeringsbelopperar(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { avkortningsinformasjon }.safe { justeringsbelopperar }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggfelles_avkortningsinformasjon_justeringsbelopperar_utenminus(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { avkortningsinformasjon }.safe { justeringsbelopperar }.ifNull(Kroner(0)).absoluteValue()
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggfelles_btfbbelopfratrukketannenforeldersinntekt(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { btfbbelopfratrukketannenforeldersinntekt }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggfelles_btfbinntektannenforelder(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { btfbinntektannenforelder }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggserkull_avkortningsinformasjon_avkortingsbelopperar(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggserkull }.safe { avkortningsinformasjon }.safe { avkortingsbelopperar }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggserkull_avkortningsinformasjon_fribelopperiodisert(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggserkull }.safe { avkortningsinformasjon }.safe { fribelopperiodisert }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggserkull_avkortningsinformasjon_inntektperiodisert(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggserkull }.safe { avkortningsinformasjon }.safe { inntektperiodisert }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggserkull_avkortningsinformasjon_inntektstak(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggserkull }.safe { avkortningsinformasjon }.safe { inntektstak }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggserkull_avkortningsinformasjon_justeringsbelopperar(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggserkull }.safe { avkortningsinformasjon }.safe { justeringsbelopperar }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggserkull_avkortningsinformasjon_justeringsbelopperar_utenminus(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggserkull }.safe { avkortningsinformasjon }.safe { justeringsbelopperar }.ifNull(Kroner(0)).absoluteValue()
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_reduksjonsgrunnlag_barnetilleggregelverktype(): Expression<String> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { reduksjonsgrunnlag }.safe { barnetilleggregelverktype }.ifNull("")
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_reduksjonsgrunnlag_gradertoppjustertifu(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { reduksjonsgrunnlag }.safe { gradertoppjustertifu }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_reduksjonsgrunnlag_prosentsatsoifufortak(): Expression<Int> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { reduksjonsgrunnlag }.safe { prosentsatsoifufortak }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_reduksjonsgrunnlag_sumbruttoetterreduksjonbt(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { reduksjonsgrunnlag }.safe { sumbruttoetterreduksjonbt }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_reduksjonsgrunnlag_sumbruttoforreduksjonbt(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { reduksjonsgrunnlag }.safe { sumbruttoforreduksjonbt }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_uforetrygdberegning_instopphanvendt(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { uforetrygdberegning }.safe { instopphanvendt }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_beregningsdata_beregningufore_uforetrygdberegning_instoppholdtype(): Expression<String> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { uforetrygdberegning }.safe { instoppholdtype }.ifNull("")
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_etteroppgjorresultat_avviksbelop(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { etteroppgjorresultat }.safe { avviksbelop }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_etteroppgjorresultat_avviksbeloptfb(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { etteroppgjorresultat }.safe { avviksbeloptfb }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_etteroppgjorresultat_avviksbeloptsb(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { etteroppgjorresultat }.safe { avviksbeloptsb }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_etteroppgjorresultat_avviksbeloput(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { etteroppgjorresultat }.safe { avviksbeloput }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_etteroppgjorresultat_etteroppgjorresultattype(): Expression<String> = vedtaksbrev.safe { vedtaksdata }.safe { etteroppgjorresultat }.safe { etteroppgjorresultattype }.ifNull("")
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_etteroppgjorresultat_inntektut(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { etteroppgjorresultat }.safe { inntektut }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_etteroppgjorresultat_tidligerebeloptfb(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { etteroppgjorresultat }.safe { tidligerebeloptfb }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_etteroppgjorresultat_tidligerebeloptsb(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { etteroppgjorresultat }.safe { tidligerebeloptsb }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_etteroppgjorresultat_tidligerebeloput(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { etteroppgjorresultat }.safe { tidligerebeloput }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_etteroppgjorresultat_totalbeloptfb(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { etteroppgjorresultat }.safe { totalbeloptfb }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_etteroppgjorresultat_totalbeloptsb(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { etteroppgjorresultat }.safe { totalbeloptsb }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_etteroppgjorresultat_totalbeloput(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { etteroppgjorresultat }.safe { totalbeloput }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_forrigeetteroppgjor_eoendringbruker_endretpensjonogandreytelser(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { forrigeetteroppgjor }.safe { eoendringbruker }.safe { endretpensjonogandreytelser }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_forrigeetteroppgjor_eoendringbruker_endretpensjonogandreytelser_new(): Expression<Boolean> = vedtaksbrev_vedtaksdata_forrigeetteroppgjor_eoendringbruker_endretpensjonogandreytelser()
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_forrigeetteroppgjor_eoendringbruker_endretpgi(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { forrigeetteroppgjor }.safe { eoendringbruker }.safe { endretpgi }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_forrigeetteroppgjor_eoendringbruker_endretpgi_new(): Expression<Boolean> = vedtaksbrev_vedtaksdata_forrigeetteroppgjor_eoendringbruker_endretpgi()
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_forrigeetteroppgjor_eoendringeps_endretpensjonogandreytelser(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { forrigeetteroppgjor }.safe { eoendringeps }.safe { endretpensjonogandreytelser }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_forrigeetteroppgjor_eoendringeps_endretpensjonogandreytelser_new(): Expression<Boolean> = vedtaksbrev_vedtaksdata_forrigeetteroppgjor_eoendringeps_endretpensjonogandreytelser()
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_forrigeetteroppgjor_eoendringeps_endretpgi(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { forrigeetteroppgjor }.safe { eoendringeps }.safe { endretpgi }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_forrigeetteroppgjor_eoendringeps_endretpgi_new(): Expression<Boolean> = vedtaksbrev_vedtaksdata_forrigeetteroppgjor_eoendringeps_endretpgi()
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_forrigeetteroppgjor_resultatforrigeeo(): Expression<String> = vedtaksbrev.safe { vedtaksdata }.safe { forrigeetteroppgjor }.safe { resultatforrigeeo }.ifNull("")
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_forrigeetteroppgjor_resultatforrigeeo_new(): Expression<String> = vedtaksbrev_vedtaksdata_forrigeetteroppgjor_resultatforrigeeo()
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_forrigeetteroppgjor_tidligereeoiverksatt(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { forrigeetteroppgjor }.safe { tidligereeoiverksatt }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_forrigeetteroppgjor_tidligereeoiverksatt_new(): Expression<Boolean> = vedtaksbrev_vedtaksdata_forrigeetteroppgjor_tidligereeoiverksatt()
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_kravhode_brukerkonvertertup(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { kravhode }.safe { brukerkonvertertup }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_vilkarsvedtak_vilkar_medlemskapforutettertrygdeavtaler_oppfyltvedsammenlegging(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { vilkarsvedtaklist }.safe { vilkarsvedtak }.getOrNull().safe { vilkar }.safe { medlemskapforutettertrygdeavtaler }.safe { oppfyltvedsammenlegging }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_fortsattmedlemskap_inngangunntak(): Expression<String> = vedtaksbrev.safe { vedtaksdata }.safe { vilkarsvedtaklist }.safe { vilkarsvedtak }.getOrNull().safe { vilkar }.safe { fortsattmedlemskap }.safe { inngangunntak }.ifNull("")
fun Expression<PEgruppe10>.foedselsdatoTilBarnTilleggErInnvilgetFor(): Expression<List<LocalDate>> = functions.foedselsdatoTilBarnTilleggErInnvilgetFor
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregning_beregningbrukersivilstand(): Expression<String> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningbrukersivilstand }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregning_beregningsivilstandanvendt(): Expression<String> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningsivilstandanvendt }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregning_beregningbenyttetsivilstand(): Expression<String> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningbenyttetsivilstand }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregning_beregningytelsekomp_barnetilleggfelles_antallbarnfelles(): Expression<Int> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { antallbarnfelles }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregning_beregningytelsekomp_barnetilleggfelles_btfbbrutto(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { btfbbrutto }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregning_beregningytelsekomp_barnetilleggfelles_btfbfribelop(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { btfbfribelop }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregning_beregningytelsekomp_barnetilleggfelles_btfbinntektbruktiavkortning(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { btfbinntektbruktiavkortning }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregning_beregningytelsekomp_barnetilleggfelles_btfbinnvilget(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { btfbinnvilget }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregning_beregningytelsekomp_barnetilleggfelles_btfbnetto(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { btfbnetto }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregning_beregningytelsekomp_barnetilleggserkull_antallbarnserkull(): Expression<Int> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggserkull }.safe { antallbarnserkull }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregning_beregningytelsekomp_barnetilleggserkull_btsbbrutto(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggserkull }.safe { btsbbrutto }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregning_beregningytelsekomp_barnetilleggserkull_btsbfribelop(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggserkull }.safe { btsbfribelop }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregning_beregningytelsekomp_barnetilleggserkull_btsbinntektbruktiavkortning(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggserkull }.safe { btsbinntektbruktiavkortning }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregning_beregningytelsekomp_barnetilleggserkull_btsbinnvilget(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggserkull }.safe { btsbinnvilget }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregning_beregningytelsekomp_barnetilleggserkull_btsbnetto(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggserkull }.safe { btsbnetto }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregning_beregningytelsekomp_ektefelletillegg_etinnvilget(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { ektefelletillegg }.safe { etinnvilget }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregning_beregningytelsekomp_ektefelletillegg_etnetto(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { ektefelletillegg }.safe { etnetto }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_belopokt(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { belopokt }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_belopredusert(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { belopredusert }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_belopsendring_barnetilleggfellesyk_belopgammelbtfb(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { belopsendring }.safe { barnetilleggfellesyk }.safe { belopgammelbtfb }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_belopsendring_barnetilleggfellesyk_belopnybtfb(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { belopsendring }.safe { barnetilleggfellesyk }.safe { belopnybtfb }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_belopsendring_barnetilleggserkullyk_belopgammelbtsb(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { belopsendring }.safe { barnetilleggserkullyk }.safe { belopgammelbtsb }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_belopsendring_barnetilleggserkullyk_belopnybtsb(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { belopsendring }.safe { barnetilleggserkullyk }.safe { belopnybtsb }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_belopsendring_uforetrygdordineryk_belopgammelut(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { belopsendring }.safe { uforetrygdordineryk }.safe { belopgammelut }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_belopsendring_uforetrygdordineryk_belopnyut(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { belopsendring }.safe { uforetrygdordineryk }.safe { belopnyut }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningvirkningdatofom(): Expression<LocalDate?> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningvirkningdatofom }
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggfelles_btfbbrukersinntekttilavkortning(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { btfbbrukersinntekttilavkortning }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggfelles_btfbbruttoperar(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { btfbbruttoperar }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggfelles_btfbfradrag(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { btfbfradrag }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggfelles_btfbnettoperar(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggfelles }.safe { btfbnettoperar }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggserkull_btsbbruttoperar(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggserkull }.safe { btsbbruttoperar }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggserkull_btsbfradrag(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggserkull }.safe { btsbfradrag }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_barnetilleggserkull_btsbnettoperar(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { barnetilleggserkull }.safe { btsbnettoperar }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_gjenlevendetillegg_gjenlevendetillegginformasjon_anvendttrygdetid(): Expression<Int> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { gjenlevendetillegg }.safe { gjenlevendetillegginformasjon }.safe { anvendttrygdetid }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_gjenlevendetillegg_gjenlevendetillegginformasjon_beregningsgrunnlagavdodordiner_arsbelop(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { gjenlevendetillegg }.safe { gjenlevendetillegginformasjon }.safe { beregningsgrunnlagavdodordiner }.safe { arsbelop }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_gjenlevendetillegg_gjenlevendetillegginformasjon_beregningsgrunnlagavdodordiner_opptjeningutliste(): Expression<List<OpptjeningUT>> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { gjenlevendetillegg }.safe { gjenlevendetillegginformasjon }.safe { beregningsgrunnlagavdodordiner }.safe { opptjeningutliste }.ifNull(emptyList())
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_gjenlevendetillegg_gjenlevendetillegginformasjon_beregningsgrunnlagavdodordiner_opptjeningutliste_opptjeningut_ar(): Expression<Int> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { gjenlevendetillegg }.safe { gjenlevendetillegginformasjon }.safe { beregningsgrunnlagavdodordiner }.safe { opptjeningutliste }.getOrNull().safe { ar }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_gjenlevendetillegg_gjenlevendetillegginformasjon_beregningsgrunnlagavdodyrkesskadearsbelop(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { gjenlevendetillegg }.safe { gjenlevendetillegginformasjon }.safe { beregningsgrunnlagavdodyrkesskadearsbelop }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_gjenlevendetillegg_gjenlevendetillegginformasjon_inntektvedskadetidspunktet(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { gjenlevendetillegg }.safe { gjenlevendetillegginformasjon }.safe { inntektvedskadetidspunktet }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_gjenlevendetillegg_gjenlevendetillegginformasjon_minsteytelsebenyttetungufor(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { gjenlevendetillegg }.safe { gjenlevendetillegginformasjon }.safe { minsteytelsebenyttetungufor }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_gjenlevendetillegg_gjenlevendetillegginformasjon_uforetidspunkt(): Expression<LocalDate?> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { gjenlevendetillegg }.safe { gjenlevendetillegginformasjon }.safe { uforetidspunkt }
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_gjenlevendetillegg_gjenlevendetillegginformasjon_yrkesskadegrad(): Expression<Int> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { gjenlevendetillegg }.safe { gjenlevendetillegginformasjon }.safe { yrkesskadegrad }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_gjenlevendetillegg_gtinnvilget(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { gjenlevendetillegg }.safe { gtinnvilget }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_gjenlevendetillegg_gtnetto(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { gjenlevendetillegg }.safe { gtnetto }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_gjenlevendetillegg_nyttgjenlevendetillegg(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { gjenlevendetillegg }.safe { nyttgjenlevendetillegg }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_avkortingsbelopperar(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { uforetrygdordiner }.safe { avkortingsbelopperar }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_avkortningsinformasjon_belopsgrense(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { uforetrygdordiner }.safe { avkortningsinformasjon }.safe { belopsgrense }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_avkortningsinformasjon_forventetinntekt(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { uforetrygdordiner }.safe { avkortningsinformasjon }.safe { forventetinntekt }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_avkortningsinformasjon_inntektsgrense(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { uforetrygdordiner }.safe { avkortningsinformasjon }.safe { inntektsgrense }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_avkortningsinformasjon_inntektsgrensenestear(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { uforetrygdordiner }.safe { avkortningsinformasjon }.safe { inntektsgrensenestear }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_avkortningsinformasjon_inntektstak(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { uforetrygdordiner }.safe { avkortningsinformasjon }.safe { inntektstak }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_avkortningsinformasjon_kompensasjonsgrad(): Expression<Double> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { uforetrygdordiner }.safe { avkortningsinformasjon }.safe { kompensasjonsgrad }.ifNull(0.0)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_avkortningsinformasjon_oieu(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { uforetrygdordiner }.safe { avkortningsinformasjon }.safe { oieu }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_avkortningsinformasjon_oifu(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { uforetrygdordiner }.safe { avkortningsinformasjon }.safe { oifu }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_avkortningsinformasjon_oifu_x_08(): Expression<Kroner> = functions.pe_vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_avkortningsinformasjon_oifu_x_08
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_avkortningsinformasjon_ugradertbruttoperar(): Expression<Kroner> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ beregningytelseskomp }.safe{ uforetrygdordiner }.safe{ avkortningsinformasjon }.safe{ ugradertbruttoperar }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_avkortningsinformasjon_utbetalingsgrad(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ beregningytelseskomp }.safe{ uforetrygdordiner }.safe{ avkortningsinformasjon }.safe{ utbetalingsgrad }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_fradrag(): Expression<Kroner> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ beregningytelseskomp }.safe{ uforetrygdordiner }.safe{ fradrag }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_minsteytelse_oppfyltungufor(): Expression<Boolean> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ beregningytelseskomp }.safe{ uforetrygdordiner }.safe{ minsteytelse }.safe{ oppfyltungufor }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_minsteytelse_sats(): Expression<Double> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ beregningytelseskomp }.safe{ uforetrygdordiner }.safe{ minsteytelse }.safe{ sats }.ifNull(0.0)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_netto(): Expression<Kroner> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ beregningytelseskomp }.safe{ uforetrygdordiner }.safe{ netto }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_nettoakk(): Expression<Kroner> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ beregningytelseskomp }.safe{ uforetrygdordiner }.safe{ nettoakk }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_nettorestar(): Expression<Kroner> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ beregningytelseskomp }.safe{ uforetrygdordiner }.safe{ nettorestar }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_ytelsesgrunnlag_beregningsgrunnlagordinar_antallarinntektiavtaleland(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ beregningytelseskomp }.safe{ uforetrygdordiner }.safe{ ytelsesgrunnlag }.safe{ beregningsgrunnlagordinar }.safe{ antallarinntektiavtaleland }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_ytelsesgrunnlag_beregningsgrunnlagordinar_antallarover1g(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ beregningytelseskomp }.safe{ uforetrygdordiner }.safe{ ytelsesgrunnlag }.safe{ beregningsgrunnlagordinar }.safe{ antallarover1g }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_ytelsesgrunnlag_beregningsgrunnlagordinar_beregningsgrunnlagordinerarsbelop(): Expression<Kroner> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ beregningytelseskomp }.safe{ uforetrygdordiner }.safe{ ytelsesgrunnlag }.safe{ beregningsgrunnlagordinar }.safe{ beregningsgrunnlagordinerarsbelop }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_ytelsesgrunnlag_beregningsgrunnlagordinar_opptjeningutliste(): Expression<List<OpptjeningUT>> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ beregningytelseskomp }.safe{ uforetrygdordiner }.safe{ ytelsesgrunnlag }.safe{ beregningsgrunnlagordinar }.safe{ opptjeningutliste }.ifNull(emptyList())
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_ytelsesgrunnlag_beregningsgrunnlagordinar_opptjeningutliste_opptjeningut_forstegansgstjeneste(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ beregningytelseskomp }.safe{ uforetrygdordiner }.safe{ ytelsesgrunnlag }.safe{ beregningsgrunnlagordinar }.safe{ opptjeningutliste }.getOrNull().safe{ forstegansgstjeneste }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_ytelsesgrunnlag_beregningsgrunnlagordinar_opptjeningutliste_opptjeningut_omsorgsaar(): Expression<Boolean> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ beregningytelseskomp }.safe{ uforetrygdordiner }.safe{ ytelsesgrunnlag }.safe{ beregningsgrunnlagordinar }.safe{ opptjeningutliste }.getOrNull().safe{ omsorgsaar }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_ytelsesgrunnlag_beregningsgrunnlagyrkesskadearsbelop(): Expression<Kroner> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ beregningytelseskomp }.safe{ uforetrygdordiner }.safe{ ytelsesgrunnlag }.safe{ beregningsgrunnlagyrkesskadearsbelop }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_ytelsesgrunnlag_beregningsgrunnlagyrkesskadebest(): Expression<Boolean> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ beregningytelseskomp }.safe{ uforetrygdordiner }.safe{ ytelsesgrunnlag }.safe{ beregningsgrunnlagyrkesskadebest }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_ytelsesgrunnlag_inntektvedskadetidspunktet(): Expression<Kroner> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ beregningytelseskomp }.safe{ uforetrygdordiner }.safe{ ytelsesgrunnlag }.safe{ inntektvedskadetidspunktet }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_reduksjonsgrunnlag_andelytelseavoifu(): Expression<Double> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ reduksjonsgrunnlag }.safe{ andelytelseavoifu }.ifNull(0.0)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_reduksjonsgrunnlag_sumutbt(): Expression<Kroner> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ reduksjonsgrunnlag }.safe{ sumutbt }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_totalnetto(): Expression<Kroner> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ totalnetto }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_uforetrygdberegning_anvendttrygdetid(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ uforetrygdberegning }.safe{ anvendttrygdetid }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_uforetrygdberegning_beregningsmetode(): Expression<String> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ uforetrygdberegning }.safe{ beregningsmetode }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_uforetrygdberegning_grunnbelop(): Expression<Kroner> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ uforetrygdberegning }.safe{ grunnbelop }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_uforetrygdberegning_mottarminsteytelse(): Expression<Boolean> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ uforetrygdberegning }.safe{ mottarminsteytelse }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_uforetrygdberegning_proratabroknevner(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ uforetrygdberegning }.safe{ proratabroknevner }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_uforetrygdberegning_proratabrokteller(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ uforetrygdberegning }.safe{ proratabrokteller }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_uforetrygdberegning_uforegrad(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ uforetrygdberegning }.safe{ uforegrad }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_uforetrygdberegning_uforetidspunkt(): Expression<LocalDate?> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ uforetrygdberegning }.safe{ uforetidspunkt }
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_uforetrygdberegning_yrkesskadegrad(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ uforetrygdberegning }.safe{ yrkesskadegrad }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregninguforeperiode_uforetrygdberegning_uforegrad(): Expression<Int> = vedtaksbrev.vedtaksdata.safe{ beregningsdata }.safe{ beregninguforeperiode }.getOrNull().safe{ uforetrygdberegning }.safe{ uforegrad }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_faktoromregnet(): Expression<Boolean> = vedtaksbrev.safe{ vedtaksdata }.safe{ faktoromregnet }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_kravhode_boddarbeidutland(): Expression<Boolean> = vedtaksbrev.safe{ vedtaksdata }.safe{ kravhode }.safe{ boddarbeidutland }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_kravhode_boddarbeidutlandavdod(): Expression<Boolean> = vedtaksbrev.safe{ vedtaksdata }.safe{ kravhode }.safe{ boddarbeidutlandavdod }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_kravhode_kravarsaktype(): Expression<String> = vedtaksbrev.safe{ vedtaksdata }.safe{ kravhode }.safe{ kravarsaktype }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_kravhode_kravgjelder(): Expression<String> = vedtaksbrev.safe{ vedtaksdata }.safe{ kravhode }.safe{ kravgjelder }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_kravhode_kravlinjeliste_kravlinje_kravlinjetype(): Expression<String> = vedtaksbrev.vedtaksdata.safe{ kravhode }.safe{ kravlinjeliste }.getOrNull().safe{ kravlinjetype }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_kravhode_kravmottatdato(): Expression<LocalDate> = vedtaksbrev.vedtaksdata.safe{ kravhode }.safe{ kravmottattdato }.ifNull(LocalDate.now())
fun Expression<PEgruppe10>.vedtaksdata_kravhode_onsketvirkningsdato(): Expression<LocalDate?> = vedtaksbrev.safe{ vedtaksdata }.safe{ kravhode }.safe{ onsketvirkningsdato }
fun Expression<PEgruppe10>.vedtaksdata_kravhode_vurderetrygdeavtale(): Expression<Boolean> = vedtaksbrev.safe{ vedtaksdata }.safe{ kravhode }.safe{ vurderetrygdeavtale }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_trygdetidavdod_fatt_a10_netto(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ trygdetidavdod }.safe{ fatta10netto }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_trygdetidavdod_fatteos(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ trygdetidavdod }.safe{ fatteos }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_trygdetidavdod_fattnorge(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ trygdetidavdod }.safe{ fattnorge }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_trygdetidavdod_framtidigtteos(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ trygdetidavdod }.safe{ framtidigtteos }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_trygdetidavdod_framtidigttnorsk(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ trygdetidavdod }.safe{ framtidigttnorsk }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_trygdetidavdod_ttnevnereos(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ trygdetidavdod }.safe{ ttnevnereos }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_trygdetidavdod_ttnevnernordisk(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ trygdetidavdod }.safe{ ttnevnernordisk }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_trygdetidavdod_ttnordisk(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ trygdetidavdod }.safe{ ttnordisk }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_trygdetidavdod_tttellereos(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ trygdetidavdod }.safe{ tttellereos }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_trygdetidavdod_tttellernordisk(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ trygdetidavdod }.safe{ tttellernordisk }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_trygdetidavdod_ttutlandtrygdeavtale_fattbilateral(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ trygdetidavdod }.safe{ ttutlandtrygdeavtale }.safe{ fattbilateral }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_trygdetidavdod_ttutlandtrygdeavtale_framtidigttavtaleland(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ trygdetidavdod }.safe{ ttutlandtrygdeavtale }.safe{ framtidigttavtaleland }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_trygdetidavdod_ttutlandtrygdeavtale_ttnevnerbilateral(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ trygdetidavdod }.safe{ ttutlandtrygdeavtale }.safe{ ttnevnerbilateral }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_trygdetidavdod_ttutlandtrygdeavtale_tttellerbilateral(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ trygdetidavdod }.safe{ ttutlandtrygdeavtale }.safe{ tttellerbilateral }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_ieubegrunnelse(): Expression<String> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ ieubegrunnelse }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_ieuinntekt(): Expression<Kroner> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ ieuinntekt }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_ifubegrunnelse(): Expression<String> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ ifubegrunnelse }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_ifuinntekt(): Expression<Kroner> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ ifuinntekt }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_skadetidspunkt(): Expression<LocalDate?> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ skadetidspunkt }
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_trygdetid_fatteos(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ trygdetid }.safe{ fatteos }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_trygdetid_fattnorge(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ trygdetid }.safe{ fattnorge }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_trygdetid_framtidigtteos(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ trygdetid }.safe{ framtidigtteos }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_trygdetid_framtidigttnorsk(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ trygdetid }.safe{ framtidigttnorsk }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_trygdetid_redusertframtidigtrygdetid(): Expression<Boolean> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ trygdetid }.safe{ redusertframtidigtrygdetid }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_trygdetid_ttnevnereos(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ trygdetid }.safe{ ttnevnereos }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_trygdetid_ttnevnernordisk(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ trygdetid }.safe{ ttnevnernordisk }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_trygdetid_ttnordisk(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ trygdetid }.safe{ ttnordisk }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_trygdetid_tttellereos(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ trygdetid }.safe{ tttellereos }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_trygdetid_tttellernordisk(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ trygdetid }.safe{ tttellernordisk }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_ttutlandtrygdeavtaleliste_ttutlandtrygdeavtale_fattbilateral(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ trygdetid }.safe{ ttutlandtrygdeavtaleliste }.safe{ ttutlandtrygdeavtale }.getOrNull().safe{ fattbilateral }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_uforegrad(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ uforegrad }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_uforetidspunkt(): Expression<LocalDate?> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ uforetidspunkt }
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_virkningstidpunkt(): Expression<LocalDate?> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ virkningstidpunkt }
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_yrkesskadegrad(): Expression<Int> = vedtaksbrev.vedtaksdata.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ yrkesskadegrad }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_ivsbegrunnelse(): Expression<String> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ ivsbegrunnelse }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_ivsinntekt(): Expression<Kroner> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ ivsinntekt }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_alderbegrunnelse(): Expression<String> = vedtaksbrev.vedtaksdata.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ alderbegrunnelse }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_alderresultat(): Expression<String> = vedtaksbrev.vedtaksdata.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ alderresultat }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_fortsattmedlemsskapresultat(): Expression<String> = vedtaksbrev.vedtaksdata.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ fortsattmedlemsskapresultat }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_forutgaendemedlemskapresultat(): Expression<String> = vedtaksbrev.vedtaksdata.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ forutgaendemedlemskapresultat }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_hensiktsmessigarbeidsrettedetiltakbegrunnelse(): Expression<String> = vedtaksbrev.vedtaksdata.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ hensiktsmessigarbeidsrettedetiltakbegrunnelse }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_hensiktsmessigarbeidsrettedetiltakresultat(): Expression<String> = vedtaksbrev.vedtaksdata.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ hensiktsmessigarbeidsrettedetiltakresultat }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_hensiktsmessigbehandlingbegrunnelse(): Expression<String> = vedtaksbrev.vedtaksdata.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ hensiktsmessigbehandlingbegrunnelse }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_hensiktsmessigbehandlingresultat(): Expression<String> = vedtaksbrev.vedtaksdata.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ hensiktsmessigbehandlingresultat }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_nedsattinntektsevnebegrunnelse(): Expression<String> = vedtaksbrev.vedtaksdata.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ nedsattinntektsevnebegrunnelse }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_nedsattinntektsevneresultat(): Expression<String> = vedtaksbrev.vedtaksdata.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ nedsattinntektsevneresultat }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_sykdomskadelytebegrunnelse(): Expression<String> = vedtaksbrev.vedtaksdata.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ sykdomskadelytebegrunnelse }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_sykdomskadelyteresultat(): Expression<String> = vedtaksbrev.vedtaksdata.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ sykdomskadelyteresultat }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_unguforbegrunnelse(): Expression<String> = vedtaksbrev.vedtaksdata.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ unguforbegrunnelse }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_unguforresultat(): Expression<String> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ unguforresultat }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_yrkesskadebegrunnelse(): Expression<String> = vedtaksbrev.vedtaksdata.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ yrkesskadebegrunnelse }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_yrkesskaderesultat(): Expression<String> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ yrkesskaderesultat }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkarvirkningfom(): Expression<LocalDate?> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkarvirkningfom }
fun Expression<PEgruppe10>.vedtaksdata_virkningfom(): Expression<LocalDate> = vedtaksbrev.safe{ vedtaksdata }.safe{ virkningfom }.ifNull(LocalDate.now())
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningsresultattilrevurderingtotalnetto(): Expression<Kroner> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningsresultattilrevurderingtotalnetto }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_virkningbegrunnelse(): Expression<String> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ virkningbegrunnelse }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_forutgaendemedlemskap_unntakfraforutgaendemedlemskap(): Expression<Boolean> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ forutgaendemedlemskap }.safe{ unntakfraforutgaendemedlemskap }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksbrev_vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_forutgaendemedlemskap_inngangunntak(): Expression<String> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ forutgaendemedlemskap }.safe{ inngangunntak }.ifNull("")
fun Expression<PEgruppe10>.grunnlag_persongrunnlagsliste_trygdeavtaler_bostedslandbeskrivelse(): Expression<String> = vedtaksbrev.safe { grunnlag }.safe{ persongrunnlagsliste }.getOrNull().safe{ trygdeavtaler }.safe{ bostedslandbeskrivelse }.ifNull("")
fun Expression<PEgruppe10>.grunnlag_persongrunnlagsliste_trygdeavtaler_bostedslandbeskrivelse_nullable(): Expression<String?> = vedtaksbrev.safe { grunnlag }.safe{ persongrunnlagsliste }.getOrNull().safe{ trygdeavtaler }.safe{ bostedslandbeskrivelse }
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_fortsattmedlemskap_minst20arbotid(): Expression<Boolean> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ fortsattmedlemskap }.safe{ minst20arbotid }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_vilkar_forutgaendemedlemskap_minsttrearsfmnorge(): Expression<Boolean> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ vilkar }.safe{ forutgaendemedlemskap }.safe{ minsttrearsfmnorge }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_uforetidspunktbegrunnelse(): Expression<String> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ uforetidspunktbegrunnelse }.ifNull("")
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_instopphfasteutgifterperiodeliste_instopphfasteutgifterperiode_fasteutgifter(): Expression<Kroner> = vedtaksbrev.safe { grunnlag }.safe{ persongrunnlagsliste }.getOrNull().safe{ instopphfasteutgifterperiodeliste }.safe{ instopphfasteutgifterperiode }.getOrNull().safe{ fasteutgifter }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_instopphreduksjonsperiodeliste_instopphreduksjonsperiode_forsorgeransvar(): Expression<Boolean> = vedtaksbrev.safe { grunnlag }.safe{ persongrunnlagsliste }.getOrNull().safe{ instopphreduksjonsperiodeliste }.safe{ instopphreduksjonsperiode }.getOrNull().safe{ forsorgeransvar }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_kravhode_sokerbt(): Expression<Boolean> = vedtaksbrev.safe{ vedtaksdata }.safe{ kravhode }.safe{ sokerbt }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_harLopendealderspensjon(): Expression<Boolean> = vedtaksbrev.safe{ vedtaksdata }.safe{ harLopendealderspensjon }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_total(): Expression<Kroner> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningufore }.safe{ total }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningantallperioder(): Expression<Int> = vedtaksbrev.safe{ vedtaksdata }.safe{ beregningsdata }.safe{ beregningantallperioder }.ifNull(0)
fun Expression<PEgruppe10>.vedtaksdata_vilkarsvedtaklist_vilkarsvedtak_beregningsvilkar_mndvirkningstidpunkt(): Expression<Month> = vedtaksbrev.safe{ vedtaksdata }.safe{ vilkarsvedtaklist }.safe{ vilkarsvedtak }.getOrNull().safe{ beregningsvilkar }.safe{ virkningstidspunktmaned }.ifNull(Month.JANUARY)
fun Expression<PEgruppe10>.vedtakfattetdato_minus_1mnd(): Expression<LocalDate> = vedtaksbrev.safe{ vedtaksdata }.safe{ vedtakfattetdatominus1mnd }.ifNull(LocalDate.of(1000,1,1))
fun Expression<PEgruppe10>.ut_forsorgeransvar_ingen_er_false(): Expression<Boolean> = vedtaksbrev.safe { grunnlag }.safe{ persongrunnlagsliste }.getOrNull().safe{ instopphreduksjonsperiodeliste }.safe{ forsorgeransvaralle }.ifNull(false)
fun Expression<PEgruppe10>.ut_forsorgeransvar_ingen_er_true(): Expression<Boolean> = vedtaksbrev.safe { grunnlag }.safe{ persongrunnlagsliste }.getOrNull().safe{ instopphreduksjonsperiodeliste }.safe{ forsorgeransvaringen }.ifNull(true)
fun Expression<PEgruppe10>.ut_forsorgeransvar_siste_er_true(): Expression<Boolean> = vedtaksbrev.safe { grunnlag }.safe{ persongrunnlagsliste }.getOrNull().safe{ instopphreduksjonsperiodeliste }.safe{ forsorgeransvarsiste }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksbrev_grunnlag_persongrunnlagsliste_trygdetidsgrunnlageos_trygdetidsgrunnlageos_trygdetideosland(): Expression<String> = vedtaksbrev.safe { grunnlag }.safe { persongrunnlagsliste }.getOrNull().safe { trygdetidsgrunnlaglisteeos }.safe { trygdetidsgrunnlageos }.getOrNull().safe { trygdetideosland }.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_brutto(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { uforetrygdordiner }.safe { brutto }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.ut_tbu4071_btfbinnvilget(): Expression<Boolean> = functions.pe_ut_tbu4071_btfbinnvilget.ifNull(false)
fun Expression<PEgruppe10>.ut_inntekt_hoeyere_lavere(): Expression<String> = functions.pe_ut_inntekt_hoeyere_lavere.ifNull("")
fun Expression<PEgruppe10>.ut_fradrag_hoeyere_lavere(): Expression<String> = functions.pe_ut_fradrag_hoeyere_lavere.ifNull("")
fun Expression<PEgruppe10>.ut_bruttoetterreduksjonbt_hoeyere_lavere(): Expression<String> = functions.pe_ut_bruttoetterreduksjonbt_hoeyere_lavere.ifNull("")
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_gjenlevendetillegg_gtbrutto(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { gjenlevendetillegg }.safe{gtbrutto}.ifNull(Kroner(0))
fun Expression<PEgruppe10>.vedtaksdata_reaktiviseringsforskriften(): Expression<Boolean> = vedtaksbrev.safe { vedtaksdata }.safe{ reaktiviseringsforskriften }.ifNull(false)
fun Expression<PEgruppe10>.vedtaksdata_beregningsdata_beregningufore_beregningytelseskomp_uforetrygdordiner_nettoperar(): Expression<Kroner> = vedtaksbrev.safe { vedtaksdata }.safe { beregningsdata }.safe { beregningufore }.safe { beregningytelseskomp }.safe { uforetrygdordiner }.safe{ nettoperar }.ifNull(Kroner(0))
fun Expression<PEgruppe10>.saksdata_sakapogup(): Expression<Boolean> = functions.pe_saksdata_sakapogup.ifNull(false)
