:docinfo: shared
:source-highlighter: highlight.js
:toc:

= Phrases

Fraser er gjenbrukbare innholdskomponenter som kan inkluderes i flere maler.

== Hvorfor fraser?

* **Konsistent innhold** - Samme tekst brukes på tvers av brev
* **Enklere vedlikehold** - Endringer gjøres ett sted
* **Mindre duplisering** - Unngå copy-paste av innhold

== Frase-typer

Det finnes tre typer fraser for ulike bruksområder:

[cols="2,2,3"]
|===
|Type |Brukes i |Kan inneholde

|xref:dsl/phrases/OutlinePhrase.adoc[OutlinePhrase]
|`OutlineScope`
|`paragraph`, `title1-3`, kontrollstrukturer

|xref:dsl/phrases/ParagraphPhrase.adoc[ParagraphPhrase]
|`ParagraphScope`
|`text`, `list`, `table`, kontrollstrukturer

|xref:dsl/phrases/TextOnlyPhrase.adoc[TextOnlyPhrase]
|`TextOnlyScope`
|`text`, `eval`, `newline`, kontrollstrukturer
|===

== Grunnleggende eksempel

=== Definere en frase

[source,kotlin]
----
object RettTilAKlage : OutlinePhrase<LangBokmalNynorskEnglish>() {
    override fun OutlineOnlyScope<LangBokmalNynorskEnglish, Unit>.template() {
        title1 {
            text(
                bokmal { +"Du har rett til å klage" },
                nynorsk { +"Du har rett til å klage" },
            )
        }

        paragraph {
            text(
                bokmal { +"Du kan klage på vedtaket innen 6 uker." },
                nynorsk { +"Du kan klage på vedtaket innan 6 veker." },
            )
        }
    }
}
----

=== Bruke frasen

[source,kotlin]
----
outline {
    // ... brevinnhold ...

    includePhrase(RettTilAKlage)
}
----

== Parametriserte fraser

Fraser kan ta inn parametere:

[source,kotlin]
----
data class UtbetalingsInfo(
    val beloep: Expression<Kroner>,
    val dato: Expression<Int>
) : OutlinePhrase<LangBokmalNynorskEnglish>() {
    override fun OutlineOnlyScope<LangBokmalNynorskEnglish, Unit>.template() {
        paragraph {
            text(
                bokmal {
                    +"Du får utbetalt "
                    +beloep.format()
                    +" kroner den "
                    +dato.format()
                    +". hver måned."
                }
            )
        }
    }
}

// Bruk
includePhrase(UtbetalingsInfo(
    beloep = maanedligBeloep,
    dato = 20.expr()
))
----

== Organisering av fraser

Organiser fraser i logiske grupper:

[source]
----
fraser/
├── common/
│   ├── Felles.kt              # Generiske fraser
│   ├── Lovhenvisninger.kt     # Standardreferanser
│   └── KontaktInfo.kt         # Kontaktinformasjon
├── uforetrygd/
│   ├── BeregningFraser.kt     # Beregningsforklaringer
│   └── VilkaarFraser.kt       # Vilkårsbeskrivelser
└── barnetillegg/
    └── BarnetilleggFraser.kt  # Barnetillegg-fraser
----

== Frase-dokumentasjon

* xref:dsl/phrases/OutlinePhrase.adoc[OutlinePhrase] - Fraser med avsnitt og overskrifter
* xref:dsl/phrases/ParagraphPhrase.adoc[ParagraphPhrase] - Fraser med lister og tabeller
* xref:dsl/phrases/TextOnlyPhrase.adoc[TextOnlyPhrase] - Fraser kun med tekst
* xref:dsl/phrases/includePhrase.adoc[includePhrase] - Hvordan inkludere fraser

