// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.grunnlag.persongrunnlagsliste.trygdeavtaler

data class Trygdeavtaler(
    val avtaletype: String?
)
