// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningperiode.beregningytelsekomp

import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningperiode.beregningytelsekomp.familietillegg.Familietillegg
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningperiode.beregningytelsekomp.fasteutgifter.Fasteutgifter
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningperiode.beregningytelsekomp.grunnpensjon.Grunnpensjon
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningperiode.beregningytelsekomp.sertillegg.Sertillegg
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningperiode.beregningytelsekomp.tilleggspensjon.Tilleggspensjon

data class Beregningytelsekomp(
    val familietillegg: Familietillegg?,
    val fasteutgifter: Fasteutgifter?,
    val grunnpensjon: Grunnpensjon?,
    val sertillegg: Sertillegg?,
    val tilleggspensjon: Tilleggspensjon?
)
