app-name: "pensjon-brevbaker-t4"
pdf-bygger-app: "pensjon-pdf-bygger-t4"
ingresses:
  - "https://pensjon-brevbaker-t4.dev.adeo.no"
env:
  - name: PDF_BYGGER_URL
    value: "http://pensjon-pdf-bygger-t4:8080"