app-name: "pensjon-brevbaker"
pdf-bygger-app: "pensjon-pdf-bygger"
ingresses:
  - "https://pensjon-brevbaker.dev.intern.nav.no"
env:
  - name: PDF_BUILDER_URL
    value: "http://pensjon-pdf-bygger:8080"
  - name: STS_ISSUER
    value: "https://security-token-service.nais.preprod.local"
  - name: STS_JWKS_URI
    value: "https://security-token-service.nais.preprod.local/rest/v1/sts/jwks"
  - name: STS_ACCEPTED_AUDIENCE
    value: "srvpensjon"

preAuthorized:
  - name: pensjon-pen-q0
    namespace: teampensjon
    cluster: dev-fss
  - name: pensjon-pen-q1
    namespace: teampensjon
    cluster: dev-fss
  - name: pensjon-pen-q2
    namespace: teampensjon
    cluster: dev-fss
  - name: pensjon-pen-q4
    namespace: teampensjon
    cluster: dev-fss
  - name: pensjon-pen-q5
    namespace: teampensjon
    cluster: dev-fss