app-name: "pensjon-brevbaker"
pdf-bygger-app: "pensjon-pdf-bygger"
kafka-pool: "nav-dev"
kafka-pdf-render-topic: "pensjonsbrev.pdf-bygger-render"
enable-kafka: str(true)
ingresses:
  - "https://pensjon-brevbaker.intern.dev.nav.no"

groups:
  - "8bb9b8d1-f46a-4ade-8ee8-5895eccdf8cf" #0000-GA-PENSJON_SAKSBEHANDLER
  - "9e122ddd-e542-4cc1-a7eb-92c99140fe0e" #0000-GA-PENSJON_BRUKERHJELPA
  - "63f46f74-84a8-4d1c-87a8-78532ab3ae60" #0000-GA-PENSJON_ATTESTERING
  - "a3f91493-1ab8-4b64-a544-0a77cbba9240" #0000-GA-Pensjon_VEILEDER
  - "05ae245b-7b47-428a-9074-4ff6b59eddbc" #0000-GA-Pensjon_Okonomi
  - "02505029-3f2e-48a9-b2a8-ff274dacca52" #0000-GA-PENSJON_KLAGEBEH

preAuthorized:
  - name: pensjon-pen-q0
    namespace: pensjon-q0
    cluster: dev-fss
  - name: pensjon-pen-q1
    namespace: pensjon-q1
    cluster: dev-fss
  - name: pensjon-pen-q2
    namespace: pensjon-q2
    cluster: dev-fss
  - name: pensjon-pen-q5
    namespace: pensjon-q5
    cluster: dev-fss
  - name: pensjon-psak-q2
    namespace: pensjon-q2
    cluster: dev-fss
  - name: locust
    namespace: pensjonsbrev
    cluster: dev-gcp
  - name: skribenten-backend
    namespace: pensjonsbrev
    cluster: dev-gcp
  - name: etterlatte-brev-api
    namespace: etterlatte
    cluster: dev-gcp
  - name: brevoppskrift-web
    namespace: pensjonsbrev
    cluster: dev-gcp
