app-name: "pensjon-brevbaker"
pdf-bygger-app: "pensjon-pdf-bygger"
ingresses:
  - "https://pensjon-brevbaker.intern.dev.nav.no"

groups:
  - "8bb9b8d1-f46a-4ade-8ee8-5895eccdf8cf" #0000-GA-PENSJON_SAKSBEHANDLER

externalHosts:
  - teampensjon-unleash-api.nav.cloud.nais.io

preAuthorized:
  - name: pensjon-pen-q0
    namespace: pensjon-q0
    cluster: dev-fss
  - name: pensjon-pen-q1
    namespace: pensjon-q1
    cluster: dev-fss
  - name: pensjon-pen-q2
    namespace: pensjon-q2
    cluster: dev-fss
  - name: pensjon-pen-q5
    namespace: pensjon-q5
    cluster: dev-fss
  - name: pensjon-psak-q2
    namespace: pensjon-q2
    cluster: dev-fss
  - name: locust
    namespace: pensjonsbrev
    cluster: dev-gcp
  - name: skribenten-backend
    namespace: pensjonsbrev
    cluster: dev-gcp
  - name: etterlatte-brev-api
    namespace: etterlatte
    cluster: dev-gcp
  - name: brevoppskrift-web
    namespace: pensjonsbrev
    cluster: dev-gcp
