apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app-name}}
  namespace: "pensjonsbrev"
  labels:
    "team": "pensjonsbrev"
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{image}}
  port: 8080
  kafka:
    pool: {{kafka-pool}}
  terminationGracePeriodSeconds: 60
  service:
    port: 80
    protocol: http
  liveness:
    path: "/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 20
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/metrics"
    port: "8080"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"

  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          {{#each groups as |group|}}
             - id: {{group}}
          {{/each}}
        extra:
          - azp_name
  accessPolicy:
    outbound:
      rules:
        - application: {{pdf-bygger-app}}
        - application: pensjon-pdf-bygger-grpc
      external:
        - host: teampensjon-unleash-api.nav.cloud.nais.io
    inbound:
      rules:
        {{#each preAuthorized as |app|}}
           - application: {{app.name}}
             namespace: {{app.namespace}}
             cluster: {{app.cluster}}
        {{/each}}
  ingresses:
    {{#each ingresses as |url|}}
       - {{url}}
      {{/each}}
  env:
    - name: PDF_BUILDER_URL
      value: "http://pensjon-pdf-bygger"
    - name: PDF_BYGGER_MAX_RETRIES
      value: "250"
    - name: KAFKA_PDF_RENDER_TOPIC
      value: {{kafka-pdf-render-topic}}
    - name: ENABLE_KAFKA
      value: {{enable-kafka}}
  envFrom:
    - secret: pensjon-brevbaker-unleash-api-token