app-name: "pensjon-brevbaker"
pdf-bygger-app: "pensjon-pdf-bygger"
ingresses:
  - "https://pensjon-brevbaker.intern.nav.no"
env:
  - name: PDF_BUILDER_URL
    value: "http://pensjon-pdf-bygger:8080"

preAuthorized:
  - name: pensjon-pen
    namespace: teampensjon
    cluster: prod-fss
  - name: pensjon-pen-q0
    namespace: teampensjon
    cluster: dev-fss