app-name: "pensjon-brevbaker"
pdf-bygger-app: "pensjon-pdf-bygger"
ingresses:
  - "https://pensjon-brevbaker.intern.nav.no"

preAuthorized:
  - name: pensjon-pen
    namespace: pensjondeployer
    cluster: prod-fss
  - name: etterlatte-brev-api
    namespace: etterlatte
    cluster: prod-gcp
  - name: penbatch
    namespace: pensjon-batch
    cluster: prod-fss