app-name: "pensjon-brevbaker"
pdf-bygger-app: "pensjon-pdf-bygger"
ingresses:
  - "https://pensjon-brevbaker.intern.nav.no"

groups:
  - "0af3955f-df85-4eb0-b5b2-45bf2c8aeb9e" #0000-GA-PENSJON_SAKSBEHANDLER

preAuthorized:
  - name: pensjon-pen
    namespace: pensjondeployer
    cluster: prod-fss
  - name: etterlatte-brev-api
    namespace: etterlatte
    cluster: prod-gcp
  - name: skribenten-backend
    namespace: pensjonsbrev
    cluster: prod-gcp
