// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningytelsekomp

import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningytelsekomp.familetillegg.Familetillegg
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningytelsekomp.fasteutgifter.Fasteutgifter
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningytelsekomp.grunnpensjon.Grunnpensjon
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningytelsekomp.sertillegg.Sertillegg
import no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregning.beregningytelsekomp.tilleggspensjon.Tilleggspensjon

data class Beregningytelsekomp(
    val familetillegg: Familetillegg?,
    val fasteutgifter: Fasteutgifter?,
    val grunnpensjon: Grunnpensjon?,
    val sertillegg: Sertillegg?,
    val tilleggspensjon: Tilleggspensjon?
)
