:docinfo: shared
:source-highlighter: highlight.js

= Brevmal struktur

En brevmal inneholder en nøstet struktur av elementer som brukes til å representere innhold.

Strukturen består i praksis av ulike dsl scopes.

Ytterst er TemplateRootScope. Dette scopet bruker man ytterst når man lager en mal.

== Scopes og funksjoner
Brevmal-dsl'en definerer ulike scopes hvor man kan definere ulike typer innhold.
DSL'en tilgjengeliggjør kun å definere det innholdet som kan eksistere i en gitt kontekst.
Dette gjør det enklere å utforske muligheter og unngå feil.

Oversikten er ikke ment som en komplett teknisk referanse
, men som en praktisk oversikt.
I tillegg kan omtrent alle scopes bruke kontroll-strukturer (showIf, ifNull osv)
for å styre visning av innhold basert på data.


createTemplate(...){ TemplateRootScope }
createAttachment(...){ OutlineScope }

Det finnes også abstrakte klasser som man bruker til å lage fraser som bruker scopes av samme navn.
OutlinePhrase, ParagraphPhrase, TextOnlyPhrase og PlainTextOnlyPhrase.

TemplateRootScope {
    title { PlainTextScope }
    outline { OutlineScope }
    includeAttachment
    includeAttachmentIfNotNull
}

OutlineScope {
    includePhrase(OutlinePhrase)
    title[1,2,3] { PlainTextScope }
    paragraph { ParagraphScope }
}

ParagraphScope {
    includePhrase([Paragraph, Text, PlainText]Phrase)
    list
    table
    formText
    formChoice
    newline
}

TextScope {
    includePhrase([Text, PlainText]Phrase)
    text
}

PlainTextScope {
    includePhrase(PlainTextPhrase)
    text
}