// Generated by exstreamConverter. Do not edit manually.
package no.nav.pensjon.brev.api.model.maler.legacy.pegruppe2.vedtaksbrev.vedtaksdata.beregningsdata.beregningsrelasjoner

data class Beregningsrelasjoner(
    val avdodetternavn: String?,
    val avdodfornavn: String?,
    val avdodmellomnavn: String?
)
