name: .build-backend.yaml

on:
  workflow_call:
    inputs:
      image_suffix:
        description: "Image suffix"
        required: true
        type: string
      path:
        description: "Path to build"
        required: true
        type: string
        default: ""
      target:
        description: "target build folder name"
        required: true
        type: string
      gradleTarget:
        description: "gradle build target path"
        required: true
        type: string
      extraModulesToBuild:
        description: "Modules to build"
        required: false
        type: string
      buildImage:
        description: "Build image?"
        required: true
        type: boolean
      uploadJar:
        description: "Upload jar?"
        required: false
        type: boolean
        default: false
      requiresNode:
        description: "Gradle build requires node.js"
        required: false
        type: boolean
        default: false
    outputs:
      image:
        description: "Image name"
        value: ${{ jobs.build.outputs.image }}

env:
  JavaDistribution: "temurin"
  JavaVersion: 25

jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      packages: "read"
      id-token: "write"
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-encryption-key: ${{ secrets.GRADLEKEY }}
      - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          "distribution": ${{ env.JavaDistribution }}
          "java-version": ${{ env.JavaVersion }}
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        if: ${{ inputs.requiresNode }}
        with:
          node-version-file: ".tool-versions"
          registry-url: https://npm.pkg.github.com/
          scope: "@navikt"
          cache: "npm"
          cache-dependency-path: skribenten-web/frontend/package-lock.json
      - name: "publish common to Maven local"
        run: |
          ./gradlew :brevbaker:api-model-common:publishToMavenLocal
      - name: "publish extra modules to Maven local"
        if: ${{ inputs.extraModulesToBuild != '' }}
        run: |
          ./gradlew ${{ inputs.extraModulesToBuild }}
      - name: "compile and run tests"
        run: |
          ./gradlew :${{ inputs.gradleTarget }}:buildNeeded
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
      - name: "Build and publish container image to GAR"
        uses: nais/docker-build-push@31c3a7321909bcb20799fdf46153fec721fd9512 # v0
        id: docker-push
        if: ${{ inputs.buildImage && ((github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch') || (github.event_name == 'schedule' && github.ref == 'refs/heads/main')) }}
        with:
          team: pensjonsbrev
          image_suffix: ${{ inputs.image_suffix }}
          pull: true
          docker_context: ./${{ inputs.path }}
          dockerfile: ${{ inputs.path }}/Dockerfile
          salsa: false
      - name: "Upload jar"
        if: ${{ inputs.uploadJar }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{inputs.target}}-jar
          path: ${{ inputs.path }}/build/install/${{ inputs.target }}/lib
          if-no-files-found: 'error'
