name: .release.yaml

on:
  workflow_call:
    inputs:
      gradleTarget:
        description: "gradle build target path"
        required: true
        type: string
      changes:
        description: "Changes"
        required: true
        type: string
      localDependenciesToPublish:
        description: "publishToMavenLocal tasks required before building this artifact"
        required: false
        type: string

env:
  JavaDistribution: "temurin"
  JavaVersion: 25

jobs:
  release:
    runs-on: "ubuntu-latest"
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-encryption-key: ${{ secrets.GRADLEKEY }}
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          "distribution": ${{ env.JavaDistribution }}
          "java-version": ${{ env.JavaVersion }}
      - name: "publish local build dependencies"
        if: ${{ inputs.localDependenciesToPublish != '' }}
        run: |
          ./gradlew ${{ inputs.localDependenciesToPublish }}
      - name: "compile and run tests"
        env:
          GRADLE_TARGETS: ${{ inputs.gradleTarget }}
        run: |
          tasks=""
          for target in $GRADLE_TARGETS; do tasks="$tasks :$target:build"; done
          ./gradlew $tasks
      - name: "Release maven artifact"
        if: ${{ github.ref == 'refs/heads/main' && inputs.changes == 'true' }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GRADLE_TARGETS: ${{ inputs.gradleTarget }}
        run: |
          tasks=""
          for target in $GRADLE_TARGETS; do tasks="$tasks :$target:publish"; done
          ./gradlew $tasks -Dorg.gradle.configuration-cache=false
      - name: "Release maven manually"
        if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GRADLE_TARGETS: ${{ inputs.gradleTarget }}
        run: |
          tasks=""
          for target in $GRADLE_TARGETS; do tasks="$tasks :$target:publish"; done
          ./gradlew -Pversion="0-$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)-$(git rev-parse --short=12 HEAD)" $tasks -Dorg.gradle.configuration-cache=false
