name: .salsa.yaml

on:
  workflow_call:
    inputs:
      image:
        description: 'Image to analyze'
        required: true
        type: string

jobs:
  salsa:
    name: Generate SBOM, attest and sign image
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    permissions:
      id-token: "write"
    steps:
      - name: NAIS login
        uses: nais/login@40b72a35a18ddf2ad74b632461139ab838cc2a2f # v0
        id: login
        with:
          team: pensjonsbrev
      - name: Generate SBOM, attest and sign image
        id: attest-sign
        uses: nais/attest-sign@65d1aaa8b7dc5913ae02b80f16f7c1cf9bad6491 # v2.0.17
        with:
          image_ref: ${{ inputs.image }}
