name: .verify-frontend.yaml

on:
  workflow_call:
    inputs:
      workingDir:
        description: "Working directory"
        required: true
        type: string
      runTests:
        description: "Run tests"
        required: true
        type: boolean

jobs:
  verify-bff:
    name: Verify bff tests, lint and typescript errors
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".tool-versions"
          registry-url: https://npm.pkg.github.com/
          scope: "@navikt"
      - name: Install bff dependencies
        working-directory: ${{ inputs.workingDir }}/bff
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Run Biome lint
        working-directory: ${{ inputs.workingDir }}/bff
        run: npm run lint

      - name: Check for typescript errors
        working-directory: ${{ inputs.workingDir }}/bff
        run: npm run check-types

      - name: Build bff
        working-directory: ${{ inputs.workingDir }}/bff
        run: npm run build

  verify-frontend:
    name: Verify frontend tests, lint and typescript errors
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".tool-versions"
          cache: "npm"
          cache-dependency-path: ${{ inputs.workingDir }}/frontend/package-lock.json

      - name: Install dependencies
        working-directory: ${{ inputs.workingDir }}/frontend
        run: npm ci

      - name: Lint code and config
        working-directory: ${{ inputs.workingDir }}/frontend
        run: npm run lint

      - name: Lint css
        working-directory: ${{ inputs.workingDir }}/frontend
        run: npm run stylelint

      - name: Check types
        working-directory: ${{ inputs.workingDir }}/frontend
        run: npm run check-types

      - name: Run unit tests
        if: ${{ inputs.runTests }}
        working-directory: ${{ inputs.workingDir }}/frontend
        run: npm run test

      - name: Install e2e test runner and browser
        if: ${{ inputs.runTests }}
        working-directory: ${{ inputs.workingDir }}/frontend
        run: npx playwright install --with-deps chromium

      - name: Run e2e tests
        if: ${{ inputs.runTests }}
        working-directory: ${{ inputs.workingDir }}/frontend
        run: npx playwright test

      - name: Upload e2e artifacts
        uses: actions/upload-artifact@v6
        if: ${{ inputs.runTests && failure() }}
        with:
          name: playwright-artifacts
          path: ${{ inputs.workingDir }}/frontend/test/e2e-report/
