name: "Slett gamle/ubrukte container bilder"
on:
  pull_request:

jobs:
  cleanup-brevbaker:
    name: "Brevbaker: Fjern gamle container bilder"
    runs-on: "ubuntu-latest"
    permissions:
      packages: write
    steps:
      - uses: smartsquaregmbh/delete-old-packages@v0.7.0
        with:
          organization: navikt
          user: pensjonsbrev
          names: |
            pensjon-pdf-bygger
          type: docker
          dry-run: true
          token: "${{ secrets.GITHUB_TOKEN }}"