name: "Slett gamle/ubrukte container bilder"
on:
  pull_request:

jobs:
  cleanup-brevbaker:
    name: "Brevbaker: Fjern gamle container bilder"
    runs-on: "ubuntu-latest"
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: pensjon-pdf-bygger
          package-type: container
          min-versions-to-keep: 5
          token: "${{ secrets.GITHUB_TOKEN }}"