name: "Slett gamle/ubrukte container bilder"
on:
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  cleanup-pdf-bygger:
    name: "Pdf-bygger: Fjern gamle container bilder"
    runs-on: "ubuntu-latest"
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55
        with:
          package-name: pensjonsbrev/pdf-bygger
          package-type: container
          min-versions-to-keep: 10
          token: "${{ secrets.DELETE_PACKAGES_TOKEN }}"
