name: "Slett gamle/ubrukte container bilder"
on:
  pull_request:

jobs:
  cleanup-brevbaker:
    name: "Brevbaker: Fjern gamle container bilder"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/delete-package-versions@v4.1.1
        with:
          package-name: pensjonsbrev/pensjon-pdf-bygger
          package-type: container
          min-versions-to-keep: 5
          token: "${{ secrets.DELETE_PACKAGES_TOKEN }}"