name: "deploy: brevoppskrift-web"
'on':
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-brevoppskrift-web.yaml
      - brevoppskrift-web/**
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/.build-frontend.yaml
    secrets: inherit
    with:
      workingDir: brevoppskrift-web
      deployToProd: false