name: "deploy: brevoppskrift-web"
'on':
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-brevoppskrift-web.yaml
      - brevoppskrift-web/**
  workflow_dispatch:

defaults:
  run:
    working-directory: brevoppskrift-web

jobs:
  build:
    name: build
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
        with:
          node-version: '20'
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'

      - name: Install frontend
        working-directory: brevoppskrift-web/frontend
        run: npm install

      - name: Build frontend
        working-directory: brevoppskrift-web/frontend
        run: npm run build

      - name: Copy frontend dist into public directory of bff
        working-directory: brevoppskrift-web/frontend
        run: cp -r dist/ ../bff/public

      - name: Install bff dependencies
        working-directory: brevoppskrift-web/bff
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Build bff
        working-directory: brevoppskrift-web/bff
        run: npm run build

      - name: Build and push Docker container
        uses: nais/docker-build-push@791ebb6f74b82849c742a9bc9c97abe44c6c111f
        id: docker-build-push
        with:
          team: pensjonsbrev
          image_suffix: web
          docker_context: brevoppskrift-web/bff
          dockerfile: brevoppskrift-web/bff/Dockerfile
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev:
    name: Deploy app to dev
    permissions:
      contents: read
      id-token: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Deploy to DEV
        uses: nais/deploy/actions/deploy@a8718ab86a0c9bd63c6e3c8bbae747f62500c272
        env:
          CLUSTER: dev-gcp
          RESOURCE: brevoppskrift-web/bff/.nais/nais.yaml
          VAR: image=${{needs.build.outputs.image}}
          VARS: "brevoppskrift-web/bff/.nais/bff-dev.yaml"
