name: "Build and deploy brevbaker and pdf-bygger"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
    paths:
      - "pensjon-brevbaker/**"
      - "pdf-bygger/**"
      - ".github/workflows/pdfbygger-brevbaker.yml"
env:
  "IMAGE_BREVBAKER": "ghcr.io/${{ github.repository }}/pensjon-brevbaker:${{ github.sha }}"
  "IMAGE_PDF_BUILDER": "ghcr.io/${{ github.repository }}/pensjon-pdf-bygger:${{ github.sha }}"
jobs:
  snyk:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "Run Snyk to check for vulnerabilities"
        uses: "snyk/actions/gradle-jdk16@master"
        env:
          SNYK_TOKEN: "${{ secrets.SNYK_TOKEN }}"
        with:
          command: "monitor"
          args: "--org=pensjonsbrev --all-projects"
  "build-brevbaker":
    defaults:
      run:
        working-directory: pensjon-brevbaker
    name: "build brevbaker"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "actions/cache@v2"
        with:
          "path": "~/.gradle/caches"
          "key": "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}"
          "restore-keys": "${{ runner.os }}-gradle-"
      - uses: "actions/setup-java@v1"
        with:
          "java-version": "17"
      - name: "compile and run tests"
        run: |
          ../pensjon-brevbaker-api-model/gradlew --project-dir ../pensjon-brevbaker-api-model publishToMavenLocal
          ./gradlew build
        env:
          "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
      - name: "Build and publish Docker image"
        run: "docker build --pull --tag ${IMAGE_BREVBAKER} . && echo $GITHUB_TOKEN | docker login\
        \ --username $GITHUB_REPOSITORY --password-stdin https://ghcr.io\
        \ && docker push ${IMAGE_BREVBAKER}"
        env:
          "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"

  "build-pdfbygger":
    defaults:
      run:
        working-directory: pdf-bygger
    name: "build pdfbygger"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "docker/setup-buildx-action@v1"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: "actions/cache@v2"
        with:
          "path": "~/.gradle/caches"
          "key": "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}"
          "restore-keys": "${{ runner.os }}-gradle-"

      - name: "Cache docker layers"
        uses: "actions/cache@v2"
        with:
          path: "/tmp/.buildx-cache"
          key: "${{ runner.os }}-buildx-${{ github.sha }}"
          restore-keys: "${{ runner.os }}-buildx-"
      - uses: "actions/setup-java@v1"
        with:
          "java-version": "17"
      - name: "compile and run tests"
        run: "./gradlew build"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:pensjon-brevbaker"
          push: true
          tags: ${IMAGE_PDF_BUILDER}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
        #fix to not grow cache infinitely
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: | 
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
        env:
          "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"

  runIntegrationTests:
    defaults:
      run:
        working-directory: pensjon-brevbaker
    name: "Integration tests"
    needs: [ build-brevbaker, build-pdfbygger ]
    services:
      pdf-bygger:
        ports:
          - 8081:8080
        image: "ghcr.io/${{ github.repository }}/pensjon-pdf-bygger:${{ github.sha }}"
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      brevbaker:
        env:
          PDF_BUILDER_URL: "http://pdf-bygger:8080"
          AZURE_OPENID_CONFIG_JWKS_URI: "http://vtp-pensjon:8060/rest/isso/oauth2/connect/jwk_uri"
          AZURE_OPENID_CONFIG_ISSUER: "https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0"
          AZURE_APP_CLIENT_ID: "brevbaker-123"
          JAVA_OPTS: "-Dio.ktor.development=true"
        ports:
          - 8080:8080
        image: "ghcr.io/${{ github.repository }}/pensjon-brevbaker:${{ github.sha }}"
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/cache@v2"
        with:
          "path": "~/.gradle/caches"
          "key": "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}"
          "restore-keys": "${{ runner.os }}-gradle-"
      - uses: "actions/setup-java@v1"
        with:
          "java-version": "17"
      - name: "run integration tests"
        run: |
          ../pensjon-brevbaker-api-model/gradlew --project-dir ../pensjon-brevbaker-api-model publishToMavenLocal
          ./gradlew integrationTest
        env:
          "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          fail_if_no_tests: true
          fail_on_test_failures: true
          report_paths: '**/build/test-results/integrationTest/TEST-*.xml'

  "deployBrevbakerToDev":
    name: "Deploy brevbaker to dev"
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    needs: "runIntegrationTests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Deploy to DEV"
        uses: "nais/deploy/actions/deploy@v1"

        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "dev-gcp"
          "RESOURCE": "pensjon-brevbaker/.nais/nais.yaml"
          "VAR": image=${{ env.IMAGE_BREVBAKER }}
          "VARS": "pensjon-brevbaker/.nais/dev.yaml"

  "deployPdfByggerToDev":
    name: "Deploy pdf-bygger to dev"
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    needs: "runIntegrationTests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Deploy to DEV"
        uses: "nais/deploy/actions/deploy@v1"

        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "dev-gcp"
          "RESOURCE": "pdf-bygger/.nais/nais.yaml"
          "VAR": image=${{ env.IMAGE_PDF_BUILDER }}
          "VARS": "pdf-bygger/.nais/dev.yaml"

  "deployBrevbakerToProduction":
    name: "Deploy brevbaker to production"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: "runIntegrationTests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Deploy to production"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "prod-gcp"
          "RESOURCE": "pensjon-brevbaker/.nais/nais.yaml"
          "VAR": image=${{ env.IMAGE_BREVBAKER }}
          "VARS": "pensjon-brevbaker/.nais/prod.yaml"

  "deployPdfByggerToProduction":
    name: "Deploy pdf-bygger to production"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: "runIntegrationTests"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Deploy to production"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "prod-gcp"
          "RESOURCE": "pdf-bygger/.nais/nais.yaml"
          "VAR": image=${{ env.IMAGE_PDF_BUILDER }}
          "VARS": "pdf-bygger/.nais/prod.yaml"