name: "Build and deploy pdf-bygger"
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "build.gradle.kts"
      - "gradle.properties"
      - "gradle/libs.versions.toml"
      - "brevbaker/pdf-bygger/**"
      - ".github/workflows/.build-backend.yaml"
      - ".github/workflows/pdfbygger.yml"
      - ".github/workflows/cleanup.yml"
      - "gradle/wrapper/gradle-wrapper.jar"
      - "gradle/wrapper/gradle-wrapper.properties"
      - "!**/**.md"
  push:
    branches:
      - "main"
    paths:
      - "build.gradle.kts"
      - "gradle.properties"
      - "gradle/libs.versions.toml"
      - "brevbaker/pdf-bygger/**"
      - ".github/workflows/.build-backend.yaml"
      - ".github/workflows/pdfbygger.yml"
      - ".github/workflows/cleanup.yml"
      - "gradle/wrapper/gradle-wrapper.jar"
      - "gradle/wrapper/gradle-wrapper.properties"
      - "!**/**.md"
  schedule:
    - cron: '1 0 * * 6' # Kjører bygget rett etter cleanup har kjørt, for å sikre at vi har et main-tagga image
env:
  "IMAGE_PDF_BYGGER": "ghcr.io/${{ github.repository }}/pdf-bygger:${{ github.sha }}"
  "IMAGE_BRANCH": "ghcr.io/${{ github.repository }}/pdf-bygger:main"
  JavaDistribution: "temurin"
  JavaVersion: 25

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  buildPdfbygger:
    uses: ./.github/workflows/.build-backend.yaml
    secrets: inherit
    with:
      image_suffix: pdf-bygger
      path: brevbaker/pdf-bygger
      target: pdf-bygger
      gradleTarget: brevbaker:pdf-bygger
      buildImage: true
      uploadJar: true

  pushPdfByggerToGithubRegistry:
    name: "Push pdf-bygger to github registry"
    needs: buildPdfbygger
    runs-on: ubuntu-latest
    permissions:
      packages: "write"
      id-token: "write"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Download jar
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: pdf-bygger-jar
          path: brevbaker/pdf-bygger/build/install/pdf-bygger/lib
      - name: Docker login
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: "https://ghcr.io"
          username: ${{ github.repository }}
          password: ${{ github.token }}
      - name: "Build Docker image"
        run: |
          docker build --pull --tag ${IMAGE_PDF_BYGGER} brevbaker/pdf-bygger
      - name: "Push image with sha"
        run: |
          docker push ${IMAGE_PDF_BYGGER}
      - name: "Tag image with main"
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main' }}
        run: |
          docker tag ${IMAGE_PDF_BYGGER} ${IMAGE_BRANCH}
      - name: "Push image with main"
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main' }}
        run: |
          docker push ${IMAGE_BRANCH}

  salsa-pdfbygger:
    uses: ./.github/workflows/.salsa.yaml
    needs: buildPdfbygger
    secrets: inherit
    with:
      digest: ${{ needs.buildPdfbygger.outputs.digest }}
      image: ${{ needs.buildPdfbygger.outputs.image }}

  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      templates: ${{ steps.changes.outputs.templates }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        with:
          filters: |
            templates:
              - 'brevbaker/pdf-bygger/containerFiles/latex/**'
              - 'brevbaker/pdf-bygger/containerFiles/typst/**'
              - 'brevbaker/pdf-bygger/Dockerfile'
              - '.github/regconfig.json'
              - '.github/workflows/pdfbygger.yml'

  runIntegrationTests:
    name: "Integration tests"
    needs: [pushPdfByggerToGithubRegistry, changes]
    runs-on: ubuntu-latest-16-cores
    permissions:
      statuses: write
      checks: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          cache-encryption-key: ${{ secrets.GRADLEKEY }}
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          "distribution": ${{ env.JavaDistribution }}
          "java-version": ${{ env.JavaVersion }}
      - name: "run integration tests"
        run: |
          ./gradlew :brevbaker:api-model-common:publishToMavenLocal 
          ./gradlew :brevbaker:pdf-bygger:integrationTest
        env:
          "PDF_BYGGER_IMAGE": "ghcr.io/navikt/pensjonsbrev/pdf-bygger:${{ github.sha }}"
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@5609ce4db72c09db044803b344a8968fd1f315da # v1.9.1
        with:
          fail_if_no_tests: true
          fail_on_test_failures: true
          report_paths: "**/build/test-results/integrationTest/TEST-*.xml"
      - name: Upload images
        if: ${{ needs.changes.outputs.templates == 'true' || (github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')) }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: visuals
          path: brevbaker/pdf-bygger/build/test_visual/

  analyzeImages:
    name: "Analyze images"
    needs: [runIntegrationTests, changes]
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.templates == 'true' || (github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')) }}
    permissions:
      statuses: write
      checks: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Download visuals
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: visuals
          path: brevbaker/pdf-bygger/build/test_visual/
      - name: Install poppler-utils
        run: sudo apt-get install -y poppler-utils
      - name: Convert visual-test pdfs to png
        run: |
          mkdir -p brevbaker/pdf-bygger/build/test_visual/png
          find brevbaker/pdf-bygger/build/test_visual/pdf -name '*.pdf' | xargs -P $(nproc) -I{} sh -c 'pdftocairo -png -r 230 -singlefile "$1" brevbaker/pdf-bygger/build/test_visual/png/$(basename "$1" .pdf)' _ {}
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".tool-versions"
      - name: Install reg-suit
        run: npm install --no-save reg-suit reg-publish-gcs-plugin reg-notify-github-plugin reg-keygen-git-hash-plugin
      - name: Authenticate to Google Cloud
        uses: nais/login@c88ada9ce583928e1c84d2fd5c45cfacdd18d5de # v0
        with:
          team: pensjonsbrev
      - name: Run reg-suit
        run: npx reg-suit run --config $GITHUB_WORKSPACE/.github/regconfig.json
        working-directory: brevbaker/pdf-bygger/build/test_visual/png

  deployPdfByggerToDev:
    name: "Deploy pdf-bygger to dev"
    uses: ./.github/workflows/.deploy.yaml
    secrets: inherit
    needs: [runIntegrationTests, buildPdfbygger]
    with:
      cluster: "dev-gcp"
      resource: "brevbaker/pdf-bygger/.nais/nais.yaml,brevbaker/pdf-bygger/.nais/hpa.yaml"
      image: ${{needs.buildPdfbygger.outputs.image}}
      vars: "brevbaker/pdf-bygger/.nais/dev.yaml"

  deployPdfByggerToProd:
    name: "Deploy pdf-bygger to prod"
    uses: ./.github/workflows/.deploy.yaml
    secrets: inherit
    needs: [runIntegrationTests, buildPdfbygger]
    with:
      cluster: "prod-gcp"
      resource: "brevbaker/pdf-bygger/.nais/nais.yaml,brevbaker/pdf-bygger/.nais/hpa.yaml"
      image: ${{needs.buildPdfbygger.outputs.image}}
      vars: "brevbaker/pdf-bygger/.nais/prod.yaml"
      redeployProd: true

  "klarTilMerge":
    name: "Klar til merge"
    needs: [buildPdfbygger, pushPdfByggerToGithubRegistry, runIntegrationTests]
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/pr
