name: "Snyk vulnerability scan"
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  snyk:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "Run Snyk to check for vulnerabilities"
        uses: "snyk/actions/gradle-jdk16@master"
        env:
          SNYK_TOKEN: "${{ secrets.SNYK_TOKEN }}"
        with:
          command: "monitor"
          args: "--org=pensjonsbrev --all-projects"