name: "verify: brevoppskrift-web"

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - .github/workflows/.verify-frontend.yaml
      - .github/workflows/verify-brevoppskrift-web.yaml
      - brevoppskrift-web/**

permissions:
  contents: read
  packages: read

jobs:
  verify:
    uses: ./.github/workflows/.verify-frontend.yaml
    secrets: inherit
    with:
      workingDir: brevoppskrift-web
      runTests: false

  "klarTilMerge":
    name: "Klar til merge"
    needs: [verify]
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ./.github/pr
